Repository tektoncd/dashboard, pull requests merged in 2019-08, with the labels that each got.

#393 exporting getServiceAccountsErrorMessage fn in the reducer index
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/S

#390 Add doc for new extension types
  DEVELOPMENT.md
  docs/samples/extension/README.md
  docs/samples/extension/config/tekton-kubernetes-resource-extension-sample.yaml
Labels: approved, lgtm, size/M

#406 OpenShift oauth and https integration
  config/openshift/openshift-tekton-dashboard.yaml
Labels: approved, lgtm, size/L

#412 Add docs for release information
  README.md
Labels: approved, lgtm, size/M

#404 Bad helper text on Import Tekton resources panel
  src/containers/ImportResources/ImportResources.js
Labels: approved, lgtm, size/XS

#414 add endpoints api
  DEVELOPMENT.md
  Gopkg.lock
  Gopkg.toml
  cmd/dashboard/main.go
  config/dev-tekton-dashboard.yaml
  config/openshift/openshift-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/types.go
  pkg/router/router.go
  pkg/router/routes_test.go
Labels: approved, lgtm, size/L

#405 Create secrets panel is too short (hard to select last SA)
  src/components/SecretsModal/BasicAuthFields.js
  src/components/SecretsModal/BasicAuthFields.test.js
  src/components/SecretsModal/SecretsModal.scss
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/L

#415 HTTPS support - via Ingress
  README.md
  ingress/https-ingress.yaml
  ingress/ingress-https-setup.sh
Labels: approved, lgtm, size/M

#408 create a release pipeline for dashboard
  tekton/build.yml
  tekton/publish.yaml
  tekton/release-pipeline.yml
  tekton/resources.yaml
Labels: approved, lgtm, size/L

#429 Integration test fix
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#422 Update root storybook config to include sub-packages
  .eslintrc.js
  .storybook/.babelrc
  .storybook/config.js
  package-lock.json
  packages/components/package.json
  packages/components/src/utils/test.js
  packages/utils/package.json
Labels: approved, lgtm, size/M

#432 Remove duplicate storybook config
  packages/components/.storybook/Container.js
  packages/components/.storybook/Container.scss
  packages/components/.storybook/addons.js
  packages/components/.storybook/config.js
  packages/components/.storybook/webpack.config.js
Labels: approved, lgtm, size/L

#430 Correct the README format
  README.md
Labels: approved, lgtm, ok-to-test, size/M

#438 Readme update for v0.1.1
  README.md
Labels: approved, lgtm, size/XS

#436 Add missing defaultMessage for PipelineRuns error
  src/containers/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/XS

#442 First README for release process
  tekton/README.md
Labels: approved, lgtm, size/M

#443 Update README
  README.md
Labels: approved, lgtm, size/XS

#445 Fix labels not being copied over on rebuild
  pkg/endpoints/pipeline.go
Labels: approved, lgtm, size/XS

#434 Add sha256 values to images with latest tag
  config/openshift/openshift-tekton-dashboard.yaml
  config/pipeline0-task.yaml
  config/release/gcr-tekton-dashboard.yaml
  tekton/publish.yaml
  tekton/scripts/lockdown.py
Labels: approved, lgtm, size/L

#444 Make dashboard compatible with pipelines 0.6.0
  Gopkg.lock
  README.md
  pkg/endpoints/cluster.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  test/e2e-common.sh
Labels: approved, lgtm, size/L

#448 Update eslint-utils
  package-lock.json
Labels: approved, lgtm, size/S

#420 dependency update for issue134 in experimental repo
  package.json
Labels: approved, lgtm, size/XS

#457 Add lerna publish config and script
  lerna.json
  package-lock.json
  package.json
  packages/components/package.json
  packages/utils/package.json
Labels: approved, lgtm, size/S

#455 Add log fetching parameter to log component. Remove log container
  babel.config.js
  package.json
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
  src/containers/Log/index.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/index.js
  src/utils/index.js
Labels: approved, lgtm, size/XL

#458 add function to generate pipelineRun link
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
Labels: approved, lgtm, size/S

#459 Update dev docs to include bootstrap step for front-end sub-packages
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#460 Return on EstablishResourcesWebsocket error to prevent panic
  pkg/endpoints/websocket.go
Labels: approved, lgtm, size/XS

#462 Expose PipelineRun component through sub-package
  lerna.json
  packages/components/src/components/index.js
Labels: approved, lgtm, size/XS

#461 Fix layout of PipelineRun stories
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
Labels: approved, lgtm, size/XS

#427 Add filter by label functionality to PipelineRuns panel
  README.md
  package-lock.json
  src/api/index.js
  src/api/index.test.js
  src/constants/index.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.scss
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/XL
