Repository tektoncd/dashboard, pull requests merged in 2019-07, with the labels that each got.

#302 add accept header for logs
  pkg/endpoints/cluster.go
  src/api/index.js
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#311 Add enhanced roles for webhooks extension usage
  config/dev-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/S

#295 Surface create PipelineRun form
  src/api/index.js
  src/api/index.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.scss
Labels: approved, lgtm, size/L

#297 Fix unexpected merge on websocket update events
  src/reducers/reducerCreators.js
  src/reducers/reducerCreators.test.js
Labels: approved, lgtm, size/S

#312 Added pipeline0 to minishift install and updated install instructions
  README.md
  config/templates/build.yaml
  config/templates/deploy.yaml
Labels: approved, lgtm, size/M

#259 Add informer controller, restructure controllers and testing packages
  Dockerfile_race_test
  Dockerfile_test
  Gopkg.lock
  README.md
  cmd/dashboard/main.go
  pkg/broadcaster/broadcaster.go
  pkg/controllers/controller.go
  pkg/controllers/kubernetes/extension.go
  pkg/controllers/kubernetes/namespaces.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/endpoints/cluster.go
  pkg/endpoints/cluster_test.go
  pkg/endpoints/credential.go
  pkg/endpoints/credential_test.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/health.go
  pkg/endpoints/health_test.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
  pkg/endpoints/test-utils.go
  pkg/endpoints/types.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  pkg/router/router.go
  pkg/router/routes_test.go
  pkg/testutils/testutils.go
  pkg/utils/utils.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#314 Fix colour issue with error message in ClusterTasks
  src/containers/ClusterTasks/ClusterTasks.js
Labels: approved, lgtm, size/XS

#301 add cancel pipeline run selection to pipeline runs list
  src/api/index.js
  src/api/index.test.js
  src/components/CancelButton/CancelButton.js
  src/components/CancelButton/CancelButton.scss
  src/components/CancelButton/CancelButton.stories.js
  src/components/CancelButton/CancelButton.test.js
  src/components/CancelButton/index.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRunList/TaskRunList.js
  src/utils/index.js
Labels: approved, lgtm, size/L

#313 Delete unused back end APIs
  DEVELOPMENT.md
  pkg/endpoints/cluster.go
  pkg/endpoints/cluster_test.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  pkg/router/router.go
Labels: approved, lgtm, size/XXL

#319 Add clusterTaskEvents to resources websocket
  pkg/broadcaster/broadcaster.go
  pkg/controllers/controller.go
  pkg/controllers/tekton/clustertask.go
  pkg/endpoints/websocket_test.go
Labels: approved, lgtm, size/L

#317 Update DEVELOPMENT.md to suggest Node.js 10.x and npm ci over npm install
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#186 issue67 - secret management - main container & App configuration - merge order: last
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/components/Breadcrumbs/Breadcrumbs.js
  src/components/SecretsTable/Secrets.scss
  src/components/SecretsTable/SecretsTable.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/Secrets/index.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
Labels: approved, lgtm, size/L

#335 Temporarily disable e2e tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#273 Issue269 secret controller
  pkg/broadcaster/broadcaster.go
  pkg/controllers/controller.go
  pkg/controllers/kubernetes/extension.go
  pkg/controllers/kubernetes/namespaces.go
  pkg/controllers/kubernetes/secret.go
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/endpoints/cluster_test.go
  pkg/endpoints/websocket_test.go
Labels: approved, lgtm, size/L

#330 Update step container prefix
  README.md
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
Labels: approved, lgtm, size/S

#337 Fix StepDetails story
  src/components/StepDetails/StepDetails.stories.js
Labels: approved, lgtm, size/S

#336 Add storybook:deploy script
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#329 Display failed init steps
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/S

#340 Ensure consistent use of CRD names
  src/components/Breadcrumbs/Breadcrumbs.stories.js
  src/components/RunHeader/RunHeader.stories.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/L

#343 Remove unnecessary inline eslint config
  src/components/Log/Log.js
  src/components/Rebuild/Rebuild.js
Labels: approved, lgtm, size/S

#341 Ensure error messages are displayed in a consistent manner
  src/components/RunHeader/RunHeader.js
  src/components/RunHeader/RunHeader.stories.js
  src/components/RunHeader/RunHeader.test.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/Extensions/Extensions.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Secrets/Secrets.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#346 Add some missing unit tests
  src/index.js
  src/reducers/clusterTasks.js
  src/reducers/clusterTasks.test.js
  src/reducers/index.test.js
  src/store/index.js
  src/store/index.test.js
Labels: approved, lgtm, size/M

#348 Use react-window to improve performance of log rendering
  package-lock.json
  package.json
  src/components/Log/Log.js
  src/components/Log/Log.scss
  src/components/Log/Log.stories.js
  src/components/Log/Log.test.js
  src/containers/Log/Log.js
Labels: approved, lgtm, size/M

#338 Dashboard install and delete scripts for different namespace on Minishift
  README.md
  minishift-delete-dashboard.sh
  minishift-install-dashboard.sh
Labels: approved, lgtm, size/M

#352 [Testing] Enable e2e tests once more
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#351 Simplify command to access Dashboard
  README.md
Labels: approved, lgtm, size/S

#357 Sort run list views by startTime descending
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRunList/TaskRunList.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#355 Add role permissions to patch service accounts & delete secrets
  config/dev-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/XS

#362 Update lodash.merge
  package-lock.json
  package.json
Labels: approved, lgtm, size/M

#359 Ability to import resources into a target namespace
  Gopkg.lock
  config/pipeline0-task.yaml
  config/pipeline0.yaml
  config/release/gcr-tekton-dashboard.yaml
  package-lock.json
  pkg/endpoints/cluster.go
  pkg/endpoints/pipeline.go
  pkg/router/router.go
  src/api/index.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L

#345 secrets paneling polished
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.scss
  src/components/SecretsDeleteModal/SecretsDeleteModal.test.js
  src/components/SecretsModal/Annotations.js
  src/components/SecretsModal/BasicAuthFields.js
  src/components/SecretsModal/BasicAuthFields.test.js
  src/components/SecretsModal/SecretsModal.scss
  src/components/SecretsModal/UniversalFields.js
  src/components/SecretsTable/Secrets.scss
  src/components/SecretsTable/SecretsTable.js
  src/components/SecretsTable/SecretsTable.test.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SideNav/SideNav.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/XXL

#349 Fix pipeline-0 root directory default
  config/pipeline0-task.yaml
  config/pipeline0.yaml
  config/release/gcr-tekton-dashboard.yaml
  config/templates/deploy.yaml
  src/containers/ImportResources/ImportResources.js
Labels: approved, lgtm, size/S

#367 Fixed unit test timeout issue
  pkg/router/routes_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#365 Add utils for creating router paths and URLs
  src/components/Breadcrumbs/Breadcrumbs.stories.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/components/Rebuild/Rebuild.js
  src/components/StepDefinition/StepDefinition.js
  src/containers/App/App.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/Extension/Extension.js
  src/containers/Extensions/Extensions.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/Tasks/Tasks.js
  src/utils/index.js
  src/utils/index.test.js
  src/utils/router.js
  src/utils/router.test.js
Labels: approved, lgtm, size/XL

#369 secret's panel style tweaks
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.scss
  src/components/SecretsTable/Secrets.scss
Labels: approved, lgtm, size/S

#381 Add Megan Wright as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#380 Add OpenShift install instructions using a route and scc
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/M

#377 Update Log container to check for container name in step status
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
Labels: approved, lgtm, size/M

#386 Add permission to get ingress, sccs, harden ingress check
  config/dev-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
  pkg/endpoints/cluster.go
Labels: approved, lgtm, size/M

#382 Add mechanism for including other k8s resources
  config/dev-tekton-dashboard.yaml
  src/api/index.js
  src/api/index.test.js
  src/containers/App/App.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/ResourceList/ResourceList.js
  src/containers/ResourceList/index.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
  src/utils/router.js
Labels: approved, lgtm, size/L

#388 Add dashboard Ingress and patch command
  README.md
  config/dev-tekton-dashboard.yaml
  ingress/basic-dashboard-ingress.yaml
Labels: approved, lgtm, size/M

#391 Add extension crd to releases
  config/release/gcr-tekton-dashboard.yaml
  config/templates/deploy.yaml
Labels: approved, lgtm, size/M
