Repository tektoncd/dashboard, pull requests merged in 2019-06, with the labels that each got.

#199 Update selectors to support retrieving resources from all namespaces
  src/constants/index.js
  src/reducers/pipelineRuns.js
  src/reducers/pipelineRuns.test.js
  src/reducers/pipelines.js
  src/reducers/pipelines.test.js
  src/reducers/serviceAccounts.js
  src/reducers/serviceAccounts.test.js
  src/reducers/taskRuns.js
  src/reducers/taskRuns.test.js
  src/reducers/tasks.js
  src/reducers/tasks.test.js
Labels: approved, lgtm, size/M

#174 Add all namespaces selection on rest apis
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L

#196 Update NamespacesDropdown to support 'All Namespaces' option
  src/components/TooltipDropdown/TooltipDropdown.js
  src/components/TooltipDropdown/TooltipDropdown.test.js
  src/containers/App/App.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
Labels: approved, lgtm, size/M

#204 Bump tektoncd/plumbing with latest fixes
  Gopkg.lock
Labels: approved, lgtm, size/XS

#209 Publish the nightly image with a stable reference
  test/publish-images.sh
Labels: approved, lgtm, size/XS

#210 Fix the grep for getting the image name
  test/publish-images.sh
Labels: approved, lgtm, size/XS

#182 Add panelling to Import Tekton resources from repository
  config/pipeline0-task.yaml
  config/pipeline0.yaml
  pkg/endpoints/pipeline.go
  pkg/endpoints/router.go
  src/api/index.js
  src/components/Breadcrumbs/Breadcrumbs.js
  src/containers/App/App.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/ImportResources/ImportResources.test.js
  src/containers/ImportResources/index.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/index.js
Labels: approved, lgtm, size/L

#187 issue67 - secret management - table & confirm delete modal - merge order: 1st
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.scss
  src/components/SecretsDeleteModal/SecretsDeleteModal.test.js
  src/components/SecretsDeleteModal/index.js
  src/components/SecretsTable/Secrets.scss
  src/components/SecretsTable/SecretsTable.js
  src/components/SecretsTable/SecretsTable.test.js
  src/components/SecretsTable/index.js
Labels: approved, lgtm, size/L

#213 Update client URLs to include namespace
  src/components/Breadcrumbs/Breadcrumbs.js
  src/components/Breadcrumbs/Breadcrumbs.test.js
  src/components/StepDetails/StepDetails.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/ImportResources/ImportResources.js
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/containers/SideNav/index.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/index.js
  src/reducers/namespaces.js
  src/reducers/namespaces.test.js
  src/utils/test.js
Labels: approved, lgtm, size/XL

#217 issue195 - removed transform value so modals display properly
  src/components/App/App.scss
Labels: approved, lgtm, size/XS

#221 Enable websocket support in dev proxy
  webpack.dev.js
Labels: approved, lgtm, size/XS

#218 Add namespace to list views when viewing 'all namespaces'
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/M

#220 Add namespaces dropdown to import resources view
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/ImportResources/ImportResources.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
Labels: approved, lgtm, size/L

#214 Handle PipelineRun that failed to start
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/M

#224 Update service accounts dropdown when namespace selection is changed
  src/containers/ImportResources/ImportResources.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
Labels: approved, lgtm, size/S

#225 Fix 'all namespaces' on service accounts API
  pkg/endpoints/cluster.go
Labels: approved, lgtm, size/XS

#216 Issue 221-Add yaml to install gcr images, updated docs
  README.md
  config/dev-tekton-dashboard.yaml
  config/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/M

#192 Namespace message too verbose
  pkg/endpoints/cluster.go
Labels: approved, lgtm, size/XS

#226 add log polling and pod/container log api
  pkg/endpoints/pipeline.go
  pkg/endpoints/router.go
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.js
  src/api/index.test.js
  src/components/Log/Log.js
  src/components/Log/Log.stories.js
  src/components/Log/Log.test.js
  src/components/StepDetails/StepDetails.js
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
Labels: approved, lgtm, size/L

#219 namespace field in credential struct
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
Labels: approved, lgtm, size/XS

#230 Add dev install script, modify readme to use, pipeline definitions in release yaml
  README.md
  config/gcr-tekton-dashboard.yaml
  config/pipeline0-task.yaml
  config/pipeline0.yaml
  config/release/gcr-tekton-dashboard.yaml
  install-dev.sh
  package-lock.json
Labels: approved, lgtm, size/L

#231 Move websocket to /resources. Add task and Pipeline Events to the web…
  Gopkg.lock
  cmd/dashboard/main.go
  pkg/broadcaster/broadcaster.go
  pkg/endpoints/cluster.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/router.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  src/api/index.js
Labels: approved, lgtm, size/L

#238 Enable linting for sort order of member imports
  .eslintrc.js
  src/containers/App/App.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/reducers/index.test.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#233 Add PipelineResources reducers, actions, and selectors
  src/actions/pipelineResources.js
  src/actions/pipelineResources.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/pipelineResources.js
  src/reducers/pipelineResources.test.js
Labels: approved, lgtm, size/XL

#234 Add PipelineResources as a top-level item in nav
  src/components/Breadcrumbs/Breadcrumbs.js
  src/containers/App/App.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResource/index.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResources/index.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
Labels: approved, lgtm, size/L

#239 Tie namespace, task and pipeline events into the store
  src/reducers/namespaces.js
  src/reducers/namespaces.test.js
  src/reducers/pipelines.js
  src/reducers/pipelines.test.js
  src/reducers/tasks.js
  src/reducers/tasks.test.js
Labels: approved, lgtm, size/L

#243 Add eventing for PipelineResources on the back end
  pkg/broadcaster/broadcaster.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/websocket_test.go
Labels: approved, lgtm, size/L

#208 Add paneling for manually creating a PipelineRun
  DEVELOPMENT.md
  Dockerfile
  pkg/endpoints/pipeline.go
  src/api/index.js
  src/components/App/App.scss
  src/containers/App/App.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.scss
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreatePipelineRun/index.js
  src/containers/ImportResources/ImportResources.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
Labels: approved, lgtm, size/XXL

#242 Use timestamp as uid for manual pipelineruns
  pkg/endpoints/pipeline.go
Labels: approved, lgtm, size/S

#244 List Tekton Pipelines as a prereq in the README
  README.md
Labels: approved, lgtm, size/XS

#248 Reduce duplication in namespaced reducers
  package-lock.json
  package.json
  src/reducers/pipelineResources.js
  src/reducers/pipelineRuns.js
  src/reducers/pipelines.js
  src/reducers/reducerCreators.js
  src/reducers/reducerCreators.test.js
  src/reducers/taskRuns.js
  src/reducers/tasks.js
Labels: approved, lgtm, size/XL

#249 Reduce duplication in namespaced reducer tests
  src/reducers/index.js
  src/reducers/pipelineResources.js
  src/reducers/pipelineResources.test.js
  src/reducers/pipelineRuns.js
  src/reducers/pipelineRuns.test.js
  src/reducers/pipelines.js
  src/reducers/pipelines.test.js
  src/reducers/serviceAccounts.js
  src/reducers/serviceAccounts.test.js
  src/reducers/taskRuns.js
  src/reducers/taskRuns.test.js
  src/reducers/tasks.js
  src/reducers/tasks.test.js
Labels: approved, lgtm, size/XL

#250 Add PipelineResourcesDropdown container
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineResourcesDropdown/index.js
Labels: approved, lgtm, size/XL

#256 Fix import resources page bug with the serviceaccount reducer
  src/reducers/index.js
Labels: approved, lgtm, size/XS

#251 Reduce duplication in namespace and extension reducers
  src/reducers/extensions.js
  src/reducers/namespaces.js
  src/reducers/reducerCreators.js
Labels: approved, lgtm, size/M

#252 Update extensions actions to be consistent with others
  src/actions/extensions.js
  src/actions/extensions.test.js
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#258 Add ParamsInput component
  src/components/TextInput/TextInput.js
  src/components/TextInput/TextInput.stories.js
  src/components/TextInput/TextInput.test.js
  src/components/TextInput/index.js
Labels: approved, lgtm, size/L

#266 update table so it does not use deprecated uid as key
  src/components/SecretsTable/SecretsTable.js
Labels: approved, lgtm, size/XS

#185 issue67 - secrets management - actions & reducers - merge order: 1st
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/api/index.js
  src/api/index.test.js
  src/containers/Extension/actions.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/XL

#271 Prevent wrapping on long step names
  src/components/Step/Step.js
  src/components/Step/Step.scss
Labels: approved, lgtm, size/S

#263 Display secrets in PipelineResource view
  src/components/App/App.scss
  src/containers/PipelineResource/PipelineResource.js
Labels: approved, lgtm, size/L

#265 Prevent wrapping of long run names at smaller window sizes
  src/components/RunHeader/RunHeader.js
  src/components/RunHeader/RunHeader.scss
Labels: approved, lgtm, size/S

#260 Reduce duplication in action creators for fetching collections
  src/actions/actionCreators.js
  src/actions/actionCreators.test.js
  src/actions/extensions.js
  src/actions/extensions.test.js
  src/actions/namespaces.js
  src/actions/namespaces.test.js
  src/actions/pipelineResources.js
  src/actions/pipelineResources.test.js
  src/actions/pipelineRuns.js
  src/actions/pipelineRuns.test.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/actions/serviceAccounts.js
  src/actions/serviceAccounts.test.js
  src/actions/taskRuns.js
  src/actions/taskRuns.test.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/reducers/reducerCreators.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/XL

#264 Add End2End PipelineRun test
  test/Pipeline.yaml
  test/deploy-task-insecure.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/kaniko-build-task.yaml
  test/test-rbac.yaml
Labels: approved, lgtm, size/L

#275 Reduce duplication in action creators for fetching single resources
  src/actions/actionCreators.js
  src/actions/actionCreators.test.js
  src/actions/pipelineResources.js
  src/actions/pipelineResources.test.js
  src/actions/pipelineRuns.js
  src/actions/pipelineRuns.test.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/actions/taskRuns.js
  src/actions/taskRuns.test.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/api/index.js
  src/api/index.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/XL

#270 Add type prop to PipelineResourcesDropdown
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
Labels: approved, lgtm, size/L

#280 Ensure braces are always added for blocks
  .eslintrc.js
Labels: approved, lgtm, size/XS

#281 Update to Carbon 10.3
  package-lock.json
  package.json
  src/components/App/App.scss
  src/components/Breadcrumbs/Breadcrumbs.js
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Run/Run.scss
  src/components/RunHeader/RunHeader.scss
  src/components/SideNavMenu/SideNavMenu.js
  src/components/SideNavMenu/SideNavMenu.test.js
  src/components/SideNavMenu/index.js
  src/containers/App/App.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/Extensions/Extensions.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.scss
  src/containers/SideNav/SideNav.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/L

#283 Remove unnecessary use of fragments in containers
  src/containers/Extensions/Extensions.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/XL

#284 Rename websocket to reflect actual use
  src/api/index.js
  src/index.js
  src/store/index.js
Labels: approved, lgtm, size/S

#285 Fix ToastNotification display in Import resources view
  src/containers/ImportResources/ImportResources.js
Labels: approved, lgtm, size/XS

#268 Add proxy for apiserver
  DEVELOPMENT.md
  Gopkg.lock
  README.md
  cmd/dashboard/main.go
  config/dev-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
  config/templates/build.yml
  config/templates/deploy.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/router.go
  test/Pipeline.yaml
  test/deploy-task-insecure.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/kaniko-build-task.yaml
  test/test-rbac.yaml
Labels: approved, lgtm, size/L

#188 issue67 - secrets management - add new secret modal - merge order: 1st
  src/components/SecretsModal/Annotations.js
  src/components/SecretsModal/Annotations.test.js
  src/components/SecretsModal/BasicAuthFields.js
  src/components/SecretsModal/BasicAuthFields.test.js
  src/components/SecretsModal/SecretsModal.scss
  src/components/SecretsModal/UniversalFields.js
  src/components/SecretsModal/UniversalFields.test.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SecretsModal/index.js
Labels: approved, lgtm, size/XXL

#278 Add Cluster task navigation
  src/actions/actionCreators.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/api/index.js
  src/components/StepDetails/StepDetails.js
  src/containers/App/App.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTasks/index.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/SideNav/SideNav.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/index.js
  src/reducers/clusterTasks.js
  src/reducers/clusterTasks.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  webpack.dev.js
Labels: approved, lgtm, size/XL

#282 PipelineRun creation form for arbitrary pipelines
  package-lock.json
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/index.js
Labels: approved, lgtm, size/XXL

#287 Specify tekton-pipelines namespace in gcr tekton dashboard yaml
  config/dev-tekton-dashboard.yaml
  config/pipeline0-task.yaml
  config/pipeline0.yaml
  config/release/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/XS

#291 Switch front-end to use kube API for Tekton resource GET requests
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#288 Fix breadcrumb label for ClusterTasks
  src/components/Breadcrumbs/Breadcrumbs.js
Labels: approved, lgtm, size/XS

#293 Add Dashboard ingress REST API endpoint
  DEVELOPMENT.md
  pkg/endpoints/cluster.go
  pkg/endpoints/cluster_test.go
  pkg/endpoints/router.go
Labels: approved, lgtm, size/M

#294 Update namespaces, service accounts, and logs APIs to use kube API
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#296 Fix error with task API call from TaskRun page
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/XS
