Repository tektoncd/dashboard, pull requests merged in 2019-11, with the labels that each got.

#685 Populate Secret Annotation Fields with Default Value
  src/components/SecretsModal/Annotations.js
  src/components/SecretsModal/Annotations.test.js
  src/components/SecretsModal/SecretsModal.scss
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
Labels: approved, lgtm, size/L

#690 Fix integration tests
  test/e2e-common.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  test/resources/envsubst/pipelinerun.yaml
  test/resources/static/kaniko-build-task.yaml
Labels: approved, lgtm, size/M

#686 Add API, actions, and reducers to get Triggers resources
  src/actions/eventListeners.js
  src/actions/eventListeners.test.js
  src/actions/secrets.js
  src/actions/triggerBindings.js
  src/actions/triggerBindings.test.js
  src/actions/triggerTemplates.js
  src/actions/triggerTemplates.test.js
  src/api/index.js
  src/api/index.test.js
  src/reducers/eventListeners.js
  src/reducers/eventListeners.test.js
  src/reducers/triggerBindings.js
  src/reducers/triggerBindings.test.js
  src/reducers/triggerTemplates.js
  src/reducers/triggerTemplates.test.js
Labels: approved, lgtm, size/XL

#696 Only selectDefaultStep in componentDidMount
  packages/components/src/components/Task/Task.js
Labels: approved, lgtm, size/XS

#694 Add support for custom notifications in PipelineRun component
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/M

#695 Reference 0.2.1 release in readme
  README.md
Labels: approved, lgtm, size/XS

#700 Fix release links in readme
  README.md
Labels: approved, lgtm, size/XS

#698 Publish @tektoncd/dashboard-components 0.0.1-alpha.26
  lerna.json
Labels: approved, lgtm, size/XS

#703 Fix README formatting
  README.md
Labels: approved, lgtm, size/XS

#702 Add support for displaying custom trigger info in RunHeader
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
Labels: approved, lgtm, size/M

#706 Pass triggerHeader prop to RunHeader
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#707 Publish @tektoncd/dashboard-components@0.0.1-alpha.28
  lerna.json
Labels: approved, lgtm, size/XS

#722 Changed icon from x to trash bin on secrets modal
  src/components/SecretsModal/Annotations.js
Labels: approved, lgtm, size/XS

#730 Remove unused code in comms.js
  src/api/comms.js
Labels: approved, lgtm, size/S

#732 First pass PipelineGraph UI component
  package-lock.json
  package.json
  packages/components/src/components/Graph/Graph.scss
  packages/components/src/components/Graph/Graph.stories.js
  packages/components/src/components/Graph/InlineLoading.js
  packages/components/src/components/Graph/Node.js
  packages/components/src/components/Graph/NodeLink.js
  packages/components/src/components/Graph/PipelineGraph.js
  packages/components/src/components/Graph/sample.json
Labels: approved, lgtm, size/XL

#710 Reusable Table Component
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/Table.test.js
  packages/components/src/components/Table/index.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/XL

#737 Prevent PipelineRuns page from resetting on websocket reconnect
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/S

#735 Always show namespace column on list views
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  src/components/SecretsTable/SecretsTable.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/L

#739 Publish @tektoncd/dashboard-componenents 0.0.1-alpha.29
  lerna.json
Labels: approved, lgtm, size/XS

#743 Update graph components to support displaying steps
  package.json
  packages/components/src/components/Graph/Graph.js
  packages/components/src/components/Graph/Graph.scss
  packages/components/src/components/Graph/Graph.stories.js
  packages/components/src/components/Graph/Node.js
  packages/components/src/components/Graph/NodeLink.js
  packages/components/src/components/Graph/sample.json
Labels: approved, lgtm, size/L

#745 add status and status icon as params
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/S

#734 Trigger Templates Page
  packages/utils/src/utils/router.js
  src/containers/App/App.js
  src/containers/SideNav/SideNav.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/TriggerTemplates/TriggerTemplates.scss
  src/containers/TriggerTemplates/TriggerTemplates.test.js
  src/containers/TriggerTemplates/index.js
  src/containers/index.js
  src/nls/messages_en.json
  src/reducers/index.js
Labels: approved, lgtm, size/XL

#748 Update Secret Action Test Coverage
  src/actions/secrets.test.js
Labels: approved, lgtm, size/M

#751 Publish @tektoncd/dashboard-components@0.0.1-alpha.30
  lerna.json
Labels: approved, lgtm, size/XS

#750 Add graph model generator and update UI components
  packages/components/src/components/Graph/Graph.js
  packages/components/src/components/Graph/Graph.stories.js
  packages/components/src/components/Graph/Node.js
  packages/components/src/components/Graph/PipelineGraph.js
  packages/components/src/components/Graph/buildGraphData.js
  packages/components/src/components/Graph/examples/graph.json
  packages/components/src/components/Graph/examples/pipeline.json
  packages/components/src/components/Graph/examples/pipelineRun.json
  packages/components/src/components/Graph/examples/tasks.json
Labels: approved, lgtm, size/XXL

#749 Update Utils Test Coverage
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#738 Removed some colons from field names
  src/components/SecretsModal/Annotations.js
  src/components/SecretsModal/BasicAuthFields.js
  src/components/SecretsModal/UniversalFields.js
Labels: approved, lgtm, size/S

#755 Fix issue preventing secrets modal from rendering correctly
  src/components/SecretsTable/SecretsTable.js
Labels: approved, lgtm, size/S

#752 Update dev md docs
  DEVELOPMENT.md
Labels: approved, lgtm, size/L

#740 Get rid of references to Build and Building
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/components/src/components/Rebuild/Rebuild.scss
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/Rerun/Rerun.scss
  packages/components/src/components/Rerun/Rerun.test.js
  packages/components/src/components/Rerun/index.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/Table.test.js
  packages/components/src/components/index.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  pkg/endpoints/pipeline.go
  pkg/router/router.go
  pkg/router/routes_test.go
  src/api/index.js
  src/components/Definitions/Definitions.scss
  src/containers/PipelineRun/PipelineRun.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#754 Add ErrorBoundary around page routes
  packages/components/src/components/PageErrorBoundary/PageErrorBoundary.js
  packages/components/src/components/PageErrorBoundary/PageErrorBoundary.test.js
  packages/components/src/components/PageErrorBoundary/index.js
  packages/components/src/components/index.js
  src/containers/App/App.js
Labels: approved, lgtm, size/L

#760 npm audit fix
  package-lock.json
Labels: approved, lgtm, size/M

#765 Remove unused prop from PipelineRuns component
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#763 Ensure PageErrorBoundary forces child update on navigation
  packages/components/src/components/PageErrorBoundary/PageErrorBoundary.js
  packages/components/src/components/PageErrorBoundary/PageErrorBoundary.test.js
Labels: approved, lgtm, size/S

#764 Bypass createPipelineRunsByPipelineURL method when Pipeline is Embedded
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/S

#728 Secrets modal scrolls to end when server urls are added
  package-lock.json
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SecretsModal/SecretsModalAnnotationText.test.js
Labels: approved, lgtm, size/M

#766 Convert NodeLink to functional component
  packages/components/src/components/Graph/NodeLink.js
Labels: approved, lgtm, size/M

#767 Move graph data model builder to utils package
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/components/Graph/Graph.js
  packages/components/src/components/Graph/PipelineGraph.js
  packages/components/src/components/index.js
  packages/utils/src/utils/buildGraphData.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/status.js
Labels: approved, lgtm, size/M

#777 Change instances of 'date modified' to 'date created' for trigger resources
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/Table.test.js
  src/containers/EventListeners/EventListeners.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/S

#781 stop log polling once step has completed
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/XS

#785 Add hide pipeline option
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/M

#783 Publish @tektoncd/dashboard-components 0.0.1-alpha.31
  lerna.json
Labels: approved, lgtm, size/XS

#788 Publish @tektoncd/dashboard-components 0.0.1-alpha.32
  lerna.json
Labels: approved, lgtm, size/XS

#791 Revert "stop log polling once step has completed"
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/XS

#794 Fix step name wrapping
  packages/components/src/components/Step/Step.scss
Labels: approved, lgtm, size/XS

#795 Revert "Fix error showing TaskRun steps that have not run"
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/Task/Task.test.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L
