Repository tektoncd/dashboard, pull requests merged in 2019-12, with the labels that each got.

#792 Delete pipeline resources
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/PipelineResources/index.js
  packages/components/src/components/index.js
  src/api/index.js
  src/api/index.test.js
  src/containers/PipelineResources/PipelineResources.js
Labels: approved, lgtm, size/L

#798 Delete taskruns
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  packages/components/src/components/TaskRuns/index.js
  packages/components/src/components/index.js
  src/api/index.js
  src/api/index.test.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/XL

#802 LabelFilter character limit
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LabelFilter/LabelFilter.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#808 Update graph styles
  packages/components/src/components/Graph/Graph.js
  packages/components/src/components/Graph/Graph.scss
  packages/components/src/components/Graph/Graph.stories.js
  packages/components/src/components/Graph/Node.js
  packages/components/src/components/Graph/NodeLink.js
  packages/utils/src/utils/buildGraphData.js
Labels: approved, lgtm, size/M

#811 Add dibbles to list of approvers
  OWNERS
Labels: approved, lgtm, size/XS

#809 View YAML reusable component
  packages/components/src/components/ViewYAML/ViewYAML.js
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
  packages/components/src/components/ViewYAML/ViewYAML.test.js
  packages/components/src/components/ViewYAML/index.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/L

#810 Format Metadata Label Util Method
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#812 Disable flaky TestExtensionRegistration
  pkg/router/routes_test.go
Labels: approved, lgtm, size/XS

#804 Change 'serviceAccount' to 'serviceAccountName'
  README.md
  packages/components/src/components/Graph/examples/pipelineRun.json
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  pkg/endpoints/pipeline.go
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#814 Move formatLabels to utils
  package-lock.json
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#768 Namespaces changed to all Namespaces doesn't change page
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/L

#818 Update README for v0.3.0
  README.md
Labels: approved, lgtm, size/XS

#823 Hide trigger nav items when triggers not installed
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/M

#825 Fix regression on TaskRuns list for inline Task specs
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/L

#687 Document test-release process
  tekton/README.md
Labels: approved, lgtm, size/M

#826 Add test for TaskRuns component
  src/containers/TaskRuns/TaskRuns.test.js
Labels: approved, lgtm, ok-to-test, size/L

#828 Update PipelineResources container to use UI component again
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/Table/Table.js
  src/containers/PipelineResources/PipelineResources.js
Labels: approved, lgtm, size/L

#820 Add ZoomablePipelineGraph component
  package-lock.json
  packages/components/package.json
  packages/components/src/components/Graph/Graph.js
  packages/components/src/components/Graph/Graph.stories.js
  packages/components/src/components/Graph/Node.js
  packages/components/src/components/Graph/PanZoom.js
  packages/components/src/components/Graph/PipelineGraph.js
  packages/components/src/components/Graph/ZoomablePipelineGraph.js
  packages/components/src/components/Graph/ZoomablePipelineGraph.scss
  packages/components/src/components/Graph/examples/graph.json
Labels: approved, lgtm, size/L

#838 Notifications stretch entire width of page
  src/components/Definitions/Definitions.scss
Labels: approved, lgtm, size/XS

#841 Update CSS for data tables
  package-lock.json
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/M

#797 TriggerBindings Details Page
  packages/utils/src/utils/router.js
  src/containers/App/App.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerBinding/index.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/index.js
  src/nls/messages_en.json
  src/scss/Triggers.scss
Labels: approved, lgtm, size/XL

#834 Update Secrets container to use Reusable Table component
  package-lock.json
  packages/components/src/components/Table/Table.scss
  src/actions/secrets.js
  src/components/SecretsTable/Secrets.scss
  src/components/SecretsTable/SecretsTable.js
  src/components/SecretsTable/SecretsTable.test.js
  src/components/SecretsTable/index.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XL

#835 Handle inline Pipeline spec
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/M

#729 Add TriggerTemplate details panelling
  package-lock.json
  packages/components/src/components/Table/Table.js
  packages/utils/src/utils/router.js
  src/containers/App/App.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/containers/TriggerTemplate/TriggerTemplateTable.scss
  src/containers/TriggerTemplate/index.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XXL
