Repository tektoncd/dashboard, pull requests merged in 2019-10, with the labels that each got.

#587 Fix for character length of secret, validation of name in create secret
  src/components/SecretsModal/Annotations.js
  src/components/SecretsModal/BasicAuthFields.js
  src/components/SecretsModal/UniversalFields.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
Labels: approved, lgtm, size/L

#591 Pass fetchPipelineRuns Action to Extension
  src/actions/pipelineRuns.js
  src/containers/Extension/actions.js
Labels: approved, lgtm, size/XS

#595 Add missing tests and improve coverage
  packages/components/src/components/FormattedDate/FormattedDate.test.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/Rebuild/Rebuild.js
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
Labels: approved, lgtm, size/M

#583 Improve styling of RunHeader component
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Rebuild/Rebuild.scss
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.scss
Labels: approved, lgtm, size/M

#590 Update URL for PipelineRun page and ensure PipelineRuns active in left nav
  packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/Rebuild/Rebuild.js
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/containers/App/App.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/M

#573 Move up to Tekton 0.7 for pipeline0
  README.md
  config/openshift/openshift-tekton-dashboard.yaml
  config/pipeline0-task.yaml
  config/pipeline0.yaml
  config/release/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/M

#597 Re-publish Carbon 10 Tab and Tabs components
  packages/components/src/components/Tab/index.js
  packages/components/src/components/Tabs/Tabs.stories.js
  packages/components/src/components/Tabs/index.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/M

#592 handle cancelled steps
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Step/Step.test.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.js
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.scss
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.test.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#599 Update usage of fetch to send credentials
  src/api/comms.js
Labels: approved, lgtm, size/XS

#588 Resiliency: function even with missing status & TaskRun info for PipelineRun page
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/components/src/components/TaskTree/TaskTree.js
  packages/utils/src/utils/index.js
  pkg/endpoints/cluster.go
  pkg/endpoints/pipeline.go
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/PipelineRun/PipelineRun.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#601 Specific Error Messages when Creating Secrets
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/S

#602 Fix Scrolling Bug when Modal is Closed
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/M

#604 Fix for secrets timeout error when deleting multiple secrets
  src/actions/secrets.js
Labels: approved, lgtm, size/XS

#605 Add troubleshooting: mention common lack of GitHub secret
  README.md
Labels: approved, lgtm, size/XS

#600 Publish alpha19
  lerna.json
Labels: approved, lgtm, size/XS

#606 Fix lockdown.py curl URL in publish pipeline
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#608 Clear secrets modal form on close
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/S

#609 Add default value of 60 for pipelinerun timeout
  src/containers/CreatePipelineRun/CreatePipelineRun.js
Labels: approved, lgtm, size/XS

#610 Just use key for clearing new modal when creating secret
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/S

#617 Reference 0.2.0 release in docs to use
  README.md
Labels: approved, lgtm, size/XS

#620 Add Steve as an approver
  OWNERS
Labels: approved, lgtm, size/XS

#612 Namespace on the left overwriting namespace in the create secret modal
  src/components/SecretsModal/BasicAuthFields.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/M

#615 Fix storybook for connected dropdowns
  .storybook/config.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelinesDropdown/PipelinesDropdown.stories.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.stories.js
Labels: approved, lgtm, size/S

#619 Make link style in task tree more specific
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.scss
Labels: approved, lgtm, size/M

#614 Bug Fix: Unable to type inside the 10th+ Server URL Field
  src/components/SecretsModal/Annotations.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/S

#622 Fix hover and focus states for task tree links
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Task/Task.scss
Labels: approved, lgtm, size/S

#621 Publish @tektoncd/dashboard-components alpha 23
  lerna.json
Labels: approved, lgtm, size/XS

#623 Update Tasks / ClusterTasks views to be consistent with PipelineRuns
  package.json
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/actions/pipelineRuns.js
  src/actions/pipelineRuns.test.js
  src/actions/taskRuns.js
  src/actions/taskRuns.test.js
  src/api/index.js
  src/containers/App/App.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/TaskRunList/index.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/index.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/store/middleware.js
  src/utils/object-is.js
Labels: approved, lgtm, size/XL

#624 Move label filter to reusable component
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LabelFilter/LabelFilter.scss
  packages/components/src/components/LabelFilter/LabelFilter.stories.js
  packages/components/src/components/LabelFilter/LabelFilter.test.js
  packages/components/src/components/LabelFilter/index.js
  packages/components/src/components/index.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XL

#627 Add delete to pipelineRuns view
  src/api/index.js
  src/api/index.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#628 Add label filter to TaskRuns page
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/L

#631 Check Intl.RelativeTimeFormat support in FormattedTime
  packages/components/src/components/FormattedDate/FormattedDate.js
  packages/components/src/components/FormattedDate/FormattedDate.test.js
Labels: approved, lgtm, size/XS

#632 Publish @tektoncd/dashboard-components 0.0.1-alpha.24
  lerna.json
Labels: approved, lgtm, size/XS

#637 Tekton logo says meow on hover
  packages/components/src/components/Header/Header.js
Labels: approved, lgtm, size/XS

#634 Kube API for frontend secrets
  Gopkg.lock
  package-lock.json
  package.json
  pkg/endpoints/credential.go
  pkg/endpoints/credential_test.go
  pkg/router/router.go
  pkg/router/routes_test.go
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.js
  src/api/index.test.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/XXL

#633 Bump tektoncd/plumbing dependency ⛽️
  Gopkg.lock
Labels: approved, lgtm, size/XS

#640 Add openshift yaml to release pipeline
  tekton/README.md
  tekton/publish.yaml
  tekton/resources.yaml
Labels: approved, lgtm, size/M

#641 Base64 encode input data for secret creation
  DEVELOPMENT.md
  package-lock.json
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/M

#645 Debug Logs for Flaky Unit Test
  pkg/router/routes_test.go
Labels: approved, lgtm, size/M

#651 Fix rebuild of cancelled PipelineRuns
  pkg/endpoints/pipeline.go
Labels: approved, lgtm, size/XS

#656 Change PipelineRun tooltip from cancel to stop
  src/containers/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/XS

#636 make timestamp configurable
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
Labels: approved, lgtm, size/S

#657 Move default pollingInterval to defaultProps
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/XS

#658 Externalise PipelineRun list action text
  src/containers/PipelineRuns/PipelineRuns.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/S

#660 Ensure no underline displayed in TaskTree
  packages/components/src/components/Step/Step.scss
Labels: approved, lgtm, size/XS

#654 Add tekton.dev conditions to ClusterRole
  config/dev-tekton-dashboard.yaml
  config/openshift/openshift-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/S

#659 Validation on import resources
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L

#653 Fix error showing TaskRun steps that have not run
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/Task/Task.test.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L

#676 Increase log / details font size to improve legibility of ideographic languages
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/StepDefinition/StepDefinition.scss
  packages/components/src/components/StepStatus/StepStatus.scss
Labels: approved, lgtm, size/S

#677 Publish @tektoncd/dashboard-components@0.0.1-alpha.25
  lerna.json
Labels: approved, lgtm, size/XS

#674 Add notifications for successful creation and deletion of secrets
  src/actions/secrets.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/nls/messages_en.json
  src/reducers/index.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/L

#649 Skip Conditional Step when Loading PipelineRun page
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#683 Change yq install method
  test/e2e-common.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#678 Fix bug where multiple service accounts can't be unpatched at once
  jest.config.js
  package-lock.json
  src/actions/secrets.js
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/XL
