Repository tektoncd/dashboard, pull requests merged in 2019-05, with the labels that each got.

#96 Dedicated path for extensions
  DEVELOPMENT.md
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
Labels: approved, lgtm, size/M

#106 Update to Carbon 10
  package-lock.json
  package.json
  src/components/App/App.scss
  src/components/Definitions/Definitions.scss
  src/components/Header/Header.scss
  src/components/RunHeader/RunHeader.scss
  src/components/Step/Step.js
  src/components/Step/Step.scss
  src/components/StepDetails/StepDetails.scss
  src/components/StepDetailsHeader/StepDetailsHeader.js
  src/components/StepDetailsHeader/StepDetailsHeader.scss
  src/components/Task/Task.js
  src/components/Task/Task.scss
  src/utils/index.js
Labels: approved, lgtm, size/L

#107 Add service account name in credential request
  DEVELOPMENT.md
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
Labels: approved, lgtm, size/M

#94 Websocket race
  Dockerfile_test
  pkg/broadcaster/broadcaster.go
  pkg/broadcaster/broadcaster_test.go
  pkg/endpoints/routes_test.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  pkg/websocket/websocket.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#111 Request namespaces so they're available for display in the UI
  src/actions/namespaces.js
  src/actions/namespaces.test.js
  src/api/index.js
  src/api/index.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/namespaces.js
  src/reducers/namespaces.test.js
Labels: approved, lgtm, size/L

#119 Add ponyfill for dynamic module import (used for extensions)
  src/containers/App/App.js
  src/containers/Extension/Extension.js
Labels: approved, lgtm, size/M

#120 Improve front-end production build
  .babelrc
  package-lock.json
  package.json
  src/utils/polyfills.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: approved, lgtm, size/L

#115 Add web project tests
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#127 Remove header on Home navigation list
  src/containers/Home/Home.js
Labels: approved, lgtm, size/XS

#122 Task runs and pipeline runs by name not working as expected
  DEVELOPMENT.md
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
Labels: approved, lgtm, size/M

#125 Tie run containers into redux store
  src/actions/pipelineRuns.js
  src/actions/task.js
  src/actions/task.test.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/pipelineRuns.js
  src/reducers/pipelines.js
  src/reducers/taskRuns.js
  src/reducers/tasks.js
  src/utils/index.js
Labels: approved, lgtm, size/XL

#131 Split credentials into three types
  DEVELOPMENT.md
  Gopkg.lock
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/routes_test.go
Labels: approved, lgtm, size/L

#135 Fix badly named variable in namespaces actions test
  src/actions/namespaces.test.js
Labels: approved, lgtm, size/XS

#132 Use name query parameters for pipeline and task run calls
  src/actions/pipelineRuns.js
  src/actions/taskRuns.js
  src/api/index.js
  src/api/index.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/M

#136 Add UI shell for navigation and namespace selection
  src/components/App/App.scss
  src/components/Breadcrumbs/Breadcrumbs.js
  src/components/Breadcrumbs/Breadcrumbs.stories.js
  src/components/Breadcrumbs/Breadcrumbs.test.js
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/RunHeader/RunHeader.scss
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/Extensions/Extensions.js
  src/containers/Home/Home.js
  src/containers/Home/index.js
  src/containers/Pipelines/Pipelines.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/index.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/L

#138 Expose redux store and selectors for use by extensions
  src/containers/Extension/Extension.js
  src/containers/Extension/globals.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/L

#140 Update PipelineRun and PipelineRuns when namespace changes
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/M

#145 Update to Carbon 10.2
  package-lock.json
  package.json
  src/containers/App/App.js
Labels: approved, lgtm, size/M

#143 Add PipelineRuns to top-level nav
  src/containers/App/App.js
  src/containers/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/M

#147 Use tektoncd/plumbing script for the CI
  Gopkg.lock
  Gopkg.toml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#150 Resolve npm audit warnings
  package-lock.json
Labels: approved, lgtm, size/S

#148 Move extensions navigation
  config/tekton-dashboard-deployment.yaml
  src/components/App/App.scss
  src/components/SideNavMenu/SideNavMenu.js
  src/components/SideNavMenu/SideNavMenu.scss
  src/components/SideNavMenu/SideNavMenu.test.js
  src/components/SideNavMenu/index.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
Labels: approved, lgtm, size/L

#151 Undo unintended removal of pipelineRuns selection
  src/containers/App/App.js
Labels: approved, lgtm, size/XS

#154 Fix task runs filtering for tasks without a taskRef
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
Labels: approved, lgtm, size/XS

#159 Ensure node.js unit tests can fail the PR build
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#157 Minor style updates
  src/components/Header/Header.scss
  src/components/SideNavMenu/SideNavMenu.scss
  src/containers/NamespacesDropdown/NamespacesDropdown.js
Labels: approved, lgtm, size/S

#153 Handle 201 Created response code
  src/api/comms.js
  src/api/comms.test.js
Labels: approved, lgtm, size/S

#162 Make sure the integration test image has the web part
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#163 Expose subset of action creators to extensions
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/containers/Extension/Extension.js
  src/containers/Extension/actions.js
  src/containers/Pipelines/Pipelines.js
  src/reducers/pipelines.js
  src/reducers/pipelines.test.js
Labels: approved, lgtm, size/L

#164 Update action creators to allow specifying a namespace
  src/actions/pipelineRuns.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/actions/taskRuns.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/M

#173 Handle inline task runs in the client
  src/api/comms.test.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/S

#155 Adjust API to use plural nouns
  DEVELOPMENT.md
  docs/samples/extension/README.md
  pkg/endpoints/cluster.go
  pkg/endpoints/health_test.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
  pkg/endpoints/websocket_test.go
  src/api/index.js
  src/api/index.test.js
  webpack.dev.js
Labels: approved, lgtm, size/L

#176 Fix to PR 155 - HandleExtension was missing slash in proxy reroute
  pkg/endpoints/router.go
Labels: approved, lgtm, size/S

#181 Issue 179 Specify 204 on credentialDelete, Add test to ensure all del…
  pkg/endpoints/credentials.go
  pkg/endpoints/routes_test.go
Labels: approved, lgtm, size/S

#180 Issue 129 Pipeline_test.go refactor and related improvements
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/test-utils.go
Labels: approved, lgtm, size/XXL

#123 Add service, remove port-forward
  DEVELOPMENT.md
  README.md
  config/tekton-dashboard.yaml
Labels: approved, lgtm, size/M

#189 install dashboard on minishift/openshift
  README.md
  config/templates/build.yml
  config/templates/deploy.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#165 initial postsubmit script to publish dashboard image
  test/publish-images.sh
Labels: approved, lgtm, size/M

#197 Add 'npm run lint' to PR build
  .gitignore
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#183 Prune credentials to userpass only
  DEVELOPMENT.md
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/routes_test.go
Labels: approved, lgtm, size/L
