Repository tektoncd/dashboard, pull requests merged in 2019-04, with the labels that each got.

#1 Initial README updates
  README.md
  docs/dashboard-ui.png
Labels: needs-ok-to-test, size/M

#6 Update dashboard to handle relative paths
  src/api/index.js
  src/containers/App/App.js
  webpack.prod.js
Labels: lgtm, needs-ok-to-test, size/XS

#8 Update package-lock.json
  package-lock.json
Labels: size/XXL

#9 initial commit for back-end
  .gitignore
  Gopkg.lock
  Gopkg.toml
  cmd/dashboard/main.go
  pkg/broadcaster/broadcaster.go
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/health.go
  pkg/endpoints/health_test.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/test-utils.go
  pkg/endpoints/utils.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  pkg/logging/logging.go
  pkg/utils/utils.go
  pkg/websocket/websocket.go
Labels: size/XXL

#11 Backend build changes and install yaml
  Dockerfile
  README.md
  cmd/dashboard/main.go
  install/tekton-dashboard-deployment.yaml
  pkg/endpoints/utils.go
Labels: needs-ok-to-test, size/L

#29 Add OWNERS file with a list of approvers
  OWNERS
Labels: size/S

#21 Add Dockerfile_test
  Dockerfile_test
Labels: approved, size/S

#26 Add deployment label
  install/tekton-dashboard-deployment.yaml
Labels: approved, needs-ok-to-test, size/XS

#19 Address go-lint problems, readiness/health probe log message
  Dockerfile
  Gopkg.lock
  cmd/dashboard/main.go
  pkg/broadcaster/broadcaster.go
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/health.go
  pkg/endpoints/health_test.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/test-utils.go
  pkg/endpoints/utils.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  pkg/logging/logging.go
  pkg/utils/utils.go
  pkg/websocket/websocket.go
Labels: approved, needs-ok-to-test, size/L

#32 Update front end to handle change in taskrunlog response format
  src/components/Log/Log.js
  src/components/Log/Log.stories.js
  src/components/Log/Log.test.js
  src/components/StepDetails/StepDetails.js
  src/containers/Log/Log.js
  src/containers/Log/Log.test.js
Labels: approved, needs-ok-to-test, size/L

#31 Fix context root code to handle dev mode
  src/api/index.js
  src/api/index.test.js
Labels: approved, needs-ok-to-test, size/S

#39 Add mutext around counter updates in websocket test
  pkg/endpoints/websocket_test.go
Labels: approved, needs-ok-to-test, size/S

#27 Add DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
Labels: approved, size/L

#36 correct image name
  install/tekton-dashboard-deployment.yaml
Labels: needs-ok-to-test, size/XS

#20 Global types
  Gopkg.lock
  pkg/endpoints/router.go
  pkg/endpoints/types.go
Labels: approved, needs-ok-to-test, size/S

#43 Document our backend API definitions
  DEVELOPMENT.md
Labels: approved, size/L

#54 Add frontend instructions to DEVELOPMENT docs
  DEVELOPMENT.md
  config/config.json
Labels: approved, needs-ok-to-test, size/M

#48 Restful routes
  DEVELOPMENT.md
  Gopkg.lock
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
Labels: approved, needs-ok-to-test, size/XL

#55 Advocate using ko in developer docs
  .eslintrc.js
  DEVELOPMENT.md
  Gopkg.lock
  README.md
  config/tekton-dashboard-deployment.yaml
  config_frontend/__mocks__/fileMock.js
  config_frontend/__mocks__/styleMock.js
  config_frontend/config.json
  config_frontend/setupTests.js
  jest.config.js
  webpack.dev.js
Labels: approved, size/L

#61 Fix router test to check PUT endpoints
  pkg/endpoints/credentials.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
Labels: approved, size/L

#63 Connect Pipelines container to redux store
  src/actions/pipeline.js
  src/actions/pipeline.test.js
  src/containers/Pipelines/Pipelines.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/pipeline.js
  src/reducers/pipelines.js
  src/reducers/pipelines.test.js
  src/store/index.js
  src/store/index.test.js
Labels: approved, size/L

#64 Connect Tasks container to redux store
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/tasks.js
  src/reducers/tasks.test.js
Labels: approved, size/L

#66 Add pipelinerunlog API doc
  DEVELOPMENT.md
Labels: approved, size/S

#57 Add query parameters to filter pipelineruns/taskruns by name
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/test-utils.go
Labels: approved, needs-ok-to-test, size/L

#33 Add create PipelineRun API
  cmd/dashboard/main.go
  config/tekton-dashboard-deployment.yaml
  pkg/endpoints/credentials.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
  pkg/utils/utils.go
Labels: approved, needs-ok-to-test, size/XL

#69 Docs for PipelineRun POST API
  DEVELOPMENT.md
Labels: approved, needs-ok-to-test, size/M

#68 Install instructions using ko
  README.md
Labels: approved, lgtm, size/S

#72 Initial pre-summit script…
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#34 Extension support
  DEVELOPMENT.md
  cmd/dashboard/main.go
  config/tekton-dashboard-deployment.yaml
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
Labels: approved, lgtm, size/L

#77 Use INSTALLED_NAMESPACE var to match Go code expectations
  config/tekton-dashboard-deployment.yaml
Labels: approved, lgtm, size/XS

#85 update package lock
  package-lock.json
Labels: approved, lgtm, size/XS

#78 Support web project from back and and builders
  .dockerignore
  .gitignore
  DEVELOPMENT.md
  Dockerfile
  Dockerfile_test
  README.md
  cmd/dashboard/main.go
  config/tekton-dashboard-deployment.yaml
  package.json
  pkg/endpoints/router.go
  pkg/endpoints/routes_test.go
  src/api/index.js
  testdata/web/index.html
  webpack.dev.js
Labels: approved, lgtm, needs-ok-to-test, size/M

#89 Update OWNERS -- adding carlos
  OWNERS
Labels: approved, lgtm, size/XS

#87 Split dev dependencies in package.json
  package-lock.json
  package.json
  src/utils/test.js
Labels: approved, lgtm, size/XXL

#93 Remove extra forward slash in API URLs
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/XS

#92 Add favicon
  src/images/favicon.png
  webpack.common.js
Labels: approved, lgtm, size/XS

#95 Use newly added name field in step status to find correct results
  Gopkg.lock
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/S

#99 Modify the readme for dockerbuild installation method.
  README.md
Labels: approved, lgtm, size/XS

#97 patch service account in credential api
  config/tekton-dashboard-deployment.yaml
  pkg/endpoints/credentials.go
  pkg/endpoints/credentials_test.go
Labels: approved, lgtm, size/L

#65 Extension sample
  docs/samples/extension/Dockerfile
  docs/samples/extension/README.md
  docs/samples/extension/config/tekton-extension-sample-service.yaml
  docs/samples/extension/config/tekton-extension-sample.yaml
  docs/samples/extension/package.json
  docs/samples/extension/server.js
Labels: approved, lgtm, needs-ok-to-test, size/L

#104 Update tasks reducer to store by namespace
  src/reducers/tasks.js
  src/reducers/tasks.test.js
Labels: approved, lgtm, size/M

#105 Fix lint issues
  docs/samples/extension/server.js
  jest.config.js
Labels: approved, lgtm, size/S

#103 Add a few docs that were missing 📝
  .github/issue-template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  code-of-conduct.md
Labels: approved, lgtm, size/L
