Repository tektoncd/dashboard, pull requests merged in 2019-09, with the labels that each got.

#467 Ensure always unique extension IDs are used in test
  pkg/router/routes_test.go
Labels: approved, lgtm, size/S

#466 Reconnect WebSocket on error
  package-lock.json
  package.json
  src/index.js
Labels: approved, lgtm, size/M

#463 Improve resilience of UI to namespace / resource deletion
  packages/components/src/components/Log/Log.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/reducers/reducerCreators.js
  src/reducers/reducerCreators.test.js
Labels: approved, lgtm, size/L

#465 Add script to extract messages for translation
  .storybook/Container.js
  DEVELOPMENT.md
  config_frontend/config.json
  package-lock.json
  package.json
  packages/components/src/components/Log/Log.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.js
  scripts/i18n/extractMessages.js
  src/constants/index.js
  src/containers/App/App.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/nls/messages_en.json
  src/utils/test.js
Labels: approved, lgtm, size/L

#392 Implement consistency across UI tables #379
  src/components/Definitions/Definitions.scss
  src/components/SecretsModal/SecretsModal.scss
  src/components/SecretsTable/Secrets.scss
  src/components/SecretsTable/SecretsTable.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.scss
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/M

#478 Fix duplicate target-namespace param for pipeline0
  pkg/endpoints/pipeline.go
Labels: approved, lgtm, size/XS

#482 Additional http service for use inside the openshift cluster
  config/openshift/openshift-tekton-dashboard.yaml
Labels: approved, lgtm, size/S

#481 Allow 0 in secret names, fix error msg to mention 253 char limit
  src/components/SecretsModal/UniversalFields.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/XS

#485 fix keys on logs components
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/XS

#486 only show cancel pipelineRun Where available
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/M

#483 Update extension docs to use v1 endpoint, Node.js 10 image, readme++
  docs/samples/extension/Dockerfile
  docs/samples/extension/README.md
  docs/samples/extension/config/tekton-extension-sample-service.yaml
  docs/samples/extension/config/tekton-extension-sample.yaml
  docs/samples/extension/package.json
  docs/samples/extension/server.js
  package-lock.json
Labels: approved, lgtm, size/L

#484 Externalize missed strings and cancel button component
  packages/components/src/components/CancelButton/CancelButton.js
  packages/components/src/components/CancelButton/CancelButton.test.js
  packages/components/src/components/ErrorBoundary/ErrorBoundary.js
  packages/components/src/components/ErrorBoundary/ErrorBoundary.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#489 Expand first step of first task by default
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/TaskTree/TaskTree.js
  packages/components/src/components/TaskTree/TaskTree.test.js
Labels: approved, lgtm, size/S

#504 Publish v0.0.1-alpha.9 of the sub-packages
  lerna.json
  package-lock.json
Labels: approved, lgtm, size/M

#508 Fix key prop on Log component
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/S

#507 Fix style of running icon on TaskRuns
  src/components/Definitions/Definitions.scss
Labels: approved, lgtm, size/XS

#495 Show ServiceAccount for install namespace only when importing resources
  src/api/index.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L

#500 Ignore stale resources from REST response and websocket payloads
  packages/components/src/components/LogoutButton/LogoutButton.js
  src/api/index.js
  src/reducers/clusterTasks.js
  src/reducers/clusterTasks.test.js
  src/reducers/reducerCreators.js
  src/reducers/reducerCreators.test.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#494 reuse pipelineRunComponent in pipelineRunContainer
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/L

#512 Only display tekton.dev annotations on secrets table
  src/components/SecretsTable/SecretsTable.js
  src/components/SecretsTable/SecretsTable.test.js
Labels: approved, lgtm, size/M

#502 Containers should re-fetch their data on a websocket reconnect
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/Pipelines/Pipelines.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SecretsModal/SecretsModalAnnotationText.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRunList/TaskRunList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/Tasks/Tasks.js
  src/reducers/index.js
  src/reducers/notifications.js
  src/reducers/notifications.test.js
  src/store/middleware.js
Labels: approved, lgtm, size/XL

#516 Publish @tektoncd/dashboard-components v0.0.1-alpha.10
  lerna.json
Labels: approved, lgtm, size/XS

#521 Update to latest Carbon package versions
  package-lock.json
  package.json
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/M

#531 Fix blue displaying for secrets display table in Safari
  src/components/SecretsTable/Secrets.scss
Labels: approved, lgtm, size/S

#490 createPipelineRun consume KubeAPI - frontend
  src/api/index.js
  src/api/index.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/utils/index.js
Labels: approved, lgtm, size/L

#421 createPipelineRun consume KubeAPI - backend
  pkg/endpoints/cluster.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/router/router.go
  pkg/router/routes_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  test/resources/envsubst/pipelineresource-git.yaml
  test/resources/envsubst/pipelineresource-image.yaml
  test/resources/envsubst/pipelinerun.yaml
  test/resources/static/Pipeline.yaml
  test/resources/static/deploy-task-insecure.yaml
  test/resources/static/kaniko-build-task.yaml
Labels: approved, lgtm, size/XXL

#532 Add pending state and function to generate pipeline run name
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#534 Update dynamic import fallback to support sending credentials
  src/containers/Extension/Extension.js
Labels: approved, lgtm, size/XS

#533 Skip auth (still must log in) for extension loading on Safari
  config/openshift/openshift-tekton-dashboard.yaml
Labels: approved, lgtm, size/XS

#535 add carbon icons to utils package
  lerna.json
  package-lock.json
  packages/utils/package.json
Labels: approved, lgtm, size/M

#510 handle secret websocket events
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/L

#536 add annotations to log fetching
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#540 Issue #537: Make pipeline0 pass correct parameters to API call
  package-lock.json
  package.json
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L

#547 Trims spaces at the start and end of a secret name instead of erroring
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/XS

#563 Fix regression in PipelineRun resiliency
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/M

#564 Issue 552: Disable dropdowns if namespace is null
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/M

#575 Handle PipelineRuns with no status in PipelineRuns table
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/XS

#574 Issue 555: Clarify the format of the timeout duration on PipelineRun creation UI
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/S

#578 Issue 554: Create PipelineRun UI timeout validation/restriction
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/M

#579 make pending not cancelable
  lerna.json
  packages/utils/src/utils/index.js
Labels: approved, lgtm, size/XS

#545 Update storybook to 5.2
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#576 Cleanup storybook config
  .storybook/config.js
Labels: approved, lgtm, size/XS

#565 Replace JS substr with substring
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/XS

#582 update lerna package version
  lerna.json
Labels: approved, lgtm, size/XS

#589 Hide params and resource on step details tab for 3rd parties
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/StepDetails/StepDetails.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/L
