Repository tektoncd/dashboard, pull requests merged in 2020-08, with the labels that each got.

#1652 Update DEVELOPMENT.md to point to docs folder
  DEVELOPMENT.md
Labels: approved, lgtm, size/L

#1656 Update link to Dashboard Katacoda tutorial
  README.md
Labels: approved, lgtm, size/XS

#1653 Add link to ResourceDetails page from ClusterTasks list
  src/containers/ClusterTasks/ClusterTasks.js
Labels: approved, lgtm, size/S

#1654 Update container stories to use Component Story Format
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.stories.js
  src/containers/EventListener/EventListener.stories.js
  src/containers/LogDownloadButton/LogDownloadButton.stories.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelinesDropdown/PipelinesDropdown.stories.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.stories.js
  src/containers/TasksDropdown/TasksDropdown.stories.js
Labels: approved, lgtm, size/XL

#1655 Update component stories to use Component Story Format
  .storybook/main.js
  package-lock.json
  package.json
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.stories.js
  packages/components/src/components/DetailsHeader/DetailsHeader.stories.js
  packages/components/src/components/FormattedDate/FormattedDate.stories.js
  packages/components/src/components/FormattedDuration/FormattedDuration.stories.js
  packages/components/src/components/Header/Header.stories.js
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/LabelFilter/LabelFilter.stories.js
  packages/components/src/components/LoadingShell/LoadingShell.stories.js
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  packages/components/src/components/ResourceTable/ResourceTable.stories.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/Step/Step.stories.js
  packages/components/src/components/StepDefinition/StepDefinition.stories.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/StepStatus/StepStatus.stories.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Tabs/Tabs.stories.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/components/src/components/TextInput/TextInput.stories.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.stories.js
  packages/components/src/components/Trigger/Trigger.stories.js
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
Labels: approved, lgtm, size/XXL

#1639 Adopt Carbon gray10 theme
  packages/components/src/components/KeyValueList/KeyValueList.scss
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.scss
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/StepStatus/StepStatus.test.js
  packages/components/src/components/Task/Task.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.scss
  packages/components/src/components/TaskTree/TaskTree.scss
  packages/components/src/components/ViewYAML/ViewYAML.js
  packages/components/src/components/ViewYAML/ViewYAML.scss
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
  packages/components/src/scss/Run.scss
  packages/components/src/scss/_vars.scss
  src/components/App/App.scss
  src/components/App/_carbon.scss
  src/components/CreateSecret/Form/UniversalFields.js
  src/containers/CreateSecret/CreateSecret.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/SideNav/SideNav.scss
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XL

#1651 Add missing Triggers websocket events on backend
  cmd/dashboard/main.go
  go.mod
  go.sum
  pkg/broadcaster/broadcaster.go
  pkg/controllers/controller.go
  pkg/controllers/triggers/clusterTriggerBinding.go
  pkg/controllers/triggers/eventListener.go
  pkg/controllers/triggers/triggerBinding.go
  pkg/controllers/triggers/triggerTemplate.go
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  pkg/endpoints/types.go
Labels: approved, lgtm, size/L

#1658 Don't copy ignored files when bootstrapping packages
  packages/components/package.json
  packages/utils/package.json
Labels: approved, lgtm, size/XS

#1649 Update backend to use v1beta1 Pipelines client
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/endpoints/pipeline.go
  pkg/endpoints/websocket_test.go
  pkg/router/routes_test.go
Labels: approved, lgtm, size/M

#1660 Fix dropdown styles on Create screens after latest theme and Carbon updates
  src/components/CreatePipelineResource/UniversalFields.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/scss/Create.scss
Labels: approved, lgtm, size/S

#1659 Fix SideNav submenu font colour
  src/containers/SideNav/SideNav.scss
Labels: approved, lgtm, size/XS

#1586 Add external logs provider support
  cmd/dashboard/main.go
  docs/dev/installer.md
  docs/walkthrough/README.md
  docs/walkthrough/walkthrough-logs-collected.png
  docs/walkthrough/walkthrough-logs-logs.png
  docs/walkthrough/walkthrough-logs-minio.png
  docs/walkthrough/walkthrough-logs-nologs.png
  docs/walkthrough/walkthrough-logs.md
  overlays/patches/installer/deployment-patch.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/externallogs.go
  pkg/endpoints/types.go
  pkg/router/router.go
  pkg/utils/proxy.go
  scripts/installer
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/reducers/index.js
  src/reducers/properties.js
  src/utils/index.js
Labels: approved, lgtm, size/XL

#1662 Remove unused scrollIntoView test stub
  config_frontend/setupTests.js
Labels: approved, lgtm, size/XS

#1661 Ensure links in log output use the Carbon link colour by default
  packages/components/src/components/Log/Log.scss
Labels: approved, lgtm, size/XS

#1663 Remove unnecessary use of cleanup in unit tests
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
Labels: approved, lgtm, size/S

#1664 Update tests to ensure beforeEach doesn't leak globally
  src/containers/App/App.test.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TasksDropdown/TasksDropdown.test.js
Labels: approved, lgtm, size/XXL

#1657 feat: Create an ansi text parser w/ links support
  package-lock.json
  packages/components/package.json
  packages/components/src/components/LogFormat/LogFormat.js
  packages/components/src/components/LogFormat/LogFormat.stories.js
  packages/components/src/components/LogFormat/LogFormat.test.js
  packages/components/src/components/LogFormat/defaults.js
  packages/components/src/components/LogFormat/index.js
Labels: approved, lgtm, ok-to-test, size/XL

#1665 Update LogFormat conceal styles so text can still be selected / copied
  packages/components/src/components/LogFormat/LogFormat.test.js
  packages/components/src/components/LogFormat/defaults.js
Labels: approved, lgtm, size/XS

#1667 Add logout URL support to the installer script
  docs/dev/installer.md
  scripts/installer
Labels: approved, lgtm, size/XS

#1666 Use release-installer in kind walkthrough
  docs/walkthrough/walkthrough-kind.md
Labels: approved, lgtm, size/S

#1668 Configure logout URL in oauth walkthrough
  docs/walkthrough/walkthrough-oauth2-proxy.md
Labels: approved, lgtm, size/S

#1669 Add support for version latest to the installer script
  scripts/installer
  scripts/release-installer
Labels: approved, lgtm, size/M

#1671 Add note to configure external logs with installer script in walkthrough
  docs/walkthrough/walkthrough-logs.md
Labels: approved, lgtm, size/S

#1672 Fix oauth2 proxy walkthrough
  docs/walkthrough/walkthrough-oauth2-proxy.md
Labels: approved, lgtm, size/XS

#1675 Fix alignment of TaskRun / step header
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
Labels: approved, lgtm, size/XS

#1673 Use version latest in installer docs
  docs/install.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
Labels: approved, lgtm, size/S

#1676 Add build command support to release-installer script
  scripts/installer
  scripts/release-installer
Labels: approved, lgtm, size/S

#1678 Improve docs readability of bash commands
  docs/extensions.md
  docs/install.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/M

#1680 bug: Empty Lines should be separated
  packages/components/src/components/LogFormat/LogFormat.js
  packages/components/src/components/LogFormat/LogFormat.test.js
Labels: approved, lgtm, ok-to-test, size/S

#1682 Wrap LogFormat output in a `code` element
  packages/components/src/components/LogFormat/LogFormat.js
  packages/components/src/components/LogFormat/LogFormat.test.js
Labels: approved, lgtm, size/XS

#1681 Update ANSI colour palette for the new LogFormat component
  packages/components/src/components/LogFormat/LogFormat.stories.js
  packages/components/src/components/LogFormat/LogFormat.test.js
  packages/components/src/components/LogFormat/defaults.js
Labels: approved, lgtm, size/L

#1684 Update triggers and pipeline versions used in e2e tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1685 Use CSS for LogFormat styles where possible
  packages/components/src/components/LogFormat/LogFormat.js
  packages/components/src/components/LogFormat/LogFormat.scss
  packages/components/src/components/LogFormat/LogFormat.stories.js
  packages/components/src/components/LogFormat/LogFormat.test.js
  packages/components/src/components/LogFormat/defaults.js
Labels: approved, lgtm, size/L

#1677 Add a walkthrough to setup everything with kind and istio
  docs/walkthrough/README.md
  docs/walkthrough/walkthrough-istio-kiali.png
  docs/walkthrough/walkthrough-istio.md
Labels: approved, lgtm, size/L

#1687 Remove obsolete instructions from dev docs
  docs/dev/README.md
  docs/dev/installer.md
Labels: approved, lgtm, size/M

#1689 Enable the new LogFormat component
  package-lock.json
  packages/components/package.json
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/S

#1694 Update release pipeline to make publishing as latest optional
  tekton/README.md
  tekton/publish.yaml
  tekton/release-pipeline.yml
  tekton/scripts/lockdown.py
Labels: approved, lgtm, size/L

#1695 Publish @tektoncd/dashboard-components 0.0.1-alpha.55
  lerna.json
Labels: approved, lgtm, size/XS

#1696 Update dot-prop to resolve npm audit warnings
  package-lock.json
Labels: approved, lgtm, size/M

#1699 Add story showing URL detection by the LogFormat component
  packages/components/src/components/LogFormat/LogFormat.stories.js
Labels: approved, lgtm, size/S

#1701 Update to Storybook 6
  .storybook/Container.js
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  packages/components/src/components/FormattedDuration/FormattedDuration.stories.js
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/LogFormat/LogFormat.stories.js
  packages/components/src/components/Table/Table.stories.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.stories.js
  src/containers/EventListener/EventListener.stories.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelinesDropdown/PipelinesDropdown.stories.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.stories.js
  src/containers/TasksDropdown/TasksDropdown.stories.js
Labels: approved, lgtm, size/XXL

#1705 Improve installer help
  docs/dev/installer.md
  scripts/installer
Labels: approved, lgtm, size/S

#1703 Fix release installer build command
  scripts/release-installer
Labels: approved, lgtm, size/XS

#1704 Add support for nightly releases in release installer script
  docs/dev/installer.md
  scripts/installer
  scripts/release-installer
Labels: approved, lgtm, size/S

#1679 Don't patch service on openshift but create a secure one for the Route
  overlays/installer/openshift/base/kustomization.yaml
  overlays/patches/openshift/service-patch.yaml
  overlays/resources/openshift/route-service.yaml
  overlays/resources/openshift/route.yaml
Labels: approved, lgtm, size/M

#1700 Fix connection closed when streaming logs
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/XS

#1706 Fix rerun pipeline run
  go.mod
  go.sum
  pkg/endpoints/pipeline.go
Labels: approved, lgtm, size/XL
