Repository tektoncd/dashboard, pull requests merged in 2020-07, with the labels that each got.

#1581 Fix flaky nightly releases
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#1585 Update README to include v0.7.1 release
  README.md
Labels: approved, lgtm, size/XS

#1573 Improve URL addressability of TaskRun and PipelineRun details pages
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/StepDetails/StepDetails.test.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/TaskTree/TaskTree.js
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/utils/src/utils/index.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/XL

#1582 Update release docs
  tekton/README.md
Labels: approved, lgtm, size/M

#1576 Use a real proxy instead of relying on k8s client
  cmd/dashboard/main.go
  go.mod
  go.sum
  pkg/endpoints/cluster.go
  pkg/endpoints/types.go
  pkg/utils/flushwriter.go
Labels: approved, lgtm, size/L

#1593 Add const dashboardAPIGroup
  src/api/index.js
Labels: approved, lgtm, size/XS

#1587 Remove unused log-related code from backend
  pkg/endpoints/websocket.go
Labels: approved, lgtm, size/XS

#1588 Make overview and YAML tabs URL addressable
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  packages/components/src/components/ResourceDetails/ResourceDetails.test.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/Condition/Condition.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/EventListener/EventListener.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1589 Fix styles on Create PipelineResource modal
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreatePipelineResource/index.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/PipelineResources/PipelineResources.js
  src/scss/Create.scss
Labels: approved, lgtm, size/M

#1584 Update to Carbon 10.15
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/components/LoadingShell/LoadingShell.scss
  packages/components/src/components/Tabs/Tabs.stories.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.test.js
  src/containers/App/App.test.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/SideNav/SideNav.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TasksDropdown/TasksDropdown.js
  src/containers/TasksDropdown/TasksDropdown.test.js
Labels: approved, lgtm, size/L

#1594 Add log related flags to the installer
  docs/dev/installer.md
  scripts/installer
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/S

#1595 Remove unused `taskRunNames` in PipelineRun component
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#1596 Update installer script prereq checks
  scripts/installer
Labels: approved, lgtm, size/S

#1591 Move Create PipelineResource to a URL addressable page
  src/components/CreatePipelineResource/GitResourceFields.js
  src/components/CreatePipelineResource/UniversalFields.js
  src/components/CreateSecret/CreateSecret.scss
  src/containers/App/App.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/Secrets/Secrets.js
  src/containers/index.js
  src/nls/messages_en.json
  src/scss/Create.scss
Labels: approved, lgtm, size/XL

#1590 Add --openshift flag
  cmd/dashboard/main.go
  overlays/patches/installer/deployment-patch.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  pkg/endpoints/types.go
  scripts/installer
Labels: approved, lgtm, size/L

#1597 Remove web-dir arg
  base/300-deployment.yaml
  cmd/dashboard/main.go
  docs/dev/README.md
  pkg/endpoints/types.go
  pkg/router/router.go
Labels: approved, lgtm, size/S

#1606 Speed up npm install by skipping lerna ci cleanup step
  package.json
Labels: approved, lgtm, size/XS

#1604 Add release-installer script to ease install of dashboard release
  docs/install.md
  scripts/release-installer
Labels: approved, lgtm, size/M

#1609 Update lodash to address npm audit issues
  package-lock.json
Labels: approved, lgtm, size/XS

#1610 Publish @tektoncd/dashboard-components 0.0.1-alpha.50
  lerna.json
Labels: approved, lgtm, size/XS

#1611 Fix secret not set on github and gitlab interceptors
  packages/components/src/components/Trigger/Trigger.js
Labels: approved, lgtm, size/M

#1614 Remove unused TaskSkeleton component
  packages/components/src/components/TaskSkeleton/TaskSkeleton.js
  packages/components/src/components/TaskSkeleton/TaskSkeleton.scss
  packages/components/src/components/TaskSkeleton/TaskSkeleton.stories.js
  packages/components/src/components/TaskSkeleton/TaskSkeleton.test.js
  packages/components/src/components/TaskSkeleton/index.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/L

#1616 Fix modal + notifications for Import Resources and Create PipelineRun/TaskRun
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.js
  src/api/index.test.js
  src/containers/ImportResources/ImportResources.js
Labels: approved, lgtm, size/M

#1615 Stop loading the entirety of the Carbon styles
  src/components/App/App.scss
  src/components/App/_carbon.scss
  src/containers/SideNav/SideNav.scss
Labels: approved, lgtm, size/M

#1578 Support both polling and streaming logs
  cmd/dashboard/main.go
  config_frontend/setupTests.js
  docs/dev/installer.md
  overlays/patches/installer/deployment-patch.yaml
  package-lock.json
  package.json
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.test.js
  pkg/endpoints/cluster.go
  pkg/endpoints/types.go
  scripts/installer
  src/api/comms.js
  src/api/index.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/properties.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1617 Add update command to prepare-kind-cluster script
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/XS

#1613 Reduce size of static resource bundles
  packages/components/package.json
  packages/utils/package.json
Labels: approved, lgtm, size/XS

#1618 Upgrade of reviewers to approvers, remove inactives from reviewer list
  OWNERS
Labels: approved, lgtm, size/S

#1620 Fix missing icons for PipelineRunStopping and PipelineRunCouldntCancel reasons
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, size/S

#1621 Add stream-logs and ingress-url options by default to prepare-kind-cluster
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/XS

#1623 Pin newmann version as new version breaks the build
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1605 Make uninstall not requiring install options
  docs/dev/installer.md
  scripts/installer
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/S

#1622 Remove unused code from pipeline endpoint
  pkg/endpoints/pipeline.go
Labels: approved, lgtm, size/M

#1624 Add npm script to rebuild lerna packages when changes are detected
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#1626 Remove `step=__` from URL for PipelineRun and TaskRun details pages
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/TaskTree/TaskTree.js
  packages/utils/src/utils/index.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/M

#1625 Document an oauth-proxy issue workaround
  docs/install.md
  docs/oauth-certificate-workaround.md
Labels: approved, lgtm, ok-to-test, size/M

#1627 Temporarily restore structured list styles
  src/components/App/_carbon.scss
Labels: approved, lgtm, size/XS

#1628 Publish @tektoncd/dashboard-components 0.0.1-alpha.51
  lerna.json
Labels: approved, lgtm, size/XS

#1629 Fix alignment of notification text
  src/components/Definitions/Definitions.scss
Labels: approved, lgtm, size/XS

#1630 Split APIs by kind
  src/actions/secrets.test.js
  src/api/clusterTasks.js
  src/api/clusterTasks.test.js
  src/api/clusterTriggerBindings.js
  src/api/clusterTriggerBindings.test.js
  src/api/comms.js
  src/api/comms.test.js
  src/api/conditions.js
  src/api/conditions.test.js
  src/api/eventListeners.js
  src/api/eventListeners.test.js
  src/api/extensions.js
  src/api/extensions.test.js
  src/api/index.js
  src/api/index.test.js
  src/api/pipelineResources.js
  src/api/pipelineResources.test.js
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/api/pipelines.js
  src/api/pipelines.test.js
  src/api/secrets.js
  src/api/secrets.test.js
  src/api/serviceAccounts.js
  src/api/serviceAccounts.test.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
  src/api/tasks.js
  src/api/tasks.test.js
  src/api/triggerBindings.js
  src/api/triggerBindings.test.js
  src/api/triggerTemplates.js
  src/api/triggerTemplates.test.js
  src/api/utils.js
  src/api/utils.test.js
  src/containers/App/App.test.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/Conditions/Conditions.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateSecret/CreateSecret.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TasksDropdown/TasksDropdown.test.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
Labels: approved, lgtm, size/XXL

#1632 Rename 'credentials' to 'secrets' for consistency
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/api/secrets.js
  src/api/secrets.test.js
  src/containers/Secrets/Secrets.test.js
Labels: approved, lgtm, size/M

#1631 Use pipelineTask name for PipelineRun URL addressability
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/L

#1634 Update readme to point to 0.8 release and docs
  README.md
Labels: approved, lgtm, size/XS

#1633 Reduce the amount of content included in the published npm packages
  packages/components/.npmignore
  packages/utils/.npmignore
Labels: approved, lgtm, size/XS

#1635 Remove unused image from components package
  lerna.json
  packages/components/src/images/tekton-horizontal-color.png
Labels: approved, lgtm, size/XS

#1636 Publish @tektoncd/dashboard-components 0.0.1-alpha.53
  lerna.json
Labels: approved, lgtm, size/XS

#1637 Fix OverflowMenu focus and keyboard nav issue
  packages/components/src/components/RunDropdown/RunDropdown.js
Labels: approved, lgtm, size/XS

#1640 Update to Carbon 10.16
  package-lock.json
  package.json
  packages/components/package.json
Labels: approved, lgtm, size/M

#1638 Ensure label / annotation forms fully support keyboard navigation
  packages/components/src/components/KeyValueList/KeyValueList.js
  packages/components/src/components/KeyValueList/KeyValueList.scss
  packages/components/src/components/KeyValueList/KeyValueList.test.js
  src/components/CreateSecret/CreateSecret.scss
  src/components/CreateSecret/Form/Annotations.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
Labels: approved, lgtm, size/M

#1642 Fix URL addressability for conditions in PipelineRun
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/S

#1643 Add label and queryParam constants
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/utils/src/utils/constants.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/api/index.js
  src/api/index.test.js
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/L

#1644 Accessibility fixes
  packages/components/src/components/Table/Table.js
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/containers/LogDownloadButton/LogDownloadButton.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1646 Update PipelineRun container logic to correctly select TaskRuns with conditions
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#1645 Update readme to include the v0.8.2 release
  README.md
Labels: approved, lgtm, size/XS

#1647 Display RunHeader with error details instead of 'No TaskRuns found' message
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1648 Publish @tektoncd/dashboard-components 0.0.1-alpha.54
  lerna.json
Labels: approved, lgtm, size/XS
