Repository tektoncd/dashboard, pull requests merged in 2020-02, with the labels that each got.

#982 Use unique identifiers for dashboard publish
  tekton/README.md
  tekton/build.yml
  tekton/publish.yaml
  tekton/release-pipeline.yml
  tekton/resources.yaml
Labels: approved, lgtm, size/L

#988 Display decoded secret usernames instead of base64 form
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/S

#986 Surface errors in read-only dashboard
  src/actions/secrets.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Secrets/Secrets.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/TaskRuns/TaskRuns.js
  src/reducers/secrets.js
Labels: approved, lgtm, size/L

#992 Remove unused 'notificationComponent' className
  src/containers/EventListeners/EventListeners.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/containers/Secrets/Secrets.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
Labels: approved, lgtm, size/XS

#1002 Kaniko task changes as latest is breaking integration test
  test/e2e-common.sh
  test/resources/static/kaniko-build-task.yaml
Labels: approved, lgtm, size/M

#1000 Display a reload message if no data yet found, prompt reload (temp fix)
  src/containers/Secrets/Secrets.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/S

#993 Update RunDropdown to ensure menu gets focus for keyboard nav
  packages/components/src/components/RunDropdown/RunDropdown.js
Labels: approved, lgtm, size/XS

#1005 Update Carbon icon imports to remove references to the CommonJS exports
  packages/components/src/components/CancelButton/CancelButton.js
  packages/components/src/components/Graph/Node.js
  packages/components/src/components/KeyValueList/KeyValueList.js
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Trigger/Trigger.js
  packages/utils/src/utils/index.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Secrets/Secrets.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/M

#1006 Fix overflow issue on step details
  packages/components/src/components/StepDefinition/StepDefinition.scss
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/StepStatus/StepStatus.scss
Labels: approved, lgtm, size/S

#991 Show secret and image pull secret names only for ServiceAccount page
  Gopkg.lock
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/ServiceAccount/ServiceAccount.test.js
Labels: approved, lgtm, size/M

#987 Add some missing frontend unit tests
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/Trigger/Trigger.test.js
  packages/utils/src/utils/index.test.js
  src/api/index.test.js
  src/containers/SideNav/SideNav.test.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1011 Move more user-facing strings to react-intl
  packages/components/src/components/CancelButton/CancelButton.test.js
  packages/components/src/components/Header/Header.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/Trigger/Trigger.js
  src/containers/Extension/Extension.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/Pipelines/Pipelines.js
  src/containers/SideNav/SideNav.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerTemplate/TriggerTemplate.js
Labels: approved, lgtm, size/L

#1004 make pipelineRun timestamp configurable
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/XS

#1016 Error notifications appear consistently for all create functions
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/ImportResources/ImportResources.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Secrets/Secrets.js
  src/containers/SecretsModal/SecretsModal.js
Labels: approved, lgtm, size/M

#1027 Service account namespace change bug
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/L

#1017 GKE Ingress requires 200 OK
  pkg/endpoints/health.go
  pkg/endpoints/health_test.go
Labels: approved, lgtm, size/XS

#1032 Update readme for nightly builds to close issues 921 and 839
  README.md
Labels: approved, lgtm, size/S

#1033 Secret create error doesn't show on modal and secrets page
  src/containers/Secrets/Secrets.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/M

#983 Add about page to display versions
  DEVELOPMENT.md
  base/300-deployment.yaml
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  pkg/router/routes_test.go
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/containers/About/index.js
  src/containers/App/App.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
  src/nls/messages_en.json
  tekton/README.md
Labels: approved, lgtm, size/L

#1020 Ensure checkbox is vertically centered in table rows
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/XS

#1022 Convert getStatusIcon to a component
  package-lock.json
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/StatusIcon/index.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.scss
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/index.js
  packages/utils/package.json
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, size/L

#1023 Update LabelFilter component design
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LabelFilter/LabelFilter.scss
  packages/components/src/components/LabelFilter/LabelFilter.test.js
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
Labels: approved, lgtm, size/L

#1019 Mention read-only and version 0.5 releases
  README.md
Labels: approved, lgtm, size/M

#1038 Fix EventListener Storybook Entry
  src/containers/EventListener/EventListener.stories.js
Labels: approved, lgtm, size/XS

#1048 About page now displays Openshift pipelines versions as well
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1040 Correct comment about unnamed step numbering
  packages/utils/src/utils/index.js
Labels: approved, lgtm, size/XS

#1039 Update Carbon to 10.9.3
  package-lock.json
  package.json
  packages/components/package.json
Labels: approved, lgtm, size/XXL

#1041 Refactor About container
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1042 Store full secret resource instead of custom structure
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/api/index.js
  src/api/index.test.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/reducers/index.js
  src/reducers/secrets.js
  src/reducers/secrets.test.js
Labels: approved, lgtm, size/L

#1060 Remove Carbon style imports from Table.scss
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/XS

#1059 Add log download button
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/api/index.js
  src/containers/LogDownloadButton/LogDownloadButton.js
  src/containers/LogDownloadButton/LogDownloadButton.stories.js
  src/containers/LogDownloadButton/index.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/containers/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1061 Remove duplicate lerna 'prepare' step in dev
  Dockerfile
  package.json
  tekton/build.yml
  test/presubmit-tests.sh
  test/publish-images.sh
Labels: approved, lgtm, size/S

#1062 Restore branch coverage threshold
  jest.config.js
Labels: approved, lgtm, size/XS

#1069 Publish @tektoncd/dashboard-components 0.0.1-alpha.39
  lerna.json
Labels: approved, lgtm, size/XS

#1066 Remove unused packages
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#1052 Add npm script to generate webpack bundle report
  .gitignore
  package.json
Labels: approved, lgtm, size/XS

#1053 Update TooltipDropdown to use ComboBox internally
  src/components/PipelineResourcesModal/UniversalFields.js
  src/components/SecretsModal/SecretsModal.scss
  src/components/SecretsModal/UniversalFields.js
  src/components/SecretsModal/UniversalFields.test.js
  src/components/TooltipDropdown/TooltipDropdown.js
  src/components/TooltipDropdown/TooltipDropdown.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.scss
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/ImportResources/ImportResources.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.test.js
  src/containers/PipelineResourcesModal/PipelineResourcesModalErrorNotification.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SecretsModal/SecretsModalErrorNotification.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.scss
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/XL

#1076 Add button to open logs in new window
  packages/components/src/components/Log/Log.scss
  src/containers/LogDownloadButton/LogDownloadButton.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1054 Update PipelineResource details view to match common layout
  src/containers/EventListener/EventListener.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/scss/Triggers.scss
Labels: approved, lgtm, size/L

#1055 Update PipelineResources page to use Table batch actions
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/Table/Table.scss
  src/containers/PipelineResources/PipelineResources.js
  src/containers/Secrets/Secrets.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1079 Add multiple action parameters to pipelineRuns
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
Labels: approved, lgtm, size/M

#1081 Update lerna.json
  lerna.json
Labels: approved, lgtm, size/XS

#1083 Fix alignment of Table checkboxes when row contains overflow menu
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/XS

#1057 Update Storybook to latest and refactor config
  .storybook/config.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/theme.js
  package-lock.json
  package.json
  packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.js
  packages/components/src/components/CancelButton/CancelButton.stories.js
  packages/components/src/components/FormattedDate/FormattedDate.stories.js
  packages/components/src/components/FormattedDuration/FormattedDuration.stories.js
  packages/components/src/components/Graph/Graph.stories.js
  packages/components/src/components/Header/Header.stories.js
  packages/components/src/components/KeyValueList/KeyValue.stories.js
  packages/components/src/components/LabelFilter/LabelFilter.stories.js
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/ResourceTable/ResourceTable.stories.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/Step/Step.stories.js
  packages/components/src/components/StepDefinition/StepDefinition.stories.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.stories.js
  packages/components/src/components/StepStatus/StepStatus.stories.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Tabs/Tabs.stories.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/TaskSkeleton/TaskSkeleton.stories.js
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/components/src/components/TextInput/TextInput.js
  packages/components/src/components/TextInput/TextInput.stories.js
  packages/components/src/components/TextInput/TextInput.test.js
  packages/components/src/components/TextInput/index.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.stories.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.test.js
  packages/components/src/components/TooltipDropdown/index.js
  packages/components/src/components/Trigger/Trigger.stories.js
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
  packages/components/src/components/index.js
  src/containers/EventListener/EventListener.stories.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.stories.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.stories.js
Labels: approved, lgtm, size/XL

#1086 Bump minimum k8s version to 1.15.0 and fix rerun pipelines (digest)
  DEVELOPMENT.md
  Gopkg.lock
  Gopkg.toml
  README.md
  pkg/endpoints/dashboard.go
Labels: approved, lgtm, size/L

#1090 Update StepStatus and StepDefinition to avoid undefined YAML tag
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/StepStatus/StepStatus.stories.js
  packages/components/src/components/StepStatus/StepStatus.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1093 Mock focus-trap to prevent flakiness in unit tests involving Modal
  config_frontend/__mocks__/focus-trap.js
Labels: approved, lgtm, size/M

#1084 Add suport for custom columns to the PipelineRuns component
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
Labels: approved, lgtm, size/L

#1091 Exclude LogDownloadButton from code coverage
  src/containers/LogDownloadButton/LogDownloadButton.js
Labels: approved, lgtm, size/XS

#1096 Publish @tektoncd/dashboard-components 0.0.1-alpha.41
  lerna.json
Labels: approved, lgtm, size/XS

#1077 Sort Tasks for PipelineRuns by their Task's earliest startedAt time
  packages/components/src/components/PipelineRun/PipelineRun.js
  testdata/ordering/pipeline.yaml
  testdata/ordering/pipelinerun.yaml
  testdata/ordering/tasks.yaml
Labels: approved, lgtm, size/L
