Repository tektoncd/dashboard, pull requests merged in 2020-09, with the labels that each got.

#1707 Ensure dashboard frontend can be built on Windows without change
  .gitattributes
  package-lock.json
  package.json
  packages/components/package.json
  packages/utils/package.json
Labels: approved, lgtm, size/M

#1710 Fix dashboard-run-ko task
  tekton/publish.yaml
Labels: approved, area/release, kind/bug, lgtm, size/XS

#1712 Add translations for PipelineRun and PipelineRuns components
  config_frontend/config.json
  package-lock.json
  package.json
  scripts/i18n/extractMessages.js
  scripts/i18n/importFromProperties.js
  src/containers/App/App.js
  src/nls/messages_de.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/XXL

#1717 Add tab showing story source in the storybook
  .storybook/main.js
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#1719 Add missing author, license, and repo details to npm packages
  packages/components/package.json
  packages/utils/package.json
Labels: approved, lgtm, size/S

#1716 update install commands in walkthrough for istio dashboard
  docs/walkthrough/walkthrough-istio.md
Labels: approved, lgtm, ok-to-test, size/S

#1720 Publish @tektoncd/dashboard-components 0.0.1-alpha.56
  lerna.json
Labels: approved, lgtm, size/XS

#1718 Fix logs persistence walkthrough
  docs/walkthrough/walkthrough-logs.md
Labels: approved, lgtm, size/S

#1721 Fix installer requiring ko and kustomize for remote releases
  scripts/installer
Labels: approved, lgtm, size/XS

#1724 Update PipelineRun component to be more resilient to incomplete status fields
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/S

#1711 Remove OpenShift specific installer script manifests
  .dockerignore
  base/200-clusterrole-dashboard.yaml
  cmd/dashboard/main.go
  docs/README.md
  docs/dev/api.md
  docs/install.md
  docs/oauth-certificate-workaround.md
  go.mod
  go.sum
  ingress/basic-dashboard-ingress.yaml
  ingress/https-ingress.yaml
  ingress/ingress-https-setup.sh
  overlays/installer/k8s/base/kustomization.yaml
  overlays/installer/k8s/read-write/kustomization.yaml
  overlays/installer/openshift/base/kustomization.yaml
  overlays/installer/openshift/read-write/kustomization.yaml
  overlays/installer/read-only/kustomization.yaml
  overlays/installer/read-write/kustomization.yaml
  overlays/patches/openshift/deployment-patch.yaml
  overlays/patches/openshift/serviceaccount-patch.yaml
  overlays/resources/openshift/route-service.yaml
  overlays/resources/openshift/route.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/cluster_test.go
  pkg/endpoints/types.go
  pkg/router/router.go
  pkg/router/routes_test.go
  scripts/installer
  tekton/README.md
  tekton/build.yaml
  tekton/openshift/publish.yaml
  tekton/publish.yaml
  tekton/release-pipeline.yaml
  tekton/scripts/lockdown.py
Labels: approved, area/release, kind/cleanup, lgtm, size/XL

#1726 Update screenshot in readme to reflect updated theme
  docs/dashboard-ui.png
Labels: approved, lgtm, size/XS

#1725 Release pipeline fixes
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#1733 Update e2e tests to latest pipelines and triggers versions
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1734 Fix cluster-scoped Kubernetes resource extensions
  src/api/index.js
  src/api/index.test.js
  src/api/utils.js
  src/api/utils.test.js
  src/containers/ResourceList/ResourceList.js
Labels: approved, lgtm, size/M
