Repository tektoncd/dashboard, pull requests merged in 2020-04, with the labels that each got.

#1220 Update Gopkg and tests to use 0.11
  Gopkg.lock
  Gopkg.toml
  test/e2e-common.sh
Labels: approved, lgtm, size/S

#1216 Update Logs component to display full logs up to 20,000 lines
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/Tab/index.js
  packages/components/src/components/Tabs/index.js
  packages/components/src/components/index.js
  src/containers/LogDownloadButton/index.js
  src/containers/ResourceList/ResourceList.js
  src/containers/ResourceList/index.js
  src/containers/index.js
Labels: approved, lgtm, size/L

#1224 Rename resource Details tab to Overview
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1225 This fixes the signal handling in the dashboard.
  Gopkg.lock
  cmd/dashboard/main.go
Labels: approved, lgtm, ok-to-test, size/M

#1238 Update readme to reference v0.6.0
  README.md
Labels: approved, lgtm, size/XS

#1237 add skeletonRowCount as param
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/Table/Table.js
Labels: approved, lgtm, size/S

#1235 Update style of metadata card for triggers pages
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.scss
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/EventListener/EventListener.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/scss/Triggers.scss
Labels: approved, lgtm, size/M

#1231 Update Table to add tooltips to all string values passed as cell content
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Extensions/Extensions.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
Labels: approved, lgtm, size/M

#1230 Remove unused Breadcrumbs component
  packages/components/src/components/Breadcrumbs/Breadcrumbs.js
  packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.js
  packages/components/src/components/Breadcrumbs/Breadcrumbs.test.js
  packages/components/src/components/Breadcrumbs/index.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/L

#1243 Fix flaky CreatePipelineRun test
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/L

#1229 Adapting namespace for openshift in the overlays. Fixes #1227
  README.md
  overlays/dev-openshift-imagestream/kustomization.yaml
  overlays/dev-openshift-locked-down/kustomization.yaml
  overlays/dev-openshift/kustomization.yaml
  overlays/latest-openshift-locked-down/kustomization.yaml
  overlays/latest-openshift/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/S

#1234 Update Triggers API group to match Triggers 0.4 release
  base/200-clusterrole.yaml
  overlays/full-fat/cluster-role-patch-json.yaml
  src/api/index.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/EventListener/EventListener.stories.js
  src/containers/EventListener/EventListener.test.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/SideNav/SideNav.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
Labels: approved, lgtm, size/M

#1256 Ensure param and resource handling is still compatible with v1alpha1
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/M

#1245 Address DAP (accessibility) violations
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LabelFilter/LabelFilter.scss
  packages/components/src/components/RunDropdown/RunDropdown.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/TaskRunStatus/TaskRunStatus.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/PipelineResource/PipelineResource.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/SideNav/SideNav.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerTemplate/TriggerTemplate.js
Labels: approved, lgtm, size/L

#1259 Fix log format
  pkg/endpoints/dashboard.go
Labels: approved, lgtm, ok-to-test, size/XS

#1244 Use versionTag for version label in nightly builds
  DEVELOPMENT.md
  base/300-deployment.yaml
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#1260 Add version label to Service
  base/300-service.yaml
  overlays/openshift-patches/dashboard-service.yaml
  overlays/openshift-patches/internal-dashboard-service.yaml
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#1236 Restore display of CEL interceptor details
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.test.js
  src/containers/EventListener/EventListener.js
Labels: approved, lgtm, size/L

#1267 Add Kind to the Resource Templates table
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/S

#1268 Copy docs from website
  docs/README.md
Labels: approved, lgtm, size/L

#1273 Add v1alpha1 constraint to deleting pipeline resources
  src/api/index.js
Labels: approved, lgtm, size/XS

#1274 Ensure actions are not displayed on TaskRuns in ReadOnly mode
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
Labels: approved, lgtm, size/XXL

#1275 Check for data field before checking for access token
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/XS

#1286 Update lerna.json
  lerna.json
Labels: approved, lgtm, size/XS

#1284 Add API for creating a TaskRun
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, ok-to-test, size/L

#1287 Fix step order issues
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L

#1289 Address moderate problems from npm audit
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#1294 Add a - between git-source and randomly generated letters
  src/containers/ImportResources/ImportResources.js
Labels: approved, lgtm, size/XS

#1295 adding a new sa when on secrets page no longer causes error
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/XS

#1279 Update loading states to be less disruptive
  packages/components/src/components/TooltipDropdown/TooltipDropdown.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.stories.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/EventListeners/EventListeners.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
Labels: approved, lgtm, size/L

#1292 Add support for external filters on Table component
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/Table.test.js
Labels: approved, lgtm, size/XL

#1281 Disable caching of all `/v1/*` and `/proxy/*` responses
  pkg/router/router.go
Labels: approved, lgtm, size/XS

#1296 Add watch permission for serviceaccounts
  base/200-clusterrole.yaml
Labels: approved, lgtm, size/XS

#1298 Only load TaskRuns for the selected PipelineRun
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#1280 Add Content-Security-Policy
  src/index.template.html
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: approved, lgtm, size/M

#1297 Pass through `filters` prop from PipelineRuns to Table
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/Table/Table.stories.js
Labels: approved, lgtm, size/M

#1301 Add Tasks and ClusterTasks dropdowns
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.stories.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/ClusterTasksDropdown/index.js
  src/containers/TasksDropdown/TasksDropdown.js
  src/containers/TasksDropdown/TasksDropdown.stories.js
  src/containers/TasksDropdown/TasksDropdown.test.js
  src/containers/TasksDropdown/index.js
  src/containers/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, ok-to-test, size/XL

#1262 Add support for configurable triggers and pipeline namespaces
  base/300-deployment.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
Labels: approved, lgtm, ok-to-test, size/M

#1265 Update release Tasks and Pipeline to v1beta1
  tekton/README.md
  tekton/build.yml
  tekton/publish.yaml
  tekton/release-pipeline.yml
Labels: approved, lgtm, size/L

#1302 Use self-contained pipeline run to import resources
  README.md
  base/400-pipeline0-task.yaml
  base/401-pipeline0.yaml
  base/kustomization.yaml
  src/api/index.js
  src/api/index.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/XL

#1308 Remove unused colour variables
  packages/components/src/scss/_vars.scss
Labels: approved, lgtm, size/S

#1307 Update storybook dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#1306 Remove unused string from i18n message bundle
  src/nls/messages_en.json
Labels: approved, lgtm, size/XS

#1305 Update react-intl and polyfills for recent Safari versions
  package-lock.json
  package.json
  packages/components/package.json
  src/utils/polyfills.js
Labels: approved, lgtm, size/S

#1125 Remove dynamic import ponyfill
  README.md
  src/containers/Extension/Extension.js
Labels: approved, lgtm, size/M

#1312 Add unsafe inline and blob to CSP
  webpack.common.js
Labels: approved, lgtm, size/XS

#1314 Publish @tektoncd/dashboard-components 0.0.1-alpha.46
  lerna.json
Labels: approved, lgtm, size/XS

#1316 Change finish button for patching secrets to a toolbar button
  src/components/CreateSecret/ServiceAccountSelector.js
Labels: approved, lgtm, size/S

#1318 Update readme to point to v0.6.1
  README.md
Labels: approved, lgtm, size/S

#1317 Change finish button for patching secrets to a toolbar button
  src/components/CreateSecret/ServiceAccountSelector.js
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#1309 Add `tkn` prefix to CSS class names - part 1
  packages/components/src/components/CancelButton/CancelButton.js
  packages/components/src/components/CancelButton/CancelButton.scss
  packages/components/src/components/Header/Header.js
  packages/components/src/components/Header/Header.scss
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LabelFilter/LabelFilter.scss
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/LogoutButton/LogoutButton.js
  packages/components/src/components/LogoutButton/LogoutButton.scss
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/Rerun/Rerun.scss
  packages/components/src/components/Rerun/Rerun.test.js
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/Spinner/Spinner.js
  packages/components/src/components/Spinner/Spinner.scss
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.scss
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.js
  packages/components/src/components/StepDetailsHeader/StepDetailsHeader.scss
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/StepStatus/StepStatus.scss
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/Task/Task.scss
  packages/components/src/components/TaskRunStatus/TaskRunStatus.js
  packages/components/src/components/TaskRunStatus/TaskRunStatus.scss
  packages/components/src/components/TaskSkeleton/TaskSkeleton.js
  packages/components/src/components/TaskSkeleton/TaskSkeleton.scss
  packages/components/src/components/TaskTree/TaskTree.js
  packages/components/src/components/TaskTree/TaskTree.scss
  packages/components/src/scss/Run.scss
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L

#1313 Update babel and webpack dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#1324 Define URLs and paths for the 'Create' pages
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
Labels: approved, lgtm, size/L

#1322 Add custom DataTableSkeleton component
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.js
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.scss
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.stories.js
  packages/components/src/components/DataTableSkeleton/index.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/index.js
  src/containers/PipelineResource/PipelineResource.js
Labels: approved, lgtm, size/L

#1331 Reference OpenShift 0.6.1 Dashboard release
  README.md
Labels: approved, lgtm, size/XS

#1333 Display filters on empty table
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.test.js
Labels: approved, lgtm, size/XS

#1337 Publish @tektoncd/dashboard-components 0.0.1-alpha.47
  lerna.json
Labels: approved, lgtm, size/XS

#1332 Reorganise SideNav to use menus in preparation for rail
  src/containers/SideNav/SideNav.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1325 ImportResources : Add dropdown for install namespace
  src/api/index.js
  src/api/index.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L
