Repository tektoncd/dashboard, pull requests merged in 2020-01, with the labels that each got.

#853 Delete duplicate delete pipelinerun tests
  src/api/index.test.js
Labels: approved, lgtm, size/S

#849 Prevent links in tables from wrapping
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
Labels: approved, lgtm, size/M

#855 Fix empty timeout error
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/S

#863 Change integration test to use 0.8.0 of pipelines
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#831 Use newer ko-ci images during release process
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#859 Fix rendering issue with empty secrets table
  packages/components/src/components/Table/Table.js
Labels: approved, lgtm, size/XS

#862 Override the default base image to run as non-root user
  .ko.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#864 Fix lint warnings
  config_frontend/setupTests.js
  packages/components/src/components/Graph/PanZoom.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SecretsModal/SecretsModalAnnotationText.test.js
  src/containers/SecretsModal/SecretsModalErrorNotification.test.js
Labels: approved, lgtm, size/S

#784 Add EventListener details page
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.scss
  packages/components/src/components/Trigger/Trigger.test.js
  packages/components/src/components/Trigger/index.js
  packages/components/src/components/index.js
  packages/utils/src/utils/router.js
  src/components/App/App.scss
  src/containers/App/App.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.test.js
  src/containers/EventListener/index.js
  src/containers/EventListeners/EventListeners.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XL

#870 Temporary: Bundle Carbon DataTable styles
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/XS

#867 Update secrets error message to indicate where a secret is already created
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#847 SA surfaced in Secrets table
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#869 Publish @tektoncd/dashboard-components 0.0.1-alpha.34
  lerna.json
Labels: approved, lgtm, size/XS

#871 Fix Table select styles
  packages/components/src/components/Table/Table.scss
  src/components/Definitions/Definitions.scss
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplate/TriggerTemplateTable.scss
Labels: approved, lgtm, size/M

#876 Publish @tektoncd/dashboard-components 0.0.1-alpha.35
  lerna.json
Labels: approved, lgtm, size/XS

#874 Display EventListener name in tooltip on list view
  src/containers/EventListeners/EventListeners.js
  src/containers/EventListeners/EventListeners.test.js
Labels: approved, lgtm, size/XS

#879 Common Error Title Intl
  src/containers/EventListeners/EventListeners.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/S

#836 Update PipelineRuns and TaskRuns status column
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/RunHeader/RunHeader.test.js
  packages/components/src/components/StepDetails/StepDetails.test.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  packages/components/src/components/TaskTree/TaskTree.test.js
  packages/utils/src/utils/index.js
  src/components/Definitions/Definitions.scss
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#886 Remove references to pipelines 0.9.0
  README.md
Labels: approved, lgtm, size/XS

#881 Remove gopkg.lock and update gopkg.toml to use Pipelines 0.8
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XL

#877 Fix extension test
  cmd/dashboard/main.go
  pkg/controllers/controller.go
  pkg/controllers/kubernetes/extension.go
  pkg/controllers/kubernetes/namespaces.go
  pkg/controllers/kubernetes/secret.go
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/router/router.go
  pkg/router/routes_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, size/XL

#882 Add created timestamp to ServiceAccounts list
  src/containers/ServiceAccounts/ServiceAccounts.js
Labels: approved, lgtm, size/S

#884 Use ViewYAML component anywhere YAML is rendered in the UI
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/index.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/EventListener/EventListener.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
Labels: approved, lgtm, size/M

#878 Show logs when no step name is provided
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L

#889 Add wait for deployment so timing error for pods doesnt happen
  test/e2e-common.sh
Labels: approved, lgtm, size/S

#887 Show Selected Resource Type when Viewing a Single Trigger
  src/containers/App/App.js
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/S

#860 Show Errored Task as Default in TaskRun/PipelineRun View
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/TaskTree/TaskTree.js
  packages/components/src/components/TaskTree/TaskTree.test.js
Labels: approved, lgtm, size/L

#890 Prevent Safari wrapping and overlapping text in Log component
  packages/components/src/components/Log/Log.scss
Labels: approved, lgtm, size/XS

#891 Publish @tektoncd/dashboard-components 0.0.1-alpha.36
  lerna.json
Labels: approved, lgtm, size/XS

#858 Ability to rerun pipelineruns from PipelineRuns page
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
Labels: approved, lgtm, size/M

#897 Fix infinite loop error in TaskTree
  packages/components/src/components/Task/Task.js
Labels: approved, lgtm, size/XS

#899 Update readme to reference 0.4.0 release
  README.md
Labels: approved, lgtm, size/S

#893 Enforce min and max zoom levels on pipeline graph
  packages/components/src/components/Graph/PanZoom.js
  packages/components/src/components/Graph/ZoomablePipelineGraph.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#896 Allow consumers of the components to disable the byPipeline link on PipelineRuns page
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
Labels: approved, lgtm, size/L

#906 Fix error showing TaskRun steps that have not run (again)
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/Task/Task.test.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L

#905 Improve truncation of long values in tables
  packages/components/src/components/FormattedDuration/FormattedDuration.js
  packages/components/src/components/FormattedDuration/FormattedDuration.test.js
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/utils/test.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
Labels: approved, lgtm, size/L

#898 Remove Duplicate Run.scss
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/Run.scss
  packages/components/src/scss/Run.scss
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/M

#910 Publish @tektoncd/dashboard-components 0.0.1-alpha.37
  lerna.json
Labels: approved, lgtm, size/XS

#915 Fix Typo
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#917 fix readme apply -f link for v0.4.0 release
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#923 Add environments and versions into issue template
  .github/issue-template.md
Labels: approved, lgtm, size/S

#920 Add RBAC for getting CRD info, used to detect Triggers installation
  config/dev-tekton-dashboard.yaml
  config/openshift/openshift-tekton-dashboard.yaml
  config/pipeline0-task.yaml
  config/release/gcr-tekton-dashboard.yaml
Labels: approved, lgtm, size/L

#924 Reference 0.4.1 in the readme
  README.md
Labels: approved, lgtm, size/XS

#928 Mention 0.4.1 dashboard release for non-openshift too
  README.md
Labels: approved, lgtm, size/XS

#931 Add missing tooltip on PipelineRuns Pipeline column
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, size/XS

#934 Preserve newlines in copy-pasted logs
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/XS

#912 Update categories for dashboard extension CRD
  config/dev-tekton-dashboard.yaml
  config/openshift/openshift-tekton-dashboard.yaml
  config/release/gcr-tekton-dashboard.yaml
  config/templates/deploy.yaml
  test/e2e-common.sh
Labels: approved, lgtm, size/L

#926 Update Secrets Page to Include Filters
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/nls/messages_en.json
  src/reducers/index.js
Labels: approved, lgtm, size/L

#908 Fix unnamed steps bug
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, size/S

#941 Introduce Kustomize and create locked-down dashboard build
  DEVELOPMENT.md
  README.md
  base/200-clusterrole.yaml
  base/201-clusterrolebinding.yaml
  base/202-extension-crd.yaml
  base/203-serviceaccount.yaml
  base/300-deployment.yaml
  base/300-service.yaml
  base/400-pipeline0-task.yaml
  base/401-pipeline0.yaml
  base/kustomization.yaml
  config/dev-tekton-dashboard.yaml
  config/openshift/openshift-tekton-dashboard.yaml
  config/pipeline0.yaml
  config/release/gcr-tekton-dashboard.yaml
  config/templates/build.yaml
  config/templates/deploy.yaml
  overlays/dev-locked-down/kustomization.yaml
  overlays/dev-openshift-imagestream/build.yaml
  overlays/dev-openshift-imagestream/kustomization.yaml
  overlays/dev-openshift-locked-down/kustomization.yaml
  overlays/dev-openshift/kustomization.yaml
  overlays/dev/kustomization.yaml
  overlays/full-fat/cluster-role-patch-json.yaml
  overlays/full-fat/kustomization.yaml
  overlays/latest-locked-down/kustomization.yaml
  overlays/latest-openshift-locked-down/kustomization.yaml
  overlays/latest-openshift/kustomization.yaml
  overlays/latest/kustomization.yaml
  overlays/openshift-patches/dashboard-service.yaml
  overlays/openshift-patches/internal-dashboard-service.yaml
  overlays/openshift-patches/oauth-proxy-in-deployment.yaml
  overlays/openshift-patches/route.yaml
  overlays/openshift-patches/serviceaccount.yaml
  test/e2e-common.sh
Labels: approved, lgtm, size/XXL

#939 Fix flaky frontend unit tests
  jest.config.js
  src/actions/secrets.test.js
  src/actions/tasks.test.js
  src/api/index.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/EventListener/EventListener.test.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/store/index.test.js
Labels: approved, lgtm, size/XL

#943 Fix style of primary button on delete modals
  packages/components/src/components/RunDropdown/RunDropdown.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/XS

#947 Fix PropType warning on Table component
  packages/components/src/components/Table/Table.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/containers/ClusterTasks/ClusterTasks.js
Labels: approved, lgtm, size/S

#938 Remove useZebraStyles prop on DataTables
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  src/containers/TriggerTemplate/TriggerTemplate.js
Labels: approved, lgtm, size/S

#901 Add Cache-Control header to static resources to help caching
  pkg/router/router.go
Labels: approved, lgtm, ok-to-test, size/S

#946 Use 0.10 of Pipelines for integration tests
  test/e2e-common.sh
  test/resources/envsubst/pipelineresource-git.yaml
  test/resources/envsubst/pipelineresource-image.yaml
  test/resources/envsubst/pipelinerun.yaml
Labels: approved, lgtm, size/M

#955 Additional stability improvements for CreatePipelineRun tests
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/M

#953 Small corrections to README and DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/S

#948 Update Header styles to more closely match Carbon
  packages/components/src/components/Header/Header.js
  packages/components/src/components/Header/Header.scss
  packages/components/src/components/Header/Header.stories.js
  packages/components/src/components/Header/Header.test.js
  packages/components/src/components/LogoutButton/LogoutButton.js
  packages/components/src/components/LogoutButton/LogoutButton.test.js
  packages/components/src/images/tekton-logo-20x20.svg
  src/components/App/App.scss
  src/containers/App/App.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.scss
  src/containers/SideNav/SideNav.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#959 Update issue template to be a little cleaner
  .github/issue-template.md
Labels: approved, lgtm, size/S

#958 Add missing router utils unit tests
  packages/utils/src/utils/router.test.js
Labels: approved, lgtm, size/L

#962 Fix display of step details
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/StepStatus/StepStatus.test.js
  packages/components/src/components/Task/Task.js
  packages/utils/src/utils/index.js
Labels: approved, lgtm, size/M

#963 Publish @tektoncd/dashboard-components 0.0.1-alpha.38
  lerna.json
Labels: approved, lgtm, size/XS

#957 Reduce duplication of LabelFilters code across containers
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/EventListeners/EventListeners.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/reducers/index.js
Labels: approved, lgtm, size/XL

#964 Add filter functionality to remaining list pages
  src/actions/actionCreators.js
  src/actions/pipelineResources.js
  src/actions/pipelines.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/api/index.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
  src/reducers/index.js
Labels: approved, lgtm, size/L

#952 Use Kustomize for release process, publish read-only installs
  tekton/README.md
  tekton/build.yml
  tekton/publish.yaml
  tekton/release-pipeline.yml
  tekton/resources.yaml
Labels: approved, lgtm, size/L

#967 Update to latest Carbon release (10.9.2)
  package-lock.json
  package.json
  packages/components/package.json
  src/components/TooltipDropdown/TooltipDropdown.js
  src/containers/EventListener/EventListener.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/L

#968 Update storybook to latest version
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#942 Add frontend for creating PipelineResource
  src/components/PipelineResourcesModal/GitResourceFields.js
  src/components/PipelineResourcesModal/UniversalFields.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.test.js
  src/containers/PipelineResourcesModal/PipelineResourcesModalErrorNotification.test.js
  src/containers/PipelineResourcesModal/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XXL

#971 Move more user-facing strings to react-intl
  packages/components/src/components/StepDetails/StepDetails.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.test.js
  src/components/SecretsModal/BasicAuthFields.js
  src/components/SecretsModal/BasicAuthFields.test.js
  src/components/SecretsModal/UniversalFields.js
  src/components/SecretsModal/UniversalFields.test.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/EventListener/EventListener.js
  src/containers/Extensions/Extensions.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.test.js
  src/containers/PipelineResourcesModal/PipelineResourcesModalErrorNotification.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Secrets/Secrets.js
  src/containers/SecretsModal/SecretsModal.js
  src/containers/SecretsModal/SecretsModal.test.js
  src/containers/SecretsModal/SecretsModalErrorNotification.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#977 Update page header styles
  packages/components/src/components/LabelFilter/LabelFilter.scss
  packages/components/src/components/RunHeader/RunHeader.scss
  src/components/App/App.scss
  src/components/Definitions/Definitions.scss
  src/scss/Triggers.scss
Labels: approved, lgtm, size/S

#970 Display correct errors in dashboard pod logs
  pkg/endpoints/cluster.go
Labels: approved, lgtm, size/S

#973 Remove flaky extension test
  pkg/router/routes_test.go
Labels: approved, lgtm, size/L
