Repository tektoncd/dashboard, pull requests merged in 2020-11, with the labels that each got.

#1810 Update webpack devserver proxy config for remote backends
  webpack.dev.js
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1804 Update release versions used for e2e tests
  test/e2e-tests.sh
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1787 Enable storybook essentials
  .storybook/Container.js
  .storybook/Container.scss
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.stories.js
  packages/components/src/components/FormattedDate/FormattedDate.stories.js
  packages/components/src/components/FormattedDuration/FormattedDuration.stories.js
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/LoadingShell/LoadingShell.scss
  packages/components/src/components/LogFormat/LogFormat.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.stories.js
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
  src/components/App/App.scss
  src/containers/EventListener/EventListener.stories.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
  src/containers/Secrets/Secrets.js
Labels: approved, hacktoberfest-accepted, lgtm, size/XXL

#1805 Update DetailsHeader stories to include `type` control
  packages/components/src/components/DetailsHeader/DetailsHeader.stories.js
Labels: approved, hacktoberfest-accepted, lgtm, size/M

#1806 Update design of the TaskTree component
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/Spinner/Spinner.js
  packages/components/src/components/Spinner/Spinner.scss
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/components/src/components/StatusIcon/StatusIcon.scss
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.scss
  packages/components/src/components/TaskTree/TaskTree.scss
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/components/src/components/TaskTree/TaskTree.test.js
  packages/components/src/scss/Run.scss
Labels: approved, hacktoberfest-accepted, lgtm, size/L

#1813 Add Japanese translation to messages_ja.json
  src/nls/messages_ja.json
Labels: approved, lgtm, ok-to-test, size/XL

#1812 Update README to point at 0.10.2 docs
  README.md
  docs/README.md
Labels: approved, lgtm, size/M

#1811 Add batch delete for TaskRuns and PipelineRuns
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/RunDropdown/RunDropdown.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1816 Fix validation of optional params on Create run dialogs
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
Labels: approved, lgtm, size/M

#1817 Ensure table headers don't wrap
  src/components/App/App.scss
Labels: approved, lgtm, size/XS

#1814 Refactor TaskRun / PipelineRun component trees to separate definitions from runtime data
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.stories.js
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/StepDetails/StepDetails.test.js
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/Task/index.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/TaskTree/TaskTree.js
  packages/components/src/components/TaskTree/TaskTree.stories.js
  packages/components/src/components/TaskTree/TaskTree.test.js
  packages/utils/src/utils/constants.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/App/index.js
  src/containers/LogDownloadButton/LogDownloadButton.js
  src/containers/LogDownloadButton/LogDownloadButton.stories.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_en.json
  src/utils/index.js
  src/utils/index.test.js
  src/utils/object-is.js
  src/utils/polyfills.js
Labels: approved, lgtm, size/XXL

#1818 Move LogDownloadButton to packages/components
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/LogDownloadButton/LogDownloadButton.js
  packages/components/src/components/LogDownloadButton/LogDownloadButton.stories.js
  packages/components/src/components/LogDownloadButton/index.js
  packages/components/src/components/index.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/containers/index.js
Labels: approved, lgtm, size/S

#1819 Handle missing step definition when Task deleted but TaskRun remains
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, size/S

#1821 Rename pipelineTaskName to displayName in Task components
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/TaskTree/TaskTree.js
Labels: approved, lgtm, size/L

#1820 Remove unneccessary _vars.scss
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.scss
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/StatusIcon/StatusIcon.scss
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Task/Task.scss
  packages/components/src/scss/_vars.scss
  src/components/Definitions/Definitions.scss
  src/containers/EventListener/EventListener.scss
Labels: approved, lgtm, size/M

#1822 Display duration on TaskRun and step details
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/DetailsHeader/DetailsHeader.test.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/Task/Task.stories.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1823 Rename `stepName` to `displayName` in DetailsHeader component
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.stories.js
  packages/components/src/components/DetailsHeader/DetailsHeader.test.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
Labels: approved, lgtm, size/S

#1824 Update `getLogDownloadButton` params to match `fetchLogs`
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1825 Remove storybook-react-router
  .storybook/Container.js
  package-lock.json
  package.json
  packages/components/src/components/Header/Header.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/Trigger/Trigger.stories.js
  src/containers/EventListener/EventListener.stories.js
Labels: approved, lgtm, size/XXL

#1826 Update to Carbon 10.23 and latest React 16.x
  package-lock.json
  package.json
  packages/components/package.json
  packages/utils/package.json
Labels: approved, lgtm, size/M

#1827 Add margin between duration and tabs container
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
Labels: approved, lgtm, size/XS

#1828 Remove unused Tabs styles
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.scss
Labels: approved, lgtm, size/S

#1829 Publish @tektoncd/dashboard-components 0.0.1-alpha.61
  lerna.json
Labels: approved, lgtm, size/XS

#1830 Reduce font size of duration in DetailsHeader
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
Labels: approved, lgtm, size/XS

#1831 Publish @tektoncd/dashboard-components 0.0.1-alpha.62
  lerna.json
Labels: approved, lgtm, size/XS

#1832 Add link to v0.11 docs
  README.md
Labels: approved, lgtm, size/XS

#1834 Reduce warnings output in the unit tests
  packages/components/src/components/TooltipDropdown/TooltipDropdown.test.js
  packages/utils/package.json
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TasksDropdown/TasksDropdown.test.js
Labels: approved, lgtm, size/S

#1837 Fix for websocket connection blocked by CSP in Safari
  webpack.common.js
Labels: approved, lgtm, size/XS

#1838 Suppress fetch-mock warning on fallback
  config_frontend/setupTests.js
Labels: approved, lgtm, size/XS

#1841 Add 0.11.1 release links to the readme
  README.md
Labels: approved, lgtm, size/XS

#1843 Handle edge case where TaskRun resource not available on PipelineRun page
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, size/S

#1844 Publish @tektoncd/dashboard-components 0.0.1-alpha.63
  lerna.json
Labels: approved, lgtm, size/XS

#1839 Update to React 17
  .storybook/preview.js
  package-lock.json
  package.json
  packages/components/package.json
  packages/utils/package.json
  src/containers/CreateSecret/CreateSecret.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/utils/polyfills.js
Labels: approved, lgtm, size/XXL

#1845 Remove duplicate test utils
  packages/components/src/components/DetailsHeader/DetailsHeader.test.js
  packages/components/src/components/FormattedDuration/FormattedDuration.test.js
  packages/components/src/utils/test.js
  src/components/CreateSecret/Form/AccessTokenType.test.js
  src/components/CreateSecret/Form/Annotations.test.js
  src/components/CreateSecret/Form/PasswordType.test.js
  src/components/CreateSecret/Form/UniversalFields.test.js
  src/components/CreateSecret/Form/index.test.js
  src/components/CreateSecret/ServiceAccountSelector.test.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.test.js
  src/containers/About/About.test.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/Condition/Condition.test.js
  src/containers/Conditions/Conditions.test.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateSecret/CreateSecret.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/EventListener/EventListener.test.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/Secret/Secret.test.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/SideNav/SideNav.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TasksDropdown/TasksDropdown.test.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
  src/utils/test.js
Labels: approved, lgtm, size/L

#1846 Update Storybook
  .storybook/tekton-horizontal-color.png
  .storybook/tekton-horizontal-color.svg
  .storybook/theme.js
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#1847 Update Dockerfile to use golang 1.15 for image stream builds
  Dockerfile
Labels: approved, lgtm, size/XS

#1849 Publish multi-arch image
  docs/dev/README.md
  scripts/installer
  tekton/publish.yaml
Labels: approved, lgtm, size/S

#1850 Remove publish-images.sh
  test/publish-images.sh
Labels: approved, lgtm, size/M
