Repository tektoncd/dashboard, pull requests merged in 2020-03, with the labels that each got.

#1099 Add ClusterTriggerBindings panel and ClusterTriggerBinding details page
  packages/components/src/components/Breadcrumbs/Breadcrumbs.js
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/actions/clusterTriggerBindings.js
  src/api/index.js
  src/api/index.test.js
  src/containers/App/App.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/ClusterTriggerBinding/index.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/ClusterTriggerBindings/index.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
  src/reducers/clusterTriggerBindings.js
  src/reducers/index.js
Labels: approved, lgtm, size/XXL

#1098 Update Table loading state to show headers
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.test.js
Labels: approved, lgtm, size/S

#1100 Fix spacing between filter and following content
  packages/components/src/components/LabelFilter/LabelFilter.scss
Labels: approved, lgtm, size/S

#1097 Add support for setting the danger flag on RunDropdown items
  packages/components/src/components/RunDropdown/RunDropdown.js
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/S

#1109 Correctly pick up Docker type secrets
  src/components/CreateSecret/Form/Annotations.js
Labels: approved, lgtm, size/XS

#1113 Add missing strings for DataTable
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.test.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1110 Issue: 1051 - Do not expose URL in v1/extensions
  pkg/router/router.go
  pkg/router/routes_test.go
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#1116 Password is selected as default secret type
  src/containers/CreateSecret/CreateSecret.js
Labels: approved, lgtm, size/XS

#1114 Publish @tektoncd/dashboard-components 0.0.1-alpha.42
  lerna.json
Labels: approved, lgtm, size/XS

#1117 Access token secrets can be viewed in the secrets table
  src/api/index.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
Labels: approved, lgtm, size/L

#1111 Display server URL for Docker registry once again
  src/components/CreateSecret/Form/Annotations.js
  src/containers/CreateSecret/CreateSecret.js
Labels: approved, lgtm, size/M

#1118 Batch action bar doesn't display if there are no secrets
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/S

#1092 issue #1088 : add oauth proxy config option to skip the openshift sign-in pop-up window
  overlays/openshift-patches/oauth-proxy-in-deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1120 Change radio buttons on secrets page to horizontal alignment
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/XS

#1043 Don't display actions or import if in read-only mode
  DEVELOPMENT.md
  README.md
  base/300-deployment.yaml
  overlays/dev-locked-down/kustomization.yaml
  overlays/dev-openshift-locked-down/kustomization.yaml
  overlays/latest-locked-down/kustomization.yaml
  overlays/latest-openshift-locked-down/kustomization.yaml
  overlays/readonly/readonly-deployment-patch.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  src/actions/properties.js
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/reducers/index.js
  src/reducers/properties.js
  tekton/publish.yaml
  tekton/resources.yaml
Labels: approved, lgtm, size/XL

#1119 Update to Carbon 10.10
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/components/LabelFilter/LabelFilter.test.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/TriggerBinding/TriggerBinding.test.js
Labels: approved, lgtm, size/XXL

#1126 Fixes #872
  src/containers/CreateSecret/CreateSecret.js
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, ok-to-test, size/S

#1128 Publish @tektoncd/dashboard-components 0.0.1-alpha.43
  lerna.json
Labels: approved, lgtm, size/XS

#1123 Remove style overrides for Delete Secrets modal
  src/components/Definitions/Definitions.scss
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.scss
Labels: approved, lgtm, size/M

#1124 Update Extensions and ResourceList to use DataTable
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/Table/Table.test.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/components/CreateSecret/ServiceAccountSelector.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/EventListeners/EventListeners.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/Extensions/Extensions.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1130 About page shows pipeline beta version
  pkg/endpoints/dashboard.go
Labels: approved, lgtm, size/S

#1072 clickjacking fix
  pkg/router/router.go
Labels: approved, lgtm, size/XS

#1131 Extract Dropdown strings for translation
  packages/components/src/components/TooltipDropdown/TooltipDropdown.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.test.js
  src/actions/secrets.js
  src/api/index.js
  src/components/CreateSecret/ServiceAccountSelector.js
  src/containers/About/About.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.stories.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1139 Don't always display secret notifications
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/XS

#1140 Fix error where selecting x on namespace button breaks page
  src/containers/CreateSecret/CreateSecret.js
  src/containers/CreateSecret/CreateSecret.test.js
Labels: approved, lgtm, size/S

#1143 `x` clears namespace box in import resources
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/S

#1149 Secrets table shows correct service accounts
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
Labels: approved, lgtm, size/XS

#1150 Use selectedNamespace as key for Table component
  packages/components/src/components/Table/Table.js
Labels: approved, lgtm, size/XS

#1152 Remove Jess, Carlos, Vincent as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#1151 Correctly show ServiceAccounts for namespace secret was created in
  src/containers/CreateSecret/CreateSecret.js
Labels: approved, lgtm, size/S

#1138 Add secret details page
  packages/utils/src/utils/router.js
  src/actions/secrets.js
  src/api/index.js
  src/api/index.test.js
  src/containers/App/App.js
  src/containers/Secret/Secret.js
  src/containers/Secret/Secret.test.js
  src/containers/Secret/index.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
  src/reducers/index.js
  src/reducers/secrets.js
Labels: approved, lgtm, size/XL

#1161 Fix secrets changing to all namespace issue
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/M

#1163 Fix PipelineResource creation to use v1alpha1
  src/api/index.js
Labels: approved, lgtm, size/XS

#1166 Remove details of CEL-interceptors from EventListener display
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.test.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.test.js
Labels: approved, lgtm, size/L

#1168 Update README to include reference to v0.5.3 release
  README.md
Labels: approved, lgtm, size/XS

#1169 Fix log line positioning issue in Safari
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
Labels: approved, lgtm, size/XS

#1170 Allow consumers of PipelineRun component to do their own TaskRun sorting
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/S

#1174 Make Accessing the Dashboard Section Easier to Find
  README.md
Labels: approved, lgtm, size/S

#1171 Publish @tektoncd/dashboard-components 0.0.1-alpha.44
  lerna.json
Labels: approved, lgtm, size/XS

#1172 Add support for taskSpec in PipelineRun
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, ok-to-test, size/S

#1182 Include ClusterTasks in set of tasks provided to PipelineRun component
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/S

#1180 task page namespace change fix
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/M

#1184 Display init containers in TaskTree when failed
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/utils/src/utils/index.js
Labels: approved, lgtm, size/L

#1188 Change how we install kustomize to work with Golang 1.14
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1187 Stop clearing the global selected namespace when cancelling create secret dialog
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/S

#1185 Secrets table display changes based one what type of secret has been created
  src/containers/CreateSecret/CreateSecret.js
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/XS

#1189 Secrets with names the same as a namespace can be created
  src/reducers/secrets.js
Labels: approved, lgtm, size/XS

#1190 Add websocket events for ServiceAccounts
  pkg/broadcaster/broadcaster.go
  pkg/controllers/controller.go
  pkg/controllers/kubernetes/serviceAccount.go
Labels: approved, lgtm, size/M

#1192 Update KeyValueList design to match Annotations in CreateSecret form
  packages/components/src/components/KeyValueList/KeyValueList.js
  packages/components/src/components/KeyValueList/KeyValueList.scss
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/KeyValueList/KeyValueList.test.js
  src/components/CreateSecret/Form/Annotations.js
  src/components/CreateSecret/ServiceAccountSelector.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/L

#1195 Fix for CEL interceptors with no overlays
  packages/components/src/components/Trigger/Trigger.js
Labels: approved, lgtm, size/XS

#1194 Prepare for Triggers API group change
  src/api/index.js
Labels: approved, lgtm, size/M

#1201 Update references to params and resources to use new structure
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/components/src/components/StepDefinition/StepDefinition.stories.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/M

#1210 Updates to use Pipelines Beta
  Gopkg.lock
  Gopkg.toml
  base/400-pipeline0-task.yaml
  base/401-pipeline0.yaml
  src/api/index.js
  src/api/index.test.js
  test/e2e-common.sh
Labels: approved, lgtm, size/L

#1205 Update rerun notification
  packages/components/src/components/Rerun/Rerun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/Secrets/Secrets.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/S

#1203 Guard against ServiceAccount with no secrets
  src/containers/Secret/Secret.js
Labels: approved, lgtm, size/XS

#1212 Add Triggers version to About page
  DEVELOPMENT.md
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  src/containers/About/About.js
  src/containers/About/About.test.js
Labels: approved, lgtm, size/L

#1153 Fix duplicate errors for secret notifications
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/XS

#1214 Fix typo in Trigger component
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.scss
Labels: approved, lgtm, size/XS

#1197 add standalone taskRun status to handle some error cases
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/TaskRunStatus/TaskRunStatus.js
  packages/components/src/components/TaskRunStatus/TaskRunStatus.scss
  packages/components/src/components/TaskRunStatus/TaskRunStatus.stories.js
  packages/components/src/components/TaskRunStatus/TaskRunStatus.test.js
  packages/components/src/components/TaskRunStatus/index.js
  packages/components/src/components/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L
