Repository tektoncd/dashboard, pull requests merged in 2020-10, with the labels that each got.

#1735 Update to Carbon 10.20
  config_frontend/setupTests.js
  package-lock.json
  package.json
  packages/components/package.json
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/M

#1736 Ensure FormattedDate always provides a tooltip with the absolute date/time
  packages/components/src/components/FormattedDate/FormattedDate.js
Labels: approved, lgtm, size/M

#1738 Add support for resources using `generateName` in Import Resources
  src/api/index.js
  src/api/index.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/ImportResources/ImportResources.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1737 Add keywords to @tektoncd/dashboard-components package
  packages/components/package.json
Labels: approved, lgtm, size/XS

#1740 Publish @tektoncd/dashboard-components 0.0.1-alpha.57
  lerna.json
Labels: approved, lgtm, size/XS

#1741 Reduce scope of uninstall command to resource kinds used by dashboard
  scripts/installer
Labels: approved, lgtm, size/S

#1742 Use ko:// prefix for dashboard image
  overlays/installer/base/kustomization.yaml
  scripts/installer
Labels: approved, lgtm, ok-to-test, size/XS

#1739 Update to Node.js 14
  Dockerfile
  docs/dev/README.md
  package.json
  packages/components/package.json
  packages/utils/package.json
  tekton/build.yaml
  test/presubmit-tests.sh
  test/publish-images.sh
Labels: approved, lgtm, size/S

#1745 Use globally selected namespace by default on Create pages
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreateSecret/CreateSecret.js
  src/containers/CreateSecret/CreateSecret.test.js
Labels: approved, lgtm, size/M

#1744 Remove GitHub restriction on Import Resources
  package-lock.json
  package.json
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/nls/messages_en.json
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1746 Remove unnecessary fetch polyfill from frontend
  config_frontend/setupTests.js
  package-lock.json
  package.json
  src/api/extensions.test.js
  src/utils/polyfills.js
Labels: approved, lgtm, size/L

#1750 Add 0.10.0 links to readme
  README.md
Labels: approved, lgtm, size/XS

#1751 Use a brighter blue in the logs
  packages/components/src/components/LogFormat/LogFormat.scss
Labels: approved, lgtm, size/XS

#1748 Move Rerun PipelineRun API to frontend
  package-lock.json
  package.json
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/Rerun/Rerun.test.js
  pkg/endpoints/pipeline.go
  pkg/router/router.go
  pkg/router/routes_test.go
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1747 Remove unnecessary polyfills
  .browserslistrc
  .storybook/.babelrc
  babel.config.js
  package-lock.json
  package.json
  src/utils/polyfills.js
Labels: approved, lgtm, size/M

#1749 Add support for rerunning standalone TaskRuns
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/Rerun/Rerun.test.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/api/pipelineRuns.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1728 Update Dev docs
  docs/dev/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1753 Set runAsUser uid for nonroot distroless image
  base/300-deployment.yaml
Labels: approved, kind/bug, lgtm, size/XS

#1754 Remove unnecessary border on Table filters
  packages/components/src/components/Table/Table.scss
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1757 Fix highlighting colour on taskRun in taskTree when focus moves away
  packages/components/src/components/Task/Task.scss
Labels: approved, hacktoberfest-accepted, lgtm, size/S

#1762 Add missing UnorderedList styles
  src/components/App/_carbon.scss
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1764 Remove legacy exceptions from the Content Security Policy settings
  webpack.common.js
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1765 update lerna.json to 0.0.1-alpha.58
  lerna.json
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1769 Fix styles and label for cancelled steps
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/DetailsHeader/DetailsHeader.test.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Step/Step.test.js
Labels: approved, hacktoberfest-accepted, lgtm, size/M

#1772 Fix update handlers in extensions and ClusterTasks reducers
  src/reducers/clusterTasks.js
  src/reducers/clusterTasks.test.js
  src/reducers/extensions.js
  src/reducers/extensions.test.js
Labels: approved, hacktoberfest-accepted, lgtm, size/S

#1767 Remove deprecated storybook config
  .storybook/preview.js
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1774 Update string on Import Resource success notification
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/nls/messages_en.json
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1776 Publish @tektoncd/dashboard-components 0.0.1-alpha.59
  lerna.json
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1777 Add guard to log fetchers for missing step status
  src/utils/index.js
Labels: approved, lgtm, size/XS

#1782 Add support for Triggers 0.9
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.stories.js
  packages/components/src/components/Trigger/Trigger.test.js
  src/scss/Triggers.scss
Labels: approved, lgtm, size/L

#1785 Handle missing TaskRun status in TaskRunDetails component
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
Labels: approved, hacktoberfest-accepted, lgtm, size/S

#1799 update lerna json
  lerna.json
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1801 add 0.10.1 doc link to read me
  README.md
Labels: approved, hacktoberfest-accepted, lgtm, size/XS

#1789 Fix rerun of cancelled runs
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
Labels: approved, hacktoberfest-accepted, lgtm, size/M

#1798 Update Node.js to v14 LTS
  package.json
  packages/components/package.json
  packages/utils/package.json
  tekton/build.yaml
  test/presubmit-tests.sh
  test/publish-images.sh
Labels: approved, hacktoberfest-accepted, lgtm, size/S

#1802 Fix loading of CRD extensions when a specific namespace is selected
  src/containers/App/App.js
  src/containers/App/App.test.js
Labels: approved, hacktoberfest-accepted, lgtm, size/S

#1807 Fix key prop warning on LogFormat component
  packages/components/src/components/LogFormat/LogFormat.js
Labels: approved, hacktoberfest-accepted, lgtm, size/XS
