Repository tektoncd/dashboard, pull requests merged in 2020-12, with the labels that each got.

#1852 Add additional handling to prevent possible UI error selecting default Task / step
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#1854 Make main nav collapsible
  package-lock.json
  package.json
  packages/components/src/components/Header/Header.js
  packages/components/src/components/Header/Header.scss
  packages/components/src/components/Header/Header.test.js
  packages/components/src/components/Header/index.js
  packages/components/src/components/LoadingShell/LoadingShell.js
  packages/components/src/components/PipelineResources/index.js
  src/components/App/App.scss
  src/containers/About/About.js
  src/containers/App/App.js
  src/containers/ListPageLayout/ListPageLayout.js
  src/containers/ListPageLayout/ListPageLayout.stories.js
  src/containers/ListPageLayout/ListPageLayout.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.scss
  src/containers/SideNav/SideNav.test.js
  src/images/kubernetes.svg
  src/images/tekton-logo-20x20.svg
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  webpack.common.js
Labels: approved, lgtm, size/XL

#1857 Update integration test script to install Pipelines and Triggers once
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#1856 Add filter functionality to the ResourceList page
  packages/components/src/components/LoadingShell/index.js
  src/api/index.js
  src/containers/ResourceList/ResourceList.js
Labels: approved, lgtm, size/M

#1855 Add styling for active submenus on rail nav
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.scss
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/L

#1858 Reduce duplication in the SideNav component
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/L

#1860 Update to webpack 5
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: approved, lgtm, size/XXL

#1862 Update Pipelines and Triggers versions used in integration tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1861 Fix header styles for RunHeader and DetailsHeader components
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.scss
Labels: approved, lgtm, size/S

#1863 Update eslint
  package-lock.json
  package.json
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LogDownloadButton/LogDownloadButton.js
  packages/components/src/components/LogFormat/LogFormat.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepStatus/StepStatus.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/Table.test.js
  packages/components/src/components/Tabs/Tabs.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.stories.js
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/components/CreateSecret/Form/Annotations.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/Extension/Extension.js
  src/containers/Extensions/Extensions.js
  src/containers/ReadWriteRoute/ReadWriteRoute.js
  src/containers/Secret/Secret.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/reducers/index.js
  src/reducers/reducerCreators.test.js
Labels: approved, lgtm, size/XL

#1866 Update integration tests to latest Pipelines release
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1865 Remove `Object.is` polyfill
  src/utils/object-is.js
  src/utils/polyfills.js
Labels: approved, lgtm, size/S

#1867 Fix RunHeader font styles
  packages/components/src/components/RunHeader/RunHeader.scss
Labels: approved, lgtm, size/XS

#1870 Add ability to filter runs by status
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/StatusFilterDropdown/StatusFilterDropdown.js
  packages/components/src/components/StatusFilterDropdown/index.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/index.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1869 Display placeholders for pipeline tasks that haven't begun executing yet
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/utils/src/utils/constants.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/L

#1872 Update empty state strings for consistency and accuracy
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  packages/components/src/components/Table/Table.test.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  src/components/CreateSecret/ServiceAccountSelector.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/Conditions/Conditions.js
  src/containers/EventListeners/EventListeners.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/Extensions/Extensions.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/ServiceAccounts/ServiceAccounts.test.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1873 Add v0.12.0 release to readme
  README.md
Labels: approved, lgtm, size/XS

#1875 fix paramaters to parameters
  src/containers/Condition/Condition.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, ok-to-test, size/S
