Repository tektoncd/dashboard, pull requests merged in 2020-06, with the labels that each got.

#1400 Add more variations in e2e tests
  cmd/dashboard/main.go
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#1452 Fix the validation of PipelineResources in CreateTaskRun
  src/containers/CreateTaskRun/CreateTaskRun.js
Labels: approved, lgtm, size/S

#1456 Publish @tektoncd/dashboard-components@0.0.1-alpha.48
  lerna.json
Labels: approved, lgtm, size/XS

#1449 Add `tkn--` prefix to remaining styles and fix some inconsistencies
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/KeyValueList/KeyValueList.js
  packages/components/src/components/KeyValueList/KeyValueList.scss
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/ResourceTable/ResourceTable.js
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/Spinner/Spinner.scss
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.scss
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.scss
  src/components/CreateSecret/CreateSecret.scss
  src/components/CreateSecret/Form/Annotations.js
  src/components/CreateSecret/Form/UniversalFields.js
  src/components/CreateSecret/Form/index.js
  src/components/CreateSecret/ServiceAccountSelector.js
  src/components/Definitions/Definitions.scss
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.scss
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.scss
  src/containers/Pipelines/Pipelines.js
  src/containers/Secret/Secret.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/scss/CreateRun.scss
  src/scss/Triggers.scss
Labels: approved, lgtm, size/XL

#1455 change PipelineResourcesModal to CreatePipelineResources
  src/containers/CreatePipelineResources/CreatePipelineResources.js
  src/containers/CreatePipelineResources/CreatePipelineResources.test.js
  src/containers/CreatePipelineResources/CreatePipelineResourcesErrorNotification.test.js
  src/containers/CreatePipelineResources/index.js
  src/containers/PipelineResources/PipelineResources.js
Labels: approved, lgtm, size/XS

#1459 Fix character encoding of displayed Secrets username column
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
Labels: approved, lgtm, size/S

#1457 Update some dev dependencies (npm audit)
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#1458 Add plumbing for displaying Conditions
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/actions/conditions.js
  src/actions/conditions.test.js
  src/api/index.js
  src/api/index.test.js
  src/reducers/conditions.js
  src/reducers/conditions.test.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/L

#1463 add retries in place for already sorted taskRuns
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/S

#1448 Add VAR GOARCH in Dockerfile
  DEVELOPMENT.md
  Dockerfile
Labels: approved, lgtm, size/S

#1464 Add LoadingShell component to display while loading configuration
  packages/components/src/components/LoadingShell/LoadingShell.js
  packages/components/src/components/LoadingShell/LoadingShell.scss
  packages/components/src/components/LoadingShell/LoadingShell.stories.js
  packages/components/src/components/LoadingShell/index.js
  packages/components/src/components/index.js
  src/components/App/App.scss
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1461 Update to Carbon 10.12
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/components/LabelFilter/LabelFilter.scss
Labels: approved, lgtm, size/L

#1466 Update Storybook and pin Carbon
  .storybook/tekton-horizontal-color.svg
  .storybook/theme.js
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#1469 Remove extra characters at end of import resources tooltip
  src/containers/ImportResources/ImportResources.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XS

#1467 Switch CustomResourceDefinition component to the new common details layout
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1468 Remove Sanitizing Secret debug message
  pkg/utils/utils.go
Labels: approved, lgtm, size/XS

#1465 Add Conditions to the left nav
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  packages/components/src/components/ResourceDetails/ResourceDetails.test.js
  packages/components/src/components/Table/Table.js
  src/containers/App/App.js
  src/containers/Condition/Condition.js
  src/containers/Condition/Condition.test.js
  src/containers/Condition/index.js
  src/containers/Conditions/Conditions.js
  src/containers/Conditions/Conditions.test.js
  src/containers/Conditions/index.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/containers/index.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XL

#1450 Add support for node selectors in create task/pipeline runs
  src/api/index.js
  src/api/index.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/scss/CreateRun.scss
Labels: approved, lgtm, size/L

#1425 Add frontend support for single namespace visibility
  README.md
  cmd/dashboard/main.go
  overlays/dev-single-namespace/deployment-patch.yaml
  overlays/dev-single-namespace/kustomization.yaml
  packages/components/src/components/LogoutButton/LogoutButton.js
  pkg/controllers/controller.go
  pkg/controllers/kubernetes/extension.go
  pkg/testutils/testutils.go
  src/actions/extensions.js
  src/actions/extensions.test.js
  src/api/index.js
  src/components/CreateSecret/Form/UniversalFields.test.js
  src/components/CreateSecret/Form/index.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/CreatePipelineResources/CreatePipelineResources.test.js
  src/containers/CreatePipelineResources/CreatePipelineResourcesErrorNotification.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateSecret/CreateSecret.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/nls/messages_en.json
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/properties.js
  src/reducers/properties.test.js
Labels: approved, lgtm, size/XXL

#1454 Switch to go modules
  .dockerignore
  DEVELOPMENT.md
  Dockerfile
  Dockerfile_race_test
  Dockerfile_test
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  hack/tools.go
  install-dev.sh
  tekton/build.yml
  test/e2e-common.sh
  test/presubmit-tests.sh
  test/publish-images.sh
Labels: approved, lgtm, size/XXL

#1470 Add support for log level and log format flags
  README.md
  cmd/dashboard/main.go
  pkg/logging/logging.go
Labels: approved, lgtm, size/M

#1474 Merge duplicate strings
  src/components/CreateSecret/Form/Annotations.js
  src/components/CreateSecret/Form/UniversalFields.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/ImportResources/ImportResources.js
  src/containers/Secrets/Secrets.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1475 Remove references to extensions/deployments
  base/200-clusterrole-pipelines.yaml
  base/200-clusterrole-triggers.yaml
  docs/samples/extension/config/tekton-kubernetes-resource-extension-sample.yaml
  test/resources/static/service-account.yaml
Labels: approved, lgtm, size/XS

#1479 Comment out docs frontmatter
  docs/README.md
Labels: approved, lgtm, size/XS

#1471 Migrate existing use of Tabs on details pages to ResourceDetails component
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.test.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
  src/nls/messages_en.json
  src/scss/Triggers.scss
Labels: approved, lgtm, size/XXL

#1453 Add security context to ensure dashboard runs as non root
  base/300-deployment.yaml
  overlays/openshift-patches/oauth-proxy-in-deployment.yaml
Labels: approved, lgtm, size/XS

#1486 Cleanup use of extend-expect
  config_frontend/setupTests.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/EventListener/EventListener.test.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/Secret/Secret.test.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
Labels: approved, lgtm, size/S

#1477 Separate bug report and feature request templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
Labels: approved, lgtm, size/L

#1489 Remove unnecessary use of redux in tests
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/Secret/Secret.test.js
Labels: approved, lgtm, size/L

#1487 Add extensions doc
  docs/extensions-resource-based-rbac.png
  docs/extensions-service-based-backend.png
  docs/extensions-service-based-frontend.png
  docs/extensions.md
Labels: approved, lgtm, size/L

#1492 Fix pipelines and triggers rbac issue
  base/201-clusterrolebinding-pipelines.yaml
  base/201-clusterrolebinding-triggers.yaml
  base/kustomization.yaml
Labels: approved, lgtm, size/S

#1478 Add install doc
  docs/install.md
Labels: approved, lgtm, size/L

#1496 Remove unused peerDep from utils package
  package-lock.json
  packages/utils/package.json
Labels: approved, lgtm, size/XL

#1493 Show loading spinner only at startup
  src/containers/App/App.js
Labels: approved, lgtm, size/S

#1497 Remove obsolete/unused files
  Dockerfile_race_test
  Dockerfile_test
  install-dev.sh
  testdata/ordering/pipeline.yaml
  testdata/ordering/pipelinerun.yaml
  testdata/ordering/tasks.yaml
  testdata/web/index.html
Labels: approved, lgtm, size/L

#1501 Ensure checks for retriesStatus are null-safe
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/XS

#1500 Remove jest-dom
  config_frontend/setupTests.js
  package-lock.json
  package.json
  src/containers/TriggerTemplate/TriggerTemplate.test.js
Labels: approved, lgtm, size/L

#1502 Ensure columns on About page are aligned across tables
  src/containers/About/About.js
  src/containers/About/About.scss
Labels: approved, lgtm, size/S

#1476 Rework main README
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  docs/README.md
  docs/dashboard-ui.png
  roadmap.md
Labels: approved, lgtm, size/L

#1504 Fix extensions overview link
  README.md
Labels: approved, lgtm, size/XS

#1480 Add a doc walkthrough to setup everything from scratch with kind
  docs/walkthrough-kind-import.png
  docs/walkthrough-kind-pipelineruns.png
  docs/walkthrough-kind.md
Labels: approved, lgtm, size/L

#1515 Fix openshift kustomize overlays
  overlays/openshift-patches/flags-deployment.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1510 Check message bundles are in sync with code as part of pre-submit tests
  src/nls/messages_en.json
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#1511 Update jest
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#1516 Fix release pipeline
  tekton/build.yml
Labels: approved, lgtm, size/XS

#1517 Update dependencies
  package-lock.json
  package.json
  packages/components/src/components/Graph/ZoomablePipelineGraph.js
  packages/components/src/components/Table/Table.js
  src/actions/eventListeners.test.js
  src/actions/pipelineResources.test.js
  src/actions/serviceAccounts.test.js
  src/actions/triggerBindings.test.js
  src/actions/triggerTemplates.test.js
  src/components/CreateSecret/ServiceAccountSelector.js
  src/components/PipelineResourcesModal/UniversalFields.js
  src/containers/About/About.js
  src/containers/App/App.js
  src/containers/CreatePipelineResources/CreatePipelineResources.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/SideNav/SideNav.js
  src/containers/Tasks/Tasks.js
  src/containers/index.js
Labels: approved, lgtm, size/XXL

#1484 Add a doc walkthrough to setup oauth2 proxy and secure ingress
  README.md
  docs/walkthrough/README.md
  docs/walkthrough/walkthrough-kind-import.png
  docs/walkthrough/walkthrough-kind-pipelineruns.png
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-oauth2-proxy-github.png
  docs/walkthrough/walkthrough-oauth2-proxy-overview.png
  docs/walkthrough/walkthrough-oauth2-proxy-register.png
  docs/walkthrough/walkthrough-oauth2-proxy-registered.png
  docs/walkthrough/walkthrough-oauth2-proxy-sign-in.png
  docs/walkthrough/walkthrough-oauth2-proxy.md
Labels: approved, lgtm, size/L

#1521 Fix table layout for Triggers
  src/scss/Triggers.scss
Labels: approved, lgtm, size/S

#1522 Remove unused files (part 2)
  minishift-delete-dashboard.sh
  minishift-install-dashboard.sh
Labels: approved, lgtm, size/M

#1524 Ensure consistent behaviour across node versions
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/utils/index.js
Labels: approved, lgtm, size/S

#1508 Support running e2e tests locally with kind
  .gitignore
  test/e2e-common.sh
  test/e2e-tests.sh
  test/local-e2e-tests.sh
Labels: approved, lgtm, size/L

#1514 Improve Extension CRD and add client code generation
  .gitignore
  base/202-extension-crd.yaml
  cmd/dashboard/main.go
  go.mod
  go.sum
  hack/boilerplate/boilerplate.go.txt
  hack/generate-groups.sh
  hack/tools.go
  hack/update-codegen.sh
  hack/update-deps.sh
  pkg/apis/dashboard/register.go
  pkg/apis/dashboard/v1alpha1/doc.go
  pkg/apis/dashboard/v1alpha1/extension_types.go
  pkg/apis/dashboard/v1alpha1/register.go
  pkg/apis/dashboard/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/dashboard_client.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/extension.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/fake/fake_dashboard_client.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/fake/fake_extension.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/dashboard/interface.go
  pkg/client/informers/externalversions/dashboard/v1alpha1/extension.go
  pkg/client/informers/externalversions/dashboard/v1alpha1/interface.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/listers/dashboard/v1alpha1/expansion_generated.go
  pkg/client/listers/dashboard/v1alpha1/extension.go
  pkg/controllers/controller.go
  pkg/controllers/dashboard/extension.go
  pkg/endpoints/types.go
Labels: approved, lgtm, size/XXL

#1525 Update docs to point to 0.7.0
  README.md
  docs/install.md
Labels: approved, lgtm, size/XS

#1520 Rework dev docs
  docs/dev/README.md
  docs/dev/api.md
Labels: approved, lgtm, size/L

#1494 Add installer script for local dev
  overlays/installer/base/flags.yaml
  overlays/installer/base/kustomization.yaml
  overlays/installer/k8s/base/kustomization.yaml
  overlays/installer/k8s/read-only/kustomization.yaml
  overlays/installer/k8s/read-write/kustomization.yaml
  overlays/installer/openshift/base/kustomization.yaml
  overlays/installer/openshift/read-only/kustomization.yaml
  overlays/installer/openshift/read-write/kustomization.yaml
  scripts/installer
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/XL

#1528 Update to Node.js 12 (current LTS)
  Dockerfile
  docs/dev/README.md
  package.json
  packages/components/package.json
  packages/utils/package.json
  tekton/build.yml
  test/presubmit-tests.sh
  test/publish-images.sh
Labels: approved, lgtm, size/M

#1527 Write frontend build output directly to KO_DATA_PATH
  DEVELOPMENT.md
  base/300-deployment.yaml
  package.json
Labels: approved, lgtm, size/XS

#1530 Fix gitignore dashboard binary rule
  .gitignore
Labels: approved, lgtm, size/XS

#1531 Add installer doc
  docs/dev/README.md
  docs/dev/installer.md
Labels: approved, lgtm, size/L

#1519 Add extensions frontend notification support
  pkg/broadcaster/broadcaster.go
  pkg/controllers/dashboard/extension.go
  pkg/controllers/kubernetes/extension.go
  pkg/endpoints/websocket_test.go
  pkg/router/router.go
  src/reducers/extensions.js
  src/reducers/extensions.test.js
Labels: approved, lgtm, size/L

#1529 Adapt test script to easily test with another pipelines version
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#1533 Update eventlistener bindings to use 'ref' instead of 'name'
  README.md
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.test.js
  src/containers/EventListener/EventListener.test.js
Labels: approved, lgtm, size/S

#1535 Fix path resolution in service-based extension sample
  docs/extensions.md
Labels: approved, lgtm, size/XS

#1539 Install triggers in the test cluster
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#1540 Add doc on running integration tests locally
  docs/dev/README.md
Labels: approved, lgtm, size/M

#1532 Add postman tests
  test/e2e-tests.sh
  test/postman/Dashboard.postman_collection.json
  test/postman/Pipelines.postman_collection.json
  test/postman/Triggers.postman_collection.json
  test/postman/globals.json
Labels: approved, lgtm, size/XL

#1536 Add prepare-kind-cluster script to spin a local cluster ready to use
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/M

#1543 Remove incorrect jest config
  jest.config.js
Labels: approved, lgtm, size/XS

#1544 Remove unused styles for code blocks
  packages/components/src/components/StepDefinition/StepDefinition.scss
  packages/components/src/components/StepStatus/StepStatus.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.scss
Labels: approved, lgtm, size/M

#1541 Fix intermittent error loading PipelineResource details page
  src/containers/PipelineResource/PipelineResource.js
Labels: approved, lgtm, size/XS

#1542 Fix styles on Import Resources page
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1545 Improve consistency of table styles
  packages/components/src/components/ResourceTable/ResourceTable.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/Trigger/Trigger.js
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/Secret/Secret.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/scss/Triggers.scss
Labels: approved, lgtm, size/L

#1547 Minor style tweaks to be more consistent with Carbon guidelines
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/Step/Step.scss
  packages/components/src/components/Task/Task.scss
  packages/components/src/scss/Run.scss
Labels: approved, lgtm, size/S

#1548 Remove unnecessary margin on table noRows element
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/XS

#1546 Add Tekton cat to the about page
  src/containers/About/About.js
  src/containers/About/About.scss
  src/images/tekton-stacked-color.svg
Labels: approved, lgtm, size/L

#1553 Fix storybook stories
  packages/components/src/components/CancelButton/CancelButton.js
  packages/components/src/components/CancelButton/CancelButton.scss
  packages/components/src/components/CancelButton/CancelButton.stories.js
  packages/components/src/components/CancelButton/CancelButton.test.js
  packages/components/src/components/CancelButton/index.js
  packages/components/src/components/Trigger/Trigger.stories.js
  packages/components/src/components/index.js
  src/containers/EventListener/EventListener.stories.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1554 Update webpack loaders in preparation for webpack@5
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#1556 Update eslint and prettier
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  packages/utils/src/utils/buildGraphData.js
  packages/utils/src/utils/index.js
  src/containers/TriggerTemplate/TriggerTemplate.js
Labels: approved, lgtm, size/XL

#1555 Fix intermittent error loading rerun PipelineRun
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, size/XS

#1557 Update react-intl and supporting packages to latest versions
  package-lock.json
  package.json
  packages/components/package.json
Labels: approved, lgtm, size/XXL

#1559 Update PipelineRun story to provide clear separation from the background
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
Labels: approved, lgtm, size/S

#1562 Remove `iconDescription` prop from `AccordionItem` on Import Resources page
  src/containers/ImportResources/ImportResources.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/XS

#1558 Switch from Delete16 icon (deprecated) to TrashCan32
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/Table/Table.stories.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/Secrets/Secrets.js
Labels: approved, lgtm, size/S

#1560 Fix links to ClusterTriggerBindings from EventListener page
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.test.js
Labels: approved, lgtm, size/S

#1561 Preserve line breaks when rendering multiline params
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/WithLineBreaks/WithLineBreaks.scss
  packages/components/src/components/WithLineBreaks/index.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/M

#1565 Fix babel config to enable tree shaking
  babel.config.js
Labels: approved, lgtm, size/XS

#1563 Remove unnecessary use of `createIntl` in tests
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  src/containers/Secrets/Secrets.test.js
Labels: approved, lgtm, size/M

#1566 Update Import Resources to reference path instead of directory
  src/containers/ImportResources/ImportResources.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1569 Remove unused const
  pkg/router/router.go
Labels: approved, lgtm, size/XS

#1568 Add additionalPrinterColumns on extension CRD
  base/202-extension-crd.yaml
Labels: approved, lgtm, size/S

#1572 Move the selected step and task from PipelineRun state to props
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/L

#1575 Remove unused logs API
  pkg/endpoints/pipeline.go
  pkg/endpoints/pipeline_test.go
  pkg/router/router.go
  pkg/router/routes_test.go
Labels: approved, lgtm, size/L

#1579 Fix display of array params
  packages/components/src/components/Param/Param.scss
  packages/components/src/components/Param/index.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.scss
  packages/components/src/components/ViewYAML/ViewYAML.js
  packages/components/src/components/index.js
Labels: approved, lgtm, size/M
