Repository tektoncd/dashboard, pull requests merged in 2020-05, with the labels that each got.

#1338 Bump plumbing to recent master 👼
  Gopkg.lock
Labels: approved, lgtm, size/XS

#1334 Move CreateSecret to URL addressable page
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/App/App.js
  src/containers/CreateSecret/CreateSecret.js
  src/containers/CreateSecret/CreateSecret.test.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/containers/index.js
Labels: approved, lgtm, size/XL

#1339 Fix key prop warning on DataTableSkeleton
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.js
Labels: approved, lgtm, size/XS

#1341 Update browser title so history is more useful
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/About/About.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/CreateSecret/CreateSecret.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Extension/Extension.js
  src/containers/Extensions/Extensions.js
  src/containers/ImportResources/ImportResources.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Secret/Secret.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccount/ServiceAccount.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/SideNav/SideNav.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#1327 Add recommended k8s labels
  base/200-clusterrole.yaml
  base/201-clusterrolebinding.yaml
  base/202-extension-crd.yaml
  base/203-serviceaccount.yaml
  base/300-deployment.yaml
  base/300-service.yaml
Labels: approved, lgtm, size/M

#1343 Use getInstallProperties for displaying logout
  src/api/index.js
Labels: approved, lgtm, size/XS

#1352 Switch to ko-gcloud for release
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#1348 Decouple logout button and openshift
  packages/components/src/components/Header/Header.stories.js
  packages/components/src/components/LogoutButton/LogoutButton.js
  packages/components/src/components/LogoutButton/LogoutButton.test.js
  pkg/endpoints/cluster.go
  src/api/index.js
  src/containers/App/App.js
Labels: approved, lgtm, size/M

#1353 Add guard against missing namespace in SecretDeleted handler
  src/reducers/secrets.js
Labels: approved, lgtm, size/XS

#1351 Add CSRF protection
  Gopkg.lock
  Gopkg.toml
  base/300-deployment.yaml
  cmd/dashboard/main.go
  overlays/dev-locked-down/kustomization.yaml
  overlays/dev-openshift-imagestream/kustomization.yaml
  overlays/dev-openshift-locked-down/kustomization.yaml
  overlays/dev-openshift/kustomization.yaml
  overlays/dev/csrf-secure-cookie-patch.yaml
  overlays/dev/kustomization.yaml
  pkg/endpoints/cluster.go
  pkg/router/router.go
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.test.js
  src/utils/test.js
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#1361 Refactor controllers to reduce code duplication
  pkg/broadcaster/broadcaster.go
  pkg/controllers/kubernetes/extension.go
  pkg/controllers/kubernetes/namespaces.go
  pkg/controllers/kubernetes/secret.go
  pkg/controllers/kubernetes/serviceAccount.go
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/controllers/utils/controller.go
Labels: approved, lgtm, size/XL

#1359 Split dashboard, pipelines and triggers infos in About page
  DEVELOPMENT.md
  base/300-deployment.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  src/api/index.js
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L

#1368 Filter resources before returning to the client
  base/200-clusterrole.yaml
  overlays/full-fat/cluster-role-patch-json.yaml
  pkg/controllers/kubernetes/extension.go
  pkg/controllers/kubernetes/namespaces.go
  pkg/controllers/kubernetes/secret.go
  pkg/controllers/kubernetes/serviceAccount.go
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/controllers/utils/controller.go
  pkg/controllers/utils/utils.go
  pkg/endpoints/cluster.go
  pkg/utils/utils.go
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/L

#1366 Add roadmap doc
  roadmap.md
Labels: approved, lgtm, size/M

#1342 Use ClusterRole aggregation for standalone extensions
  DEVELOPMENT.md
  base/200-clusterrole.yaml
  docs/samples/extension/README.md
  docs/samples/extension/config/tekton-kubernetes-resource-extension-sample.yaml
  overlays/full-fat/kustomization.yaml
Labels: approved, lgtm, size/M

#1376 Fix API root for token
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.js
  src/api/index.test.js
  src/utils/test.js
Labels: approved, lgtm, size/M

#1379 Point folks to 0.6.1.2 security release
  README.md
Labels: approved, lgtm, size/XS

#1380 Update latest release to v0.6.1.2
  README.md
Labels: approved, lgtm, size/XS

#1382 Filter metadata before returning resource to the client
  pkg/utils/utils.go
Labels: approved, lgtm, size/S

#1383 Update latest release to v0.6.1.3, deprecate older releases
  README.md
Labels: approved, lgtm, size/XS

#1381 Fix clearing x on create taskrun breaks page
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
Labels: approved, lgtm, size/M

#1336 Add OpenShift support for release pipeline
  tekton/README.md
  tekton/openshift/publish.yaml
  tekton/resources.yaml
Labels: approved, lgtm, size/L

#1378 Disable Secrets and ServiceAccounts routes in read-only mode
  src/containers/App/App.js
Labels: approved, lgtm, size/M

#1369 Update to Carbon 10.11
  package-lock.json
  package.json
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LabelFilter/LabelFilter.scss
  src/containers/CreateSecret/CreateSecret.test.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/L

#1370 Use install properties to check if triggers is installed
  src/containers/App/App.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/properties.js
  src/reducers/properties.test.js
Labels: approved, lgtm, size/M

#1390 Refer to 0.6.1.4 and advise on CSRF setting false for port-forward
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/XS

#1364 Replace env variables with flags
  .gitignore
  Dockerfile
  Dockerfile_race_test
  Dockerfile_test
  base/300-deployment.yaml
  cmd/dashboard/main.go
  overlays/dev-locked-down/kustomization.yaml
  overlays/dev-openshift-imagestream/kustomization.yaml
  overlays/dev-openshift-locked-down/kustomization.yaml
  overlays/dev-openshift/kustomization.yaml
  overlays/dev/csrf-secure-cookie-patch.yaml
  overlays/dev/kustomization.yaml
  overlays/latest-locked-down/kustomization.yaml
  overlays/latest-openshift-locked-down/kustomization.yaml
  overlays/latest-openshift/kustomization.yaml
  overlays/openshift-patches/oauth-proxy-in-deployment.yaml
  overlays/readonly/readonly-deployment-patch.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  pkg/endpoints/types.go
  pkg/router/router.go
Labels: approved, lgtm, size/L

#1393 Change how we disable the Secrets and ServiceAccounts UI routes
  src/containers/App/App.js
  src/containers/ReadWriteRoute/ReadWriteRoute.js
  src/containers/ReadWriteRoute/index.js
  src/containers/index.js
Labels: approved, lgtm, size/L

#1399 Detect new deployment formats for pipeline and triggers
  pkg/endpoints/dashboard.go
Labels: approved, lgtm, size/M

#1396 Use separate service account in e2e test
  base/200-clusterrole.yaml
  overlays/full-fat/cluster-role-patch-json.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/resources/static/service-account.yaml
Labels: approved, lgtm, size/L

#1398 Add pipelines and triggers namespace flags
  cmd/dashboard/main.go
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  pkg/endpoints/types.go
Labels: approved, lgtm, size/L

#1402 Improve help message
  cmd/dashboard/main.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/resources/static/service-account.yaml
Labels: approved, lgtm, size/M

#1407 Do not watch secrets and service accounts when read-only
  cmd/dashboard/main.go
  pkg/controllers/controller.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, size/S

#1397 Clear createpipelinerun when x is pressed on pipeline
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/M

#1401 Remove useless struct
  cmd/dashboard/main.go
Labels: approved, lgtm, size/S

#1403 Add doc note for disabling CSRF secure cookie from the command line
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#1394 Sort steps by timestamps
  packages/components/src/components/TaskTree/TaskTree.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: approved, lgtm, ok-to-test, size/L

#1408 Add supported flags doc
  README.md
Labels: approved, lgtm, size/S

#1389 Update docs frontmatter for website edit links
  docs/README.md
Labels: approved, lgtm, size/XS

#1410 Remove query string from page location when constructing API root
  src/api/comms.js
Labels: approved, lgtm, size/XS

#1426 Add flag for logout url
  README.md
  cmd/dashboard/main.go
  overlays/dev-openshift-imagestream/kustomization.yaml
  overlays/dev-openshift-locked-down/kustomization.yaml
  overlays/dev-openshift/kustomization.yaml
  overlays/latest-openshift-locked-down/kustomization.yaml
  overlays/latest-openshift/kustomization.yaml
  overlays/logout/deployment-patch.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/types.go
Labels: approved, lgtm, size/M

#1391 Ensure strings in ImportResources are extracted for translation
  src/components/PipelineResourcesModal/UniversalFields.js
  src/containers/App/App.js
  src/containers/ImportResources/ImportResources.js
  src/nls/messages_en.json
  webpack.common.js
Labels: approved, lgtm, size/L

#1422 Add eddycharly to OWNERS as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#1429 Use the redux store to get the logout url and dashboard namespace
  packages/components/src/components/LogoutButton/LogoutButton.js
  src/api/index.js
  src/containers/App/App.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/properties.js
  src/reducers/properties.test.js
Labels: approved, lgtm, size/L

#1415 Update Create PipelineRun and Create TaskRun dialog behaviour
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
Labels: approved, lgtm, size/XL

#1431 Update labelSelector for ClusterTask TaskRuns
  packages/components/src/components/LogoutButton/LogoutButton.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
Labels: approved, lgtm, size/M

#1433 Stop creation of non-existent Pipelines being used in PipelineRuns
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
Labels: approved, lgtm, size/S

#1441 Stop creation of non-existent Tasks being used in TaskRuns
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
Labels: approved, lgtm, size/S

#1436 Namespace should not be translated
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Secrets/Secrets.js
  src/containers/ServiceAccounts/ServiceAccounts.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1435 Add missing test for fetchResource actionCreator
  src/actions/actionCreators.test.js
Labels: approved, lgtm, size/L

#1440 Add missing tests for actions
  src/actions/clusterTriggerBindings.test.js
  src/actions/properties.test.js
  src/actions/secrets.js
  src/actions/secrets.test.js
Labels: approved, lgtm, size/L

#1434 Resolve prop warning from HeaderGlobalAction
  packages/components/src/components/LogoutButton/LogoutButton.js
Labels: approved, lgtm, size/S

#1430 Use the redux store to get about informations
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/properties.js
  src/reducers/properties.test.js
Labels: approved, lgtm, size/L

#1439 Add rendering for retried taskRuns
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1442 Add missing Carbon strings for listbox components
  packages/components/src/components/TooltipDropdown/TooltipDropdown.js
  packages/utils/src/utils/index.js
  src/components/CreateSecret/Form/Annotations.js
  src/components/PipelineResourcesModal/UniversalFields.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/M

#1447 Add missing strings
  packages/components/src/components/CancelButton/CancelButton.js
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/Modal/Modal.js
  packages/components/src/components/Modal/index.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/Rerun/Rerun.test.js
  packages/components/src/components/RunDropdown/RunDropdown.js
  packages/components/src/components/index.js
  src/components/CreateSecret/Form/AccessTokenType.js
  src/components/CreateSecret/Form/PasswordType.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/containers/About/About.js
  src/containers/App/App.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/ImportResources/ImportResources.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesModal/PipelineResourcesModal.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L
