Repository tektoncd/dashboard, pull requests merged in 2021-06, with the labels that each got.

#2074 Rename renderWithIntl to render
  packages/components/src/components/DetailsHeader/DetailsHeader.test.js
  packages/components/src/components/ErrorBoundary/ErrorBoundary.test.js
  packages/components/src/components/FormattedDate/FormattedDate.test.js
  packages/components/src/components/FormattedDuration/FormattedDuration.test.js
  packages/components/src/components/KeyValueList/KeyValueList.test.js
  packages/components/src/components/LabelFilter/LabelFilter.test.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/LogFormat/LogFormat.test.js
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  packages/components/src/components/ResourceDetails/ResourceDetails.test.js
  packages/components/src/components/RunDropdown/RunDropdown.test.js
  packages/components/src/components/Step/Step.test.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/StepStatus/StepStatus.test.js
  packages/components/src/components/Table/Table.test.js
  packages/components/src/components/Task/Task.test.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  packages/components/src/components/TaskTree/TaskTree.test.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.test.js
  packages/components/src/utils/test.js
  src/containers/About/About.test.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/Condition/Condition.test.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TasksDropdown/TasksDropdown.test.js
  src/containers/Trigger/Trigger.test.js
Labels: approved, lgtm, size/XL

#2073 Update websocket payload format
  pkg/broadcaster/broadcaster.go
  pkg/controllers/dashboard/extension.go
  pkg/controllers/kubernetes/extension.go
  pkg/controllers/kubernetes/namespaces.go
  pkg/controllers/kubernetes/serviceAccount.go
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/condition.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/controllers/triggers/clusterInterceptor.go
  pkg/controllers/triggers/clusterTriggerBinding.go
  pkg/controllers/triggers/eventListener.go
  pkg/controllers/triggers/trigger.go
  pkg/controllers/triggers/triggerBinding.go
  pkg/controllers/triggers/triggerTemplate.go
  pkg/controllers/utils/controller.go
  pkg/endpoints/websocket_test.go
  pkg/testutils/testutils.go
  src/store/middleware.js
Labels: approved, lgtm, size/L

#2078 Update SCSS imports to follow guidance from the sass-loader
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.scss
  packages/components/src/components/RunHeader/RunHeader.scss
  src/scss/App.scss
  src/scss/_carbon.scss
Labels: approved, lgtm, size/L

#2077 Set component-level dark mode for Logs
  packages/components/src/components/Log/Log.scss
  src/scss/App.scss
Labels: approved, lgtm, size/S

#2080 Address lint warnings and remove unused code
  cmd/dashboard/main.go
  pkg/broadcaster/broadcaster.go
  pkg/csrf/csrf.go
  pkg/endpoints/cluster.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, size/M

#2081 Fix installer script with extensions rbac flag
  scripts/installer
Labels: approved, lgtm, size/XS

#2084 Update DataTableSkeleton to support `size` prop
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.js
  packages/components/src/components/DataTableSkeleton/DataTableSkeleton.stories.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/index.js
Labels: approved, lgtm, size/M

#2071 Add syntax highlight to ViewYAML component
  package-lock.json
  packages/components/package.json
  packages/components/src/components/ViewYAML/ViewYAML.js
  packages/components/src/components/ViewYAML/ViewYAML.scss
  packages/components/src/components/ViewYAML/ViewYAML.test.js
Labels: approved, lgtm, ok-to-test, size/M

#2088 Expand ViewYAML to the full width of container
  packages/components/src/components/ViewYAML/ViewYAML.scss
Labels: approved, lgtm, ok-to-test, size/XS

#2082 Add hook to keep page title in sync with displayed resource(s)
  packages/utils/src/utils/hooks.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/containers/About/About.js
  src/containers/ClusterInterceptors/ClusterInterceptors.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/Condition/Condition.js
  src/containers/Conditions/Conditions.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Extension/Extension.js
  src/containers/Extensions/Extensions.js
  src/containers/ImportResources/ImportResources.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/Trigger/Trigger.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/Triggers/Triggers.js
Labels: approved, lgtm, size/L

#2085 Add initial react-query utilities
  package-lock.json
  package.json
  packages/components/src/utils/test.js
  src/api/utils.js
  src/api/utils.test.js
  src/utils/test.js
Labels: approved, lgtm, size/L

#2090 add configmap which can contain dashboard info and RBAC to access this configmap
  base/200-role.yaml
  base/201-rolebinding.yaml
  base/config-info.yaml
  tekton/publish.yaml
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#2096 Document the `prepare-kind-cluster` script
  docs/dev/README.md
Labels: approved, lgtm, size/S

#2097 Fix table batch action checkbox column styles
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/S

#2099 Add briangleeson as an approver
  OWNERS
Labels: approved, lgtm, size/XS

#2095 Move more resources to react-query
  src/actions/conditions.js
  src/actions/conditions.test.js
  src/actions/pipelineResources.js
  src/actions/pipelineResources.test.js
  src/actions/serviceAccounts.js
  src/actions/serviceAccounts.test.js
  src/api/conditions.js
  src/api/conditions.test.js
  src/api/pipelineResources.js
  src/api/pipelineResources.test.js
  src/api/serviceAccounts.js
  src/api/serviceAccounts.test.js
  src/containers/App/App.test.js
  src/containers/Condition/Condition.js
  src/containers/Condition/Condition.test.js
  src/containers/Conditions/Conditions.js
  src/containers/Conditions/Conditions.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/Extension/actions.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/reducers/conditions.js
  src/reducers/conditions.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/pipelineResources.js
  src/reducers/pipelineResources.test.js
  src/reducers/reducerCreators.js
  src/reducers/reducerCreators.test.js
  src/reducers/serviceAccounts.js
  src/reducers/serviceAccounts.test.js
Labels: approved, lgtm, size/XXL

#2098 Update style of links in tables to match Carbon guidelines
  packages/components/src/components/PipelineResources/PipelineResources.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/Trigger/Trigger.js
  src/containers/ClusterInterceptors/ClusterInterceptors.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/Conditions/Conditions.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Extensions/Extensions.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/Triggers/Triggers.js
Labels: approved, lgtm, size/M

#2104 Restrict X-Frame-Options header with new flag
  cmd/dashboard/main.go
  pkg/endpoints/types.go
  pkg/router/router.go
  pkg/router/routes_test.go
Labels: approved, lgtm, ok-to-test, size/M
