Repository tektoncd/dashboard, pull requests merged in 2021-04, with the labels that each got.

#1995 Add 'Last updated' label to last updated timestamp on run header
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.test.js
  packages/components/src/components/RunHeader/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/M

#1993 Simplify version checks in back end
  cmd/dashboard/main.go
  docs/dev/api.md
  overlays/patches/installer/deployment-patch.yaml
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
  pkg/endpoints/types.go
  scripts/installer
  src/containers/About/About.js
  src/containers/About/About.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/properties.js
  src/reducers/properties.test.js
  test/postman/Dashboard.postman_collection.json
  test/postman/globals.json
Labels: approved, lgtm, size/L

#1996 Update order of actions on TaskRuns and PipelineRuns
  packages/components/src/components/RunDropdown/RunDropdown.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/M

#1991 Update to latest Carbon release
  package-lock.json
  package.json
  packages/components/package.json
Labels: approved, lgtm, size/S

#1997 Use small Tag variant on ResourceDetails labels
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  src/scss/Triggers.scss
Labels: approved, lgtm, size/XS

#1998 Publish @tektoncd/dashboard-components 0.0.1-alpha.69
  lerna.json
Labels: approved, lgtm, size/XS

#1999 Update to latest Storybook release
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#2001 Add temporary workaround for Storybook production build
  package-lock.json
Labels: approved, lgtm, size/XS

#2002 Publish @tektoncd/dashboard-components 0.0.1-alpha.70
  lerna.json
Labels: approved, lgtm, size/XS

#2003 Add v0.16.0 doc links to readme
  README.md
Labels: approved, lgtm, size/XS

#2006 Resolve npm audit warnings
  package-lock.json
Labels: approved, lgtm, size/XS

#2005 Remove status label string on step display
  packages/components/src/components/Spinner/Spinner.js
  packages/components/src/components/Spinner/index.js
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/components/src/components/StatusIcon/StatusIcon.test.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.scss
Labels: approved, lgtm, size/L

#2004 Replace Carbon layout tokens with spacing
  packages/components/src/components/LoadingShell/LoadingShell.scss
  src/containers/EventListener/EventListener.scss
  src/scss/App.scss
  src/scss/Create.scss
  src/scss/Triggers.scss
Labels: approved, lgtm, size/S

#2008 Update plumbing dep to pin gke version
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#2009 Fix for SideNav not collapsing when toggling the menu button
  packages/components/src/components/LabelFilter/LabelFilter.js
  src/containers/App/App.js
Labels: approved, lgtm, size/XS

#2012 Refactor ClusterTasks and dropdown containers to be functional components
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTasks/index.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/ClusterTasksDropdown/index.js
  src/containers/NamespacesDropdown/index.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/index.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/index.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/index.js
  src/containers/TasksDropdown/TasksDropdown.js
  src/containers/TasksDropdown/index.js
Labels: approved, lgtm, size/XL

#2011 Add v0.16.1 release links to the readme
  README.md
Labels: approved, lgtm, size/XS
