Repository tektoncd/dashboard, pull requests merged in 2021-05, with the labels that each got.

#2014 Update webpack-dev-server proxy config
  .eslintrc.js
  webpack.dev.js
Labels: approved, lgtm, size/M

#2013 Add custom hook to refetch data when websocket reconnects
  package-lock.json
  package.json
  packages/utils/src/utils/hooks.js
  packages/utils/src/utils/hooks.test.js
  packages/utils/src/utils/index.js
  src/containers/ClusterInterceptors/ClusterInterceptors.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/Condition/Condition.js
  src/containers/Conditions/Conditions.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/EventListeners/EventListeners.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/containers/TasksDropdown/TasksDropdown.js
  src/containers/Trigger/Trigger.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/Triggers/Triggers.js
Labels: approved, lgtm, size/XXL

#2015 Update caniuse db for browserslist config
  package-lock.json
Labels: approved, lgtm, size/XS

#2018 Add experimental support for dark mode
  src/index.js
  src/scss/_carbon.scss
Labels: approved, lgtm, size/M

#2019 Remove noisy log on websocket error
  webpack.dev.js
Labels: approved, lgtm, size/XS

#2021 Publish @tektoncd/dashboard-components 0.0.1-alpha.71
  lerna.json
Labels: approved, lgtm, size/XS

#2022 Refactor Tasks container component to be functional component
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, ok-to-test, size/L

#2026 Fix runtime error after delete cluster task
  src/containers/ClusterTasks/ClusterTasks.js
Labels: approved, lgtm, ok-to-test, size/XS

#2029 Fix npm audit and dependabot warnings
  package-lock.json
  package.json
Labels: approved, lgtm, size/XS

#2027 Convert EventListener container to functional component
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.test.js
Labels: approved, lgtm, size/L

#2031 Refactor additional containers to be functional components
  src/containers/PipelineResource/index.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResources/index.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/index.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/XXL

#2032 Update PipelineRuns status filter to support PipelineRunPending
  packages/utils/src/utils/index.js
Labels: approved, lgtm, size/XS

#2033 Refactor PipelineRun container to functional component
  src/containers/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/L

#2034 Refactor Import Resources container to functional component
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
Labels: approved, lgtm, size/XL

#2039 Refactor TaskRuns to be functional component
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, ok-to-test, size/L

#2036 Refactor CreatePipelineResource to functional component
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreatePipelineResource/UniversalFields.js
  src/containers/CreatePipelineResource/index.js
Labels: approved, lgtm, size/L

#2037 Refactor 'create run' containers to functional components
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/ImportResources/ImportResources.js
Labels: approved, lgtm, size/XXL

#2038 Refactor TaskRun to functional component
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, size/L

#2040 Remove use of `data-testid` attribute in DOM
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/LogoutButton/LogoutButton.js
  packages/components/src/components/RunDropdown/RunDropdown.js
  packages/components/src/components/RunHeader/RunHeader.js
  packages/components/src/components/RunHeader/RunHeader.test.js
  src/containers/About/About.test.js
  src/containers/ClusterInterceptors/ClusterInterceptors.test.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.test.js
  src/containers/Conditions/Conditions.test.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/Extension/Extension.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
  src/containers/Triggers/Triggers.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#2041 Update to latest Pipelines and Triggers releases
  README.md
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#2043 Update plumbing dep to fix integration tests
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#2042 Add v0.17.0 release links to the readme
  README.md
Labels: approved, lgtm, size/XS

#2044 Update kind walkthrough
  docs/walkthrough/walkthrough-kind.md
Labels: approved, lgtm, size/S

#2051 Add Windows note to install readme
  docs/dev/README.md
Labels: approved, lgtm, size/XS

#2052 Fix build_ko script
  package.json
Labels: approved, lgtm, size/XS

#2056 Remove dropdown container components from the Storybook
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.stories.js
  src/containers/NamespacesDropdown/NamespacesDropdown.stories.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.stories.js
  src/containers/PipelinesDropdown/PipelinesDropdown.stories.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.stories.js
  src/containers/TasksDropdown/TasksDropdown.stories.js
Labels: approved, lgtm, ok-to-test, size/XL

#2053 Cleanup installer script
  scripts/installer
Labels: approved, lgtm, size/S

#2054 Remove reference to the webhooks-extension
  docs/extensions.md
Labels: approved, lgtm, size/XS

#2045 Update Ingress resources to stable version
  docs/install.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
  scripts/installer
Labels: approved, lgtm, size/M

#2046 Update dev script for creating a kind cluster with Tekton installed
  scripts/prepare-kind-cluster
Labels: approved, lgtm, size/M

#2055 Update SideNav to hide when collapsed
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
Labels: approved, lgtm, size/L

#2058 Fix compilation error in EventListenerContainer section in Storybook
  src/containers/EventListener/EventListener.stories.js
Labels: approved, lgtm, ok-to-test, size/XS

#2061 Add offset to min-height to prevent layout shift
  packages/components/src/components/LabelFilter/LabelFilter.scss
Labels: approved, lgtm, ok-to-test, size/XS

#2063 add LyndseyBu as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#2059 Remove the ClusterRole aggregation from the default manifests
  base/200-clusterrole-extensions.yaml
  docs/dev/installer.md
  docs/extensions.md
  overlays/installer/base/kustomization.yaml
  scripts/installer
Labels: approved, lgtm, size/L

#2076 2065_add spacing between spinner and text
  packages/components/src/components/LoadingShell/LoadingShell.scss
Labels: approved, lgtm, size/XS

#2075 2064 RunDropdown story update
  packages/components/src/components/RunDropdown/RunDropdown.stories.js
Labels: approved, lgtm, size/S
