Repository tektoncd/dashboard, pull requests merged in 2021-02, with the labels that each got.

#1926 Fix non-English strings
  src/nls/messages_de.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/M

#1917 Update OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#1927 Remove PluralRules polyfill
  package-lock.json
  package.json
  packages/components/package.json
  src/utils/polyfills.js
Labels: approved, lgtm, size/XS

#1928 Remove references to unused knative packages
  hack/update-deps.sh
Labels: approved, lgtm, size/XS

#1921 Add term.tsv for Japanese translation and modify messages_ja.json
  docs/dev/localization/Japanese/README.md
  docs/dev/localization/Japanese/term.tsv
  src/nls/messages_ja.json
Labels: approved, lgtm, ok-to-test, size/L

#1929 Remove ReadableStream polyfill
  config_frontend/setupTests.js
  package-lock.json
  package.json
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/Log/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#1932 Update links to community repo to reference main branch
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/S

#1935 Remove dependency on Tekton go clients
  cmd/dashboard/main.go
  go.mod
  go.sum
  pkg/controllers/controller.go
  pkg/controllers/tekton/clustertask.go
  pkg/controllers/tekton/condition.go
  pkg/controllers/tekton/pipeline.go
  pkg/controllers/tekton/pipelineresource.go
  pkg/controllers/tekton/pipelinerun.go
  pkg/controllers/tekton/task.go
  pkg/controllers/tekton/taskrun.go
  pkg/controllers/triggers/clusterTriggerBinding.go
  pkg/controllers/triggers/eventListener.go
  pkg/controllers/triggers/triggerBinding.go
  pkg/controllers/triggers/triggerTemplate.go
  pkg/endpoints/types.go
  pkg/endpoints/websocket_test.go
  pkg/router/routes_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, size/XL

#1934 Fix Storybook
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#1933 Remove StructuredListSkeleton
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/scss/App.scss
  src/scss/_carbon.scss
Labels: approved, lgtm, size/S

#1936 Add kustomize.yaml to the Tekton folder
  tekton/kustomization.yaml
Labels: approved, kind/misc, lgtm, size/XS

#1937 Add v0.14.0 release links to the readme
  README.md
Labels: approved, lgtm, size/XS

#1940 Use new Dashboard logo on the about page
  src/containers/About/About.js
  src/images/tekton-dashboard-color.svg
Labels: approved, lgtm, size/L

#1941 Update k8s dependencies
  go.mod
  go.sum
  pkg/apis/dashboard/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/dashboard_client.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/extension.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/fake/fake_dashboard_client.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/fake/fake_extension.go
  pkg/client/clientset/versioned/typed/dashboard/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/dashboard/interface.go
  pkg/client/informers/externalversions/dashboard/v1alpha1/extension.go
  pkg/client/informers/externalversions/dashboard/v1alpha1/interface.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/listers/dashboard/v1alpha1/expansion_generated.go
  pkg/client/listers/dashboard/v1alpha1/extension.go
  pkg/endpoints/dashboard.go
  pkg/endpoints/websocket_test.go
  pkg/router/routes_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, size/M

#1938 Kind walkthrough update
  docs/walkthrough/walkthrough-kind.md
Labels: approved, lgtm, ok-to-test, size/XS

#1947 Add Dashboard logo to readme
  README.md
Labels: approved, lgtm, size/XS

#1951 Simplify integration tests to focus on Dashboard functionality
  test/e2e-common.sh
  test/e2e-tests.sh
  test/local-e2e-tests.sh
  test/presubmit-tests.sh
  test/resources/envsubst/pipelineresource-git.yaml
  test/resources/envsubst/pipelineresource-image.yaml
  test/resources/envsubst/pipelinerun.yaml
  test/resources/static/Pipeline.yaml
  test/resources/static/deploy-task-insecure.yaml
  test/resources/static/kaniko-build-task.yaml
Labels: approved, lgtm, size/L

#1950 Fix the koparse URL in the publish job
  tekton/publish.yaml
Labels: approved, kind/misc, lgtm, size/XS

#1952 Update Pipelines and Triggers versions used in integration tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1946 Add error handling for PipelineRun cancel
  src/containers/PipelineRuns/PipelineRuns.js
Labels: approved, lgtm, ok-to-test, size/S

#1953 Update docs to reference updated dependency versions
  README.md
  docs/dev/README.md
  docs/install.md
Labels: approved, lgtm, size/XS

#1949 Add option to maximize logs container
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/LogsToolbar/LogsToolbar.js
  packages/components/src/components/LogsToolbar/LogsToolbar.stories.js
  packages/components/src/components/LogsToolbar/index.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Portal/index.js
  packages/components/src/components/index.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/App.scss
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1956 Fix EventListener details page when github interceptor has no eventTypes
  packages/components/src/components/Trigger/Trigger.js
  packages/components/src/components/Trigger/Trigger.test.js
Labels: approved, lgtm, size/S

#1955 display language according to the language setting
  config_frontend/config.json
  src/containers/App/App.js
Labels: approved, lgtm, ok-to-test, size/M
