Repository tektoncd/dashboard, pull requests merged in 2021-03, with the labels that each got.

#1957 Normalise stored locale and add support for dev override
  config_frontend/config.json
  docs/dev/README.md
  src/actions/locale.js
  src/actions/locale.test.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#1959 Update Storybook
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#1958 Add missing icon and styles for PipelineRunPending
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/RunHeader/RunHeader.scss
Labels: approved, lgtm, size/S

#1960 Publish @tektoncd/dashboard-components 0.0.1-alpha.68
  lerna.json
Labels: approved, lgtm, size/XS

#1964 Update references to `master` branch to use new name `main`
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/pull_request_template.md
  README.md
  docs/dev/README.md
  docs/extensions.md
  docs/install.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
  scripts/installer
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#1962 Enable Simplified Chinese translation
  config_frontend/config.json
  src/containers/App/App.js
Labels: approved, lgtm, size/XS

#1966 Fix references to robocat cluster
  docs/dev/README.md
Labels: approved, lgtm, size/XS

#1965 Add TaskRun results tab
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/TaskRunDetails/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/M

#1968 Fix display of EventListeners with null triggers field
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/M

#1967 Remove unnecessary tags for LogFormat component
  .gitignore
  packages/components/src/components/LogFormat/LogFormat.js
  packages/components/src/components/LogFormat/LogFormat.test.js
Labels: approved, lgtm, ok-to-test, size/M

#1973 Ensure consistent placement of error notifications on list pages
  src/containers/About/About.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/Conditions/Conditions.js
  src/containers/EventListeners/EventListeners.js
  src/containers/Extensions/Extensions.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ListPageLayout/ListPageLayout.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
Labels: approved, lgtm, size/XL

#1974 Update messages_ja.json & term.tsv
  docs/dev/localization/Japanese/term.tsv
  src/nls/messages_ja.json
Labels: approved, lgtm, ok-to-test, size/M

#1975 Update supported Tekton project versions
  README.md
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1976 Update references to Tekton projects to use new default branch name
  docs/dev/README.md
  docs/install.md
  docs/walkthrough/walkthrough-kind.md
  roadmap.md
Labels: approved, lgtm, size/S

#1977 Update `build:analyze` script to provide more accurate results
  .editorconfig
  package.json
Labels: approved, lgtm, size/XS

#1979 Support specifying git revision on import resources
  src/api/index.js
  src/api/index.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
  src/containers/ImportResources/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1983 Add v0.15.0 release links to readme
  README.md
Labels: approved, lgtm, size/XS

#1986 Extend e2e test script to run tests on non-Intel architectures
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#1985 Display parameters and results descriptions
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/StepDetails/index.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  src/containers/PipelineRun/index.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRun/index.js
Labels: approved, lgtm, size/L

#1984 Refactor containers to use hooks
  src/containers/About/About.js
  src/containers/About/index.js
  src/containers/App/App.js
  src/containers/Condition/Condition.js
  src/containers/Condition/Condition.test.js
  src/containers/Condition/index.js
  src/containers/Conditions/Conditions.js
  src/containers/Conditions/index.js
Labels: approved, lgtm, size/XXL

#1990 Add briangleeson as reviewer
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#1989 Remove obsolete test mock
  config_frontend/__mocks__/focus-trap.js
Labels: approved, lgtm, size/M

#1988 Fix table layout for TaskRun parameters and results
  packages/components/src/components/StepDetails/StepDetails.scss
  packages/components/src/components/TaskRunDetails/TaskRunDetails.scss
Labels: approved, lgtm, size/S

#1987 Update log fetching logic to ensure we poll one last time on transition to complete
  packages/components/src/components/Log/Log.js
Labels: approved, lgtm, size/M
