Repository tektoncd/dashboard, pull requests merged in 2021-07, with the labels that each got.

#2107 Add support for overriding the default log polling cut-off
  packages/components/src/components/Log/Log.js
  packages/components/src/components/PipelineRun/PipelineRun.js
Labels: approved, lgtm, size/S

#2108 Publish @tektoncd/dashboard-components 0.0.1-alpha.72
  lerna.json
Labels: approved, lgtm, size/XS

#2110 Update UI components to support displaying TaskRun Pod details
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/ViewYAML/ViewYAML.js
  packages/components/src/components/ViewYAML/ViewYAML.scss
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#2112 Fix client mode
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/XS

#2111 Migrate CustomResourceDefinition container to react-query
  src/actions/clusterInterceptors.js
  src/actions/clusterInterceptors.test.js
  src/api/clusterTasks.js
  src/api/clusterTasks.test.js
  src/api/index.js
  src/api/pipelines.js
  src/api/pipelines.test.js
  src/api/tasks.js
  src/api/tasks.test.js
  src/containers/App/App.js
  src/containers/ClusterInterceptors/ClusterInterceptors.js
  src/containers/ClusterInterceptors/ClusterInterceptors.test.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/TaskRun/TaskRun.js
  src/reducers/clusterInterceptors.js
  src/reducers/clusterInterceptors.test.js
  src/reducers/index.js
  src/reducers/index.test.js
Labels: approved, lgtm, size/XL

#2113 Update proxy to support websockets
  cmd/dashboard/main.go
  docs/dev/api.md
  docs/extensions.md
  go.mod
  go.sum
  pkg/controllers/controller.go
  pkg/controllers/kubernetes/extension.go
  pkg/endpoints/cluster.go
  pkg/endpoints/externallogs.go
  pkg/endpoints/health.go
  pkg/endpoints/health_test.go
  pkg/endpoints/websocket.go
  pkg/endpoints/websocket_test.go
  pkg/router/router.go
  pkg/router/routes_test.go
  pkg/testutils/testutils.go
  pkg/utils/utils.go
  pkg/websocket/websocket.go
  src/api/extensions.js
  src/api/extensions.test.js
  src/reducers/extensions.js
  src/reducers/extensions.test.js
  webpack.dev.js
Labels: approved, lgtm, size/XXL

#2117 Set HOME env var for release pipeline publish task
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#2118 Fix for logs on some Kubernetes versions
  src/api/index.js
Labels: approved, lgtm, size/XS

#2106 Enable Start and Stop for PipelineRunPending
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/Rerun/Rerun.js
  packages/components/src/components/RunAction/RunAction.js
  packages/components/src/components/RunAction/RunAction.scss
  packages/components/src/components/RunAction/RunAction.test.js
  packages/components/src/components/RunAction/index.js
  packages/components/src/components/RunHeader/RunHeader.scss
  packages/components/src/components/index.js
  packages/utils/src/utils/constants.js
  packages/utils/src/utils/index.js
  src/api/comms.js
  src/api/pipelineRuns.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/App.scss
Labels: approved, lgtm, ok-to-test, size/L

#2120 Remove link from page title
  packages/components/src/components/Header/Header.js
Labels: approved, lgtm, size/XS

#2122 UI text elements should use sentence-case capitalization
  packages/components/src/components/Graph/ZoomablePipelineGraph.js
  packages/components/src/components/LabelFilter/LabelFilter.js
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Table/Table.test.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/EventListener/EventListener.js
  src/containers/EventListener/EventListener.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/ListPageLayout/ListPageLayout.js
  src/containers/PipelineResource/PipelineResource.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/nls/messages_en.json
Labels: approved, lgtm, size/L

#2125 Add v0.18.0 links to the readme
  README.md
Labels: approved, lgtm, size/XS

#2126 Update e2e tests to use latest releases
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#2124 Remove unneccessary requests for TaskRuns
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
  src/containers/TaskRuns/TaskRuns.js
Labels: approved, lgtm, size/M

#2121 Switch Cancel PipelineRun / TaskRun to patch requests
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
Labels: approved, lgtm, size/M

#2119 Add autoscroll to logs of running steps
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/Log/domUtils.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
Labels: approved, lgtm, ok-to-test, size/L

#2127 update the skip to main content button
  packages/components/src/components/Header/Header.js
  src/containers/About/About.js
  src/containers/App/App.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ListPageLayout/ListPageLayout.js
  src/scss/App.scss
Labels: approved, lgtm, size/M

#2123 Move more resources to react-query
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/api/index.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/Extension/Extension.js
  src/containers/Extension/actions.js
  src/containers/Pipelines/Pipelines.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/Tasks/Tasks.js
  src/containers/TasksDropdown/TasksDropdown.js
  src/containers/TasksDropdown/TasksDropdown.test.js
Labels: approved, lgtm, size/XXL

#2129 Fix UI bug for TaskRuns in read-only mode
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
Labels: approved, lgtm, size/S

#2131 Ensure installer script removes all Dashboard-related resource on uninstall
  scripts/installer
Labels: approved, lgtm, size/XS

#2134 Fix extension details page
  src/api/index.js
  src/api/index.test.js
Labels: approved, lgtm, size/M

#2136 Remove react-query noise from test output
  config_frontend/setupTests.js
Labels: approved, lgtm, size/XS

#2132 Fix dependent queries on Create PipelineRun and Create TaskRun pages
  src/api/clusterTasks.js
  src/api/clusterTasks.test.js
  src/api/index.js
  src/api/index.test.js
  src/api/pipelines.js
  src/api/pipelines.test.js
  src/api/tasks.js
  src/api/tasks.test.js
  src/api/utils.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreateTaskRun/CreateTaskRun.js
Labels: approved, lgtm, size/M

#2137 Remove duplicate requests for Extensions
  src/containers/Extensions/Extensions.js
  src/containers/SideNav/SideNav.js
Labels: approved, lgtm, size/S

#2135 Move display of PipelineResources
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/ResourceTable/ResourceTable.js
  packages/components/src/components/ResourceTable/ResourceTable.scss
  packages/components/src/components/StepDefinition/StepDefinition.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/App.scss
Labels: approved, lgtm, ok-to-test, size/L

#2138 Refactor TaskRun(s) and PipelineRun(s) pages to use react-query
  src/actions/actionCreators.js
  src/actions/actionCreators.test.js
  src/actions/pipelineRuns.js
  src/actions/pipelineRuns.test.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/actions/taskRuns.js
  src/actions/taskRuns.test.js
  src/actions/tasks.js
  src/actions/tasks.test.js
  src/api/pipelineRuns.js
  src/api/taskRuns.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TaskRuns/index.js
  src/reducers/clusterTasks.js
  src/reducers/clusterTasks.test.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/pipelineRuns.js
  src/reducers/pipelineRuns.test.js
  src/reducers/pipelines.js
  src/reducers/pipelines.test.js
  src/reducers/reducerCreators.js
  src/reducers/selectorCreators.js
  src/reducers/selectorCreators.test.js
  src/reducers/taskRuns.js
  src/reducers/taskRuns.test.js
  src/reducers/tasks.js
  src/reducers/tasks.test.js
Labels: approved, lgtm, size/XXL

#2140 Update log trailer when forcePolling is true but step is complete
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/Log/Log.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/M

#2133 Add scroll buttons to logs of steps
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/Log/domUtils.js
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, ok-to-test, size/L

#2142 Publish @tektoncd/dashboard-components 0.0.1-alpha.73
  lerna.json
Labels: approved, lgtm, size/XS

#2143 Update docs and tests to latest releases
  README.md
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#2144 Housekeeping
  packages/components/src/components/DetailsHeader/index.js
  packages/components/src/components/ErrorBoundary/index.js
  packages/components/src/components/FormattedDate/index.js
  packages/components/src/components/FormattedDuration/index.js
  packages/components/src/components/Header/Header.js
  packages/components/src/components/KeyValueList/index.js
  packages/components/src/components/LabelFilter/index.js
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/LogFormat/index.js
  packages/components/src/components/LogoutButton/index.js
  packages/components/src/components/PageErrorBoundary/index.js
  packages/components/src/components/PipelineRun/index.js
  packages/components/src/components/PipelineRuns/index.js
  packages/components/src/components/ResourceDetails/index.js
  packages/components/src/components/ResourceTable/index.js
  packages/components/src/components/RunAction/index.js
  packages/components/src/components/RunDropdown/index.js
  packages/components/src/components/Step/index.js
  packages/components/src/components/StepDefinition/index.js
  packages/components/src/components/StepStatus/index.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
  packages/components/src/components/TaskRuns/index.js
  packages/components/src/components/TaskTree/index.js
  packages/components/src/components/TextInput/index.js
  packages/components/src/components/TooltipDropdown/index.js
  packages/components/src/components/ViewYAML/index.js
  src/containers/Extension/index.js
  src/containers/Extensions/index.js
  src/containers/LabelFilter/index.js
  src/containers/Pipelines/index.js
  src/containers/Tasks/index.js
Labels: approved, lgtm, size/L

#2146 Add settings page and respect system theme by default
  packages/components/src/components/LoadingShell/LoadingShell.js
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/containers/About/About.test.js
  src/containers/App/App.js
  src/containers/Settings/Settings.js
  src/containers/Settings/Settings.scss
  src/containers/Settings/Settings.test.js
  src/containers/Settings/index.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
  src/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/App.scss
  src/scss/_carbon.scss
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/L

#2139 Move About to the bottom of the SideNav
  src/containers/SideNav/SideNav.scss
Labels: approved, lgtm, ok-to-test, size/S

#2149 create pending pipeline
  src/api/pipelineRuns.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/_carbon.scss
Labels: approved, lgtm, size/M

#2150 Prevent side nav menus from overlapping in short windows
  src/containers/SideNav/SideNav.scss
Labels: approved, lgtm, size/XS

#2151 Fix colour token for PipelineRunPending status label
  packages/components/src/components/RunHeader/RunHeader.scss
Labels: approved, lgtm, size/XS

#2141 Move namespaces to react-query
  src/actions/actionCreators.js
  src/actions/actionCreators.test.js
  src/actions/namespaces.js
  src/actions/namespaces.test.js
  src/api/extensions.js
  src/api/extensions.test.js
  src/api/index.js
  src/api/index.test.js
  src/api/pipelineRuns.test.js
  src/api/taskRuns.test.js
  src/api/utils.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/Conditions/Conditions.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineResource/CreatePipelineResource.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/EventListeners/EventListeners.js
  src/containers/EventListeners/EventListeners.test.js
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/ListPageLayout/ListPageLayout.js
  src/containers/ListPageLayout/ListPageLayout.test.js
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/PipelinesDropdown/PipelinesDropdown.js
  src/containers/PipelinesDropdown/PipelinesDropdown.test.js
  src/containers/ResourceList/ResourceList.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.js
  src/containers/ServiceAccountsDropdown/ServiceAccountsDropdown.test.js
  src/containers/SideNav/SideNav.js
  src/containers/SideNav/SideNav.test.js
  src/containers/TaskRun/TaskRun.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/TasksDropdown/TasksDropdown.js
  src/containers/TasksDropdown/TasksDropdown.test.js
  src/containers/TriggerBinding/TriggerBinding.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerBindings/TriggerBindings.test.js
  src/containers/TriggerTemplate/TriggerTemplate.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/TriggerTemplates/TriggerTemplates.test.js
  src/containers/Triggers/Triggers.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/namespaces.js
  src/reducers/namespaces.test.js
  src/reducers/reducerCreators.js
  src/utils/test.js
Labels: approved, lgtm, size/XXL

#2147 Add setting to enable log timestamps
  src/api/index.js
  src/api/utils.js
  src/api/utils.test.js
  src/containers/Settings/Settings.js
  src/containers/Settings/Settings.scss
  src/containers/Settings/Settings.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#2148 Remove locale-related redux code
  src/actions/locale.js
  src/actions/locale.test.js
  src/containers/App/App.js
  src/index.js
  src/reducers/index.js
  src/reducers/index.test.js
  src/reducers/locale.js
  src/reducers/locale.test.js
Labels: approved, lgtm, size/L
