Repository tektoncd/dashboard, pull requests merged in 2021-11, with the labels that each got.

#2227 Fix Task component tests
  package-lock.json
  packages/components/src/components/Task/Task.test.js
Labels: lgtm, size/L, approved, hacktoberfest-accepted

#2229 update log trailer msg for onError:continue
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/Log/Log.test.js
  packages/utils/src/utils/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: size/M, lgtm, approved

#2230 Update backend code for getting project version info
  README.md
  base/200-clusterrole-dashboard.yaml
  base/200-clusterrole-pipelines.yaml
  base/200-clusterrole-triggers.yaml
  base/300-config-info.yaml
  overlays/installer/base/kustomization.yaml
  pkg/endpoints/dashboard.go
  scripts/installer
  tekton/publish.yaml
Labels: lgtm, size/L, approved

#2231 Include stepTemplate in step definition details tab
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: lgtm, size/L, approved

#2233 Add support for specifying tag to installer script used for releases
  docs/dev/installer.md
  scripts/installer
Labels: size/XS, lgtm, approved

#2232 Update release pipeline to use results and workspaces instead of PipelineResources
  .yamllint
  package.json
  packages/components/package.json
  packages/utils/package.json
  scripts/installer
  tekton/README.md
  tekton/build.yaml
  tekton/kustomization.yaml
  tekton/prerelease-checks.yaml
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
  tekton/resources.yaml
  test/presubmit-tests.sh
Labels: size/XXL, lgtm, approved

#2237 Add v0.22.0 links to the readme
  README.md
Labels: size/XS, lgtm, approved

#2238 Remove Ziheng from the list of reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#2239 Surface details of step onError continue in lists and details
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/DetailsHeader/DetailsHeader.scss
  packages/components/src/components/DetailsHeader/DetailsHeader.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/components/src/components/StatusIcon/StatusIcon.scss
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Step/Step.stories.js
  packages/components/src/components/Step/Step.test.js
  packages/components/src/components/StepDetails/StepDetails.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/Task/Task.js
  packages/components/src/components/Task/Task.scss
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: lgtm, size/XL, approved

#2241 Set content-type header only on valid request methods
  pkg/utils/proxy.go
Labels: size/XS, lgtm, approved, ok-to-test

#2245 Update pending logs state to make it look less like an error
  packages/components/src/components/DotSpinner/DotSpinner.js
  packages/components/src/components/DotSpinner/DotSpinner.scss
  packages/components/src/components/DotSpinner/DotSpinner.stories.js
  packages/components/src/components/DotSpinner/index.js
  packages/components/src/components/Log/Log.js
  packages/components/src/components/Log/Log.scss
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/Spinner/Spinner.stories.js
  packages/components/src/components/index.js
  src/scss/App.scss
Labels: lgtm, size/L, approved

#2246 Publish @tektoncd/dashboard-components 0.0.1-alpha.80
  lerna.json
Labels: size/XS, lgtm, approved

#2248 Fix syntax highlighting when root value is an array
  packages/components/src/components/ViewYAML/SyntaxHighlighter.js
  packages/components/src/components/ViewYAML/ViewYAML.stories.js
Labels: lgtm, size/S, approved

#2250 Prevent webpack dev server blocking UI on warnings
  webpack.dev.js
Labels: size/XS, lgtm, approved

#2249 Update pod tab empty state
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: lgtm, size/S, approved

#2251 Fix display of short values in SyntaxHighlighter for Firefox
  packages/components/src/components/ViewYAML/ViewYAML.scss
Labels: size/XS, lgtm, approved

#2252 Publish @tektoncd/dashboard-components 0.0.1-alpha.81
  lerna.json
Labels: size/XS, lgtm, approved
