Repository tektoncd/dashboard, pull requests merged in 2021-01, with the labels that each got.

#1879 Add style-guide.md and modify messages_ja.json
  docs/dev/localization/Japanese/style-guide.md
  src/nls/messages_ja.json
Labels: approved, lgtm, ok-to-test, size/M

#1881 Remove not existed request verb
  overlays/patches/read-write/clusterrole-backend-patch.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1876 Update nav icons for legibility
  src/containers/SideNav/SideNav.scss
  src/images/kubernetes.svg
  src/images/tekton-logo-20x20.svg
Labels: approved, lgtm, size/S

#1882 Update Extensions CRD to use apiextensions.k8s.io/v1
  base/202-extension-crd.yaml
Labels: approved, lgtm, size/M

#1883 Update roadmap
  roadmap.md
Labels: approved, lgtm, size/S

#1877 Add ability to delete Pipelines, Tasks, and ClusterTasks
  packages/components/src/components/Table/Table.scss
  src/api/clusterTasks.js
  src/api/clusterTasks.test.js
  src/api/pipelines.js
  src/api/pipelines.test.js
  src/api/tasks.js
  src/api/tasks.test.js
  src/components/App/App.scss
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.test.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/XL

#1886 Update navigation flow from Pipelines/Tasks/ClusterTasks to the corresponding runs
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1887 Fix styling of inline table actions in read only mode
  packages/components/src/components/Table/Table.scss
Labels: approved, lgtm, size/XS

#1885 Reduce code duplication for delete modals and disambiguate resources in different namespaces
  packages/components/src/components/DeleteModal/DeleteModal.js
  packages/components/src/components/DeleteModal/DeleteModal.scss
  packages/components/src/components/DeleteModal/DeleteModal.stories.js
  packages/components/src/components/DeleteModal/index.js
  packages/components/src/components/index.js
  src/actions/secrets.js
  src/actions/secrets.test.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.js
  src/components/SecretsDeleteModal/SecretsDeleteModal.test.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Secrets/Secrets.js
  src/containers/Secrets/Secrets.test.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
Labels: approved, lgtm, size/XL

#1888 Remove src/components folder and move contents to more suitable locations
  .storybook/Container.scss
  src/containers/App/App.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineResource/GitResourceFields.js
  src/containers/CreatePipelineResource/UniversalFields.js
  src/containers/CreateSecret/CreateSecret.js
  src/containers/CreateSecret/CreateSecret.scss
  src/containers/CreateSecret/Form/AccessTokenType.js
  src/containers/CreateSecret/Form/AccessTokenType.test.js
  src/containers/CreateSecret/Form/Annotations.js
  src/containers/CreateSecret/Form/Annotations.test.js
  src/containers/CreateSecret/Form/PasswordType.js
  src/containers/CreateSecret/Form/PasswordType.test.js
  src/containers/CreateSecret/Form/UniversalFields.js
  src/containers/CreateSecret/Form/UniversalFields.test.js
  src/containers/CreateSecret/Form/index.js
  src/containers/CreateSecret/Form/index.test.js
  src/containers/CreateSecret/ServiceAccountSelector.js
  src/containers/CreateSecret/ServiceAccountSelector.test.js
  src/containers/Extensions/Extensions.js
  src/containers/Pipelines/Pipelines.js
  src/containers/Tasks/Tasks.js
  src/scss/App.scss
  src/scss/Definitions.scss
  src/scss/_carbon.scss
Labels: approved, lgtm, size/M

#1889 Ensure success notification is visible on import resources
  src/containers/ImportResources/ImportResources.js
  src/containers/ImportResources/ImportResources.scss
Labels: approved, lgtm, size/S

#1890 Move Create PipelineRun to its own page
  src/containers/App/App.js
  src/containers/CreatePipelineResource/CreatePipelineResource.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreatePipelineRun/index.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1891 Move Create TaskRun to its own page
  src/containers/App/App.js
  src/containers/CreateTaskRun/CreateTaskRun.js
  src/containers/CreateTaskRun/CreateTaskRun.test.js
  src/containers/CreateTaskRun/index.js
  src/containers/TaskRuns/TaskRuns.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/L

#1892 Replace the deprecated `waitForElement` from react testing library
  packages/components/src/components/LabelFilter/LabelFilter.test.js
  packages/components/src/components/Log/Log.test.js
  packages/components/src/components/LogoutButton/LogoutButton.test.js
  packages/components/src/components/PipelineResources/PipelineResources.test.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/components/src/components/ResourceDetails/ResourceDetails.test.js
  packages/components/src/components/RunDropdown/RunDropdown.test.js
  packages/components/src/components/Task/Task.test.js
  src/containers/App/App.test.js
  src/containers/ClusterTriggerBinding/ClusterTriggerBinding.test.js
  src/containers/Condition/Condition.test.js
  src/containers/CreatePipelineResource/CreatePipelineResourceErrorNotification.test.js
  src/containers/CreateSecret/CreateSecret.test.js
  src/containers/CreateSecret/Form/Annotations.test.js
  src/containers/EventListener/EventListener.test.js
  src/containers/ImportResources/ImportResources.test.js
  src/containers/PipelineRun/PipelineRun.test.js
  src/containers/PipelineRuns/PipelineRuns.test.js
  src/containers/Secret/Secret.test.js
  src/containers/Secrets/Secrets.test.js
  src/containers/ServiceAccount/ServiceAccount.test.js
  src/containers/SideNav/SideNav.test.js
  src/containers/TaskRuns/TaskRuns.test.js
  src/containers/TriggerBinding/TriggerBinding.test.js
  src/containers/TriggerTemplate/TriggerTemplate.test.js
Labels: approved, lgtm, size/XL

#1893 Remove warning logs from unit test output
  packages/components/src/components/LogoutButton/LogoutButton.test.js
  packages/components/src/components/PipelineRun/PipelineRun.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  packages/components/src/components/StepDefinition/StepDefinition.test.js
  src/containers/Secret/Secret.test.js
Labels: approved, lgtm, size/M

#1894 Update ini to resolve npm audit warnings
  package-lock.json
Labels: approved, lgtm, size/XS

#1895 Publish @tektoncd/dashboard-components@0.0.1-alpha.64
  lerna.json
Labels: approved, lgtm, size/XS

#1896 Update log component loading state colours
  packages/components/src/components/Log/Log.scss
Labels: approved, lgtm, size/XS

#1897 Publish @tektoncd/dashboard-components@0.0.1-alpha.65
  lerna.json
Labels: approved, lgtm, size/XS

#1898 Add v0.13 links to readme
  README.md
Labels: approved, lgtm, size/XS

#1899 Simplify CSRF protection to work with client bundle approach
  .gitignore
  cmd/dashboard/main.go
  docs/dev/README.md
  docs/dev/installer.md
  go.mod
  go.sum
  overlays/patches/installer/deployment-patch.yaml
  pkg/csrf/csrf.go
  pkg/endpoints/cluster.go
  pkg/router/router.go
  pkg/router/routes_test.go
  scripts/installer
  src/api/clusterTasks.test.js
  src/api/comms.js
  src/api/comms.test.js
  src/api/index.test.js
  src/api/pipelineResources.test.js
  src/api/pipelineRuns.test.js
  src/api/pipelines.test.js
  src/api/secrets.test.js
  src/api/serviceAccounts.test.js
  src/api/taskRuns.test.js
  src/api/tasks.test.js
  src/utils/test.js
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#1905 Fix buffer undefined error in create new secret page
  package-lock.json
  package.json
  src/containers/CreateSecret/CreateSecret.js
Labels: approved, kind/bug, lgtm, size/M

#1900 Update default status icon
  packages/components/src/components/DetailsHeader/DetailsHeader.js
  packages/components/src/components/StatusIcon/StatusIcon.js
  packages/components/src/components/StatusIcon/StatusIcon.scss
  packages/components/src/components/Step/Step.js
  packages/components/src/components/Task/Task.js
Labels: approved, lgtm, size/S

#1903 Update installer script to build multi-arch image only on release action
  scripts/installer
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#1904 Update dev docs on use of the API_DOMAIN environment variable
  docs/dev/README.md
Labels: approved, lgtm, size/XS

#1902 Update hardcoded string in Extension loading state to use react-intl
  src/containers/Extension/Extension.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: approved, lgtm, size/S

#1906 Publish @tektoncd/dashboard-components@0.0.1-alpha.66
  lerna.json
Labels: approved, lgtm, size/XS

#1907 Handle properties fallback when running in client mode
  src/actions/properties.js
  src/actions/properties.test.js
  src/reducers/properties.js
  src/reducers/properties.test.js
Labels: approved, lgtm, size/M

#1908 Update to Carbon 10.26
  package-lock.json
  package.json
  packages/components/package.json
Labels: approved, lgtm, size/M

#1909 Add Ziheng as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#1911 Publish @tektoncd/dashboard-components@0.0.1-alpha.67
  lerna.json
Labels: approved, lgtm, size/XS

#1912 Update installer script to allow overriding target platform
  docs/dev/installer.md
  scripts/installer
Labels: approved, lgtm, size/M

#1913 Update Dashboard screenshot on main readme
  README.md
  docs/dashboard-ui.jpg
  docs/dashboard-ui.png
Labels: approved, lgtm, size/XS

#1910 Update to latest Storybook release
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#1916 Improve handling of generated files
  .generated_files
  .gitattributes
  hack/boilerplate/boilerplate.go.txt
Labels: approved, lgtm, size/S

#1919 Fix error handling in logs fallback
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/M

#1901 Update links to Dashboard Katacoda tutorial
  README.md
  docs/README.md
  docs/install.md
Labels: approved, lgtm, size/XS

#1922 Update docs for currency and style
  docs/README.md
  docs/dev/README.md
  docs/dev/api.md
  docs/dev/installer.md
  docs/extensions.md
  docs/install.md
  docs/walkthrough/walkthrough-istio.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
  src/containers/CreateSecret/CreateSecret.js
Labels: approved, lgtm, size/L

#1920 Update logs walkthrough to specify tested dependency versions
  docs/walkthrough/walkthrough-logs.md
Labels: approved, lgtm, size/S

#1924 Add Simplified Chinese translation
  src/nls/messages_zh-Hans.json
Labels: approved, lgtm, ok-to-test, size/XL

#1925 Update editorconfig to avoid unwanted trailing newlines in JSON files
  .editorconfig
Labels: approved, lgtm, size/XS
