Repository tektoncd/dashboard, pull requests merged in 2022-01, with the labels that each got.

#2269 Add some Simplified Chinese translation
  src/nls/messages_zh-Hans.json
Labels: size/M, lgtm, approved, ok-to-test

#2270 Sort items in namespace drop down by name
  src/containers/NamespacesDropdown/NamespacesDropdown.js
  src/containers/NamespacesDropdown/NamespacesDropdown.test.js
Labels: lgtm, size/S, approved, ok-to-test

#2271 Rename string id
  packages/components/src/components/Log/Log.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: lgtm, size/S, approved

#2272 Publish @tektoncd/dashboard-components 0.0.1-alpha.82
  lerna.json
Labels: size/XS, lgtm, approved

#2274 Update e2e to use latest releases
  README.md
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#2273 Enable React Fast Refresh and Strict Mode for Storybook
  .storybook/Container.js
  .storybook/main.js
  package-lock.json
  package.json
Labels: size/M, lgtm, approved

#2275 Make required kustomize version clearer in the docs
  docs/dev/README.md
Labels: size/XS, lgtm, approved

#2277 Improve and simplify webpack build
  docs/dev/README.md
  package.json
  tekton/build.yaml
  test/presubmit-tests.sh
  webpack.prod.js
Labels: size/M, lgtm, approved

#2279 Update to latest Carbon release
  package-lock.json
  package.json
  packages/components/package.json
Labels: lgtm, size/S, approved

#2281 Update PR template to more closely match version used for other projects
  .github/pull_request_template.md
Labels: lgtm, size/S, approved

#2282 Fix SideNav links when navigation from a cluster-scoped page
  src/containers/SideNav/SideNav.js
Labels: lgtm, size/S, approved

#2283 Add example of ingress with path
  docs/install.md
Labels: lgtm, size/S, approved

#2286 Add section on access control to the install docs
  docs/README.md
  docs/dev/README.md
  docs/install.md
  docs/walkthrough/README.md
  docs/walkthrough/walkthrough-istio-kiali.png
  docs/walkthrough/walkthrough-istio.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
Labels: lgtm, size/L, approved

#2288 Update deps to resolve npm audit warnings
  package-lock.json
  package.json
Labels: lgtm, size/S, approved

#2290 Update to latest major Jest version
  jest.config.js
  package-lock.json
  package.json
  packages/components/src/components/RunAction/RunAction.test.js
Labels: size/M, lgtm, approved

#2284 Remove unused font formats from config
  jest.config.js
  webpack.common.js
Labels: size/XS, lgtm, approved

#2289 Remove the update-deps script
  hack/update-deps.sh
Labels: size/M, lgtm, approved

#2292 Update test script
  test/e2e-tests.sh
Labels: size/M, lgtm, approved

#2296 Update to node 16
  docs/dev/README.md
  package-lock.json
  package.json
  packages/components/package.json
  packages/utils/package.json
  tekton/build.yaml
  test/presubmit-tests.sh
Labels: lgtm, size/S, approved

#2298 Add v0.24.0 links to the readme
  README.md
Labels: size/XS, lgtm, approved

#2300 Fix for Safari
  .storybook/.babelrc
  babel.config.js
  package-lock.json
  package.json
Labels: size/M, lgtm, approved

#2301 Add v0.24.1 links to the readme
  README.md
  tekton/release-cheat-sheet.md
Labels: size/XS, lgtm, approved

#2303 Publish @tektoncd/dashboard-components 0.0.1-alpha.83
  lerna.json
Labels: size/XS, lgtm, approved
