Repository tektoncd/dashboard, pull requests merged in 2022-04, with the labels that each got.

#2332 Update oauth2-proxy walkthrough to use community charts
  docs/walkthrough/walkthrough-oauth2-proxy.md
Labels: size/XS, lgtm, approved

#2333 Validate Origin header on websocket connection upgrade
  pkg/router/router.go
Labels: size/M, lgtm, approved

#2334 Update release docs to include process for patch releases
  tekton/README.md
Labels: lgtm, size/S, approved

#2336 Update readme with links to latest releases
  README.md
Labels: size/M, lgtm, approved

#2337 Update npm package readme, with Windows note and one time passcode param
  tekton/README.md
Labels: size/XS, lgtm, approved

#2338 Publish v0.26.0-alpha.1 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved

#2339 Update go.mod to reference minimum go version
  go.mod
  go.sum
  hack/tools.go
  tekton/publish.yaml
Labels: size/M, lgtm, approved

#2343 Add sample Task and Pipeline definitions used by the new tutorial
  docs/tutorial/pipeline.yaml
  docs/tutorial/tasks.yaml
Labels: size/M, lgtm, approved

#2344 Fix positioning of buttons on Create PipelineResource page
  src/containers/CreatePipelineResource/CreatePipelineResource.js
Labels: size/M, lgtm, approved

#2342 Add a getting started guide / tutorial to the docs
  README.md
  docs/README.md
  docs/dev/api.md
  docs/install.md
  docs/tutorial/README.md
Labels: lgtm, size/L, approved

#2327 Add client-side pagination
  src/containers/ClusterInterceptors/ClusterInterceptors.js
  src/containers/ClusterTasks/ClusterTasks.js
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.js
  src/containers/Conditions/Conditions.js
  src/containers/EventListener/EventListener.stories.js
  src/containers/EventListeners/EventListeners.js
  src/containers/ListPageLayout/ListPageLayout.js
  src/containers/ListPageLayout/ListPageLayout.stories.js
  src/containers/ListPageLayout/ListPageLayout.test.js
  src/containers/PipelineResources/PipelineResources.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/containers/Pipelines/Pipelines.js
  src/containers/ResourceList/ResourceList.js
  src/containers/TaskRuns/TaskRuns.js
  src/containers/Tasks/Tasks.js
  src/containers/TriggerBindings/TriggerBindings.js
  src/containers/TriggerTemplates/TriggerTemplates.js
  src/containers/Triggers/Triggers.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/_carbon.scss
Labels: size/XXL, lgtm, approved

#2346 Add note to docs for manually running nightly release
  tekton/README.md
Labels: size/XS, lgtm, approved

#2348 Update Storybook to latest release
  package-lock.json
  package.json
Labels: lgtm, size/S, approved

#2347 Avoid displaying stack trace for 404 with missing statusText
  src/api/comms.js
  src/api/comms.test.js
Labels: lgtm, size/S, approved
