Repository tektoncd/dashboard, pull requests merged in 2022-11, with the labels that each got.

#2554 Remove managedFields from display of Pod resource and events
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
Labels: lgtm, size/L, approved, kind/misc

#2560 Update tests to use latest Pipelines release
  releases.md
  test/e2e-tests.sh
Labels: lgtm, size/S, approved, kind/misc

#2562 Add v0.30 to the release docs
  releases.md
Labels: lgtm, size/S, approved

#2563 Remove reference to resolvers.yaml from prepare-kind-cluster script
  scripts/prepare-kind-cluster
Labels: size/XS, lgtm, approved, kind/misc

#2572 Update dependencies
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#2565 Add E2E test to create pipeline run
  packages/e2e/Dockerfile
  packages/e2e/cypress/e2e/run/create-pipelinerun.cy.js
  test/e2e-tests.sh
Labels: size/M, lgtm, approved, ok-to-test, kind/misc

#2574 Update walk-throughs and dev script to Kubernetes 1.25
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
  scripts/prepare-kind-cluster
Labels: size/M, lgtm, approved, kind/documentation, kind/misc

#2585 Update loader-utils and Storybook
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#2575 Add ability to create PipelineRun from YAML [codemirror]
  package-lock.json
  package.json
  packages/e2e/cypress/e2e/run/create-pipelinerun.cy.js
  pkg/router/router.go
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreatePipelineRun/YAMLEditor.js
  src/containers/CreatePipelineRun/YAMLEditor.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/scss/Create.scss
  webpack.dev.js
Labels: kind/feature, lgtm, size/XL, approved, ok-to-test

#2586 Update e2e tests to latest Triggers release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2594 Fix accessibility violations
  packages/components/src/components/FormattedDate/FormattedDate.js
  packages/components/src/components/FormattedDuration/FormattedDuration.js
  packages/components/src/components/Tabs/Tabs.js
Labels: lgtm, size/S, approved, ok-to-test

#2599 Publish v0.31.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#2596 Update tests to latest Pipelines release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2597 Add new namespace scoped Interceptor CRD introduced by Triggers v0.22
  base/200-clusterrole-tenant.yaml
  overlays/patches/read-write/clusterrole-tenant-patch.yaml
  packages/e2e/cypress/fixtures/kinds.json
  packages/utils/src/utils/router.js
  src/api/index.js
  src/api/interceptors.js
  src/api/interceptors.test.js
  src/containers/App/App.js
  src/containers/CustomResourceDefinition/CustomResourceDefinition.js
  src/containers/Interceptors/Interceptors.js
  src/containers/Interceptors/Interceptors.test.js
  src/containers/Interceptors/index.js
  src/containers/SideNav/SideNav.js
  src/containers/index.js
Labels: kind/feature, lgtm, size/L, approved

#2606 Update codemirror
  package-lock.json
  package.json
  packages/e2e/cypress/e2e/run/create-pipelinerun.cy.js
Labels: lgtm, size/S, approved, kind/misc

#2613 Update dependencies
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#2614 Switch Triggers resources to v1beta1
  src/api/clusterTriggerBindings.js
  src/api/eventListeners.js
  src/api/triggerBindings.js
  src/api/triggerTemplates.js
  src/api/triggers.js
Labels: kind/feature, size/M, lgtm, approved
