Repository tektoncd/dashboard, pull requests merged in 2022-05, with the labels that each got.

#2349 AVT screen reader issue with batch actions Delete button on table
  packages/components/src/components/Table/Table.js
Labels: size/XS, lgtm, approved

#2350 Publish v0.26.0-alpha.2 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved

#2354 Publish v0.26.0-alpha.3 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved

#2353 Update kustomize to v4
  docs/dev/README.md
  scripts/installer
  tekton/publish.yaml
  test/e2e-common.sh
  test/presubmit-tests.sh
Labels: lgtm, size/S, approved

#2355 Add links to latest release in readme
  README.md
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#2357 Update doc links on About page
  src/containers/About/About.js
  src/nls/messages_en.json
Labels: lgtm, size/S, approved

#2358 Add Lyndsey to approvers list
  OWNERS
Labels: size/XS, lgtm, approved

#2359 Add support for injecting a custom icon into the PipelineRun header
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/RunHeader/RunHeader.js
Labels: size/XS, lgtm, approved

#2360 Remove references to the dist folder
  .dockerignore
  .gitignore
  .stylelintignore
  package.json
  scripts/i18n/extractMessages.js
  src/containers/PipelineResourcesDropdown/PipelineResourcesDropdown.test.js
Labels: size/M, lgtm, approved

#2362 Update Triggers to latest release
  README.md
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#2361 Update installer script to detect Apple M1
  scripts/installer
Labels: lgtm, size/S, approved

#2363 Handle invalid params in Task spec
  packages/components/src/components/TaskRunDetails/TaskRunDetails.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.test.js
Labels: size/M, lgtm, approved

#2364 Bump version of Tekton Pipeline to v0.35.1
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#2356 Update design of runs pages
  packages/components/src/components/Actions/Actions.test.js
  packages/components/src/components/DetailsHeader/DetailsHeader.test.js
  packages/components/src/components/FormattedDate/FormattedDate.js
  packages/components/src/components/FormattedDate/FormattedDate.test.js
  packages/components/src/components/FormattedDuration/FormattedDuration.js
  packages/components/src/components/FormattedDuration/FormattedDuration.test.js
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.scss
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.scss
  packages/components/src/components/TaskRuns/TaskRuns.js
  packages/components/src/components/TaskRuns/TaskRuns.test.js
  src/containers/App/App.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: lgtm, size/XL, approved

#2365 Support different button kinds in Table toolbarButtons
  packages/components/src/components/Table/Table.js
  packages/components/src/components/Table/Table.stories.js
Labels: lgtm, size/S, approved

#2366 Publish v0.27.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved

#2367 Add support for reporting custom duration on PipelineRuns
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: lgtm, size/S, approved

#2368 Update docs
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  docs/README.md
  docs/dev/README.md
  docs/dev/installer.md
  docs/extensions-resource-based-rbac.png
  docs/extensions-service-based-backend.png
  docs/extensions-service-based-frontend.png
  docs/extensions.md
  docs/install.md
  docs/tekton-dashboard-color.svg
  docs/tutorial.md
  docs/walkthrough/README.md
  docs/walkthrough/walkthrough-kind.md
  docs/walkthrough/walkthrough-logs.md
  docs/walkthrough/walkthrough-oauth2-proxy.md
  roadmap.md
Labels: lgtm, size/XL, approved

#2369 Allow custom status detail on the PipelineRuns page
  packages/components/src/components/PipelineRuns/PipelineRuns.js
  packages/components/src/components/PipelineRuns/PipelineRuns.test.js
Labels: size/M, lgtm, approved

#2370 Publish v0.27.0-alpha.1 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved

#2371 Support custom tooltips for PipelineRun display name
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: size/XS, lgtm, approved

#2372 Publish v0.27.0-alpha.2 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved

#2375 Fix flash of error when loading PipelineRun details page
  packages/components/src/components/PipelineRun/PipelineRun.js
  src/containers/PipelineRun/PipelineRun.js
Labels: lgtm, size/S, approved

#2376 Disable compression in webpack-dev-server to enable log streaming
  webpack.dev.js
Labels: size/XS, lgtm, approved

#2377 Cleanup webpack-dev-server proxy config
  webpack.dev.js
Labels: size/M, lgtm, approved

#2379 Add ability to inject a custom icon after the PipelineRun name
  packages/components/src/components/PipelineRuns/PipelineRuns.js
Labels: size/XS, lgtm, approved

#2380 Publish v0.27.0-alpha.3 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved
