Repository tektoncd/dashboard, pull requests merged in 2023-05, with the labels that each got.

#2897 Fix Storybook controls
  packages/components/src/components/Actions/Actions.stories.js
  packages/components/src/components/DeleteModal/DeleteModal.stories.js
  packages/components/src/components/DetailsHeader/DetailsHeader.stories.js
  packages/components/src/components/DotSpinner/DotSpinner.stories.js
  packages/components/src/components/FormattedDate/FormattedDate.stories.js
  packages/components/src/components/FormattedDuration/FormattedDuration.stories.js
  packages/components/src/components/Header/Header.stories.js
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/LabelFilter/LabelFilter.stories.js
  packages/components/src/components/LoadingShell/LoadingShell.stories.js
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
Labels: lgtm, size/L, approved, kind/misc

#2899 Update stories to use Storybook CSF3 args
  packages/components/src/components/Log/Log.stories.js
  packages/components/src/components/LogFormat/LogFormat.stories.js
  packages/components/src/components/LogsToolbar/LogsToolbar.stories.js
  packages/components/src/components/PipelineRun/PipelineRun.stories.js
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  packages/components/src/components/RunHeader/RunHeader.stories.js
  packages/components/src/components/Spinner/Spinner.stories.js
  packages/components/src/components/StatusIcon/StatusIcon.stories.js
  packages/components/src/components/Step/Step.stories.js
  packages/components/src/components/StepDefinition/StepDefinition.stories.js
  packages/components/src/components/StepDetails/StepDetails.stories.js
  packages/components/src/components/Table/Table.stories.js
  packages/components/src/components/Task/Task.stories.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  packages/components/src/components/TextInput/TextInput.stories.js
  packages/components/src/components/TooltipDropdown/TooltipDropdown.stories.js
  packages/components/src/components/Trigger/Trigger.stories.js
  packages/graph/src/components/Graph.stories.js
  packages/graph/src/components/Graph/Graph.stories.js
  src/containers/NotFound/NotFound.stories.js
Labels: lgtm, size/XL, approved, kind/misc

#2900 Update Storybook to latest release
  package-lock.json
  package.json
Labels: lgtm, size/S, approved, kind/misc

#2909 Send start and completion time to external logs proxy
  src/api/index.js
  src/api/index.test.js
  src/utils/index.js
  src/utils/index.test.js
Labels: kind/feature, lgtm, size/L, approved, ok-to-test

#2920 Update E2E tests to latest Triggers release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2922 Publish v0.36.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#2931 Update URL of gpg key to use for kubectl install
  packages/e2e/Dockerfile
Labels: size/XS, lgtm, approved, kind/misc

#2933 Update E2E to latest Pipelines release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2939 [v0.36.x] Fix processing of stepTemplate volumeMounts
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: kind/bug, size/M, lgtm, approved
