Repository tektoncd/dashboard, pull requests merged in 2023-01, with the labels that each got.

#2646 Update tests to Pipelines v0.43.0
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2649 Add toggle to settings UI to opt-in to Pipelines v1 resources
  src/api/clusterTasks.js
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/api/taskRuns.js
  src/api/utils.js
  src/containers/Settings/Settings.js
  src/containers/Settings/Settings.scss
  src/containers/Settings/Settings.test.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: kind/feature, lgtm, size/L, approved

#2651 Update import resources to specify version v1beta1
  src/api/index.js
Labels: size/XS, lgtm, approved, kind/misc

#2658 Update Storybook and core-js
  .storybook/.babelrc
  babel.config.js
  package-lock.json
  package.json
Labels: lgtm, size/S, approved, kind/misc

#2652 Remove the OpenShift release manifests and installer flag
  docs/dev/installer.md
  docs/install.md
  scripts/installer
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
  test/e2e-tests.sh
Labels: lgtm, size/L, approved

#2663 Log Dashboard version on startup
  cmd/dashboard/main.go
  pkg/endpoints/cluster.go
  pkg/endpoints/dashboard.go
Labels: lgtm, size/S, approved, kind/misc

#2662 Update tests to latest Pipelines release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2664 Log proxied API requests at debug level
  pkg/router/router.go
Labels: size/XS, lgtm, approved, kind/misc

#2661 Switch default install mode to read-only
  cmd/dashboard/main.go
  docs/dev/README.md
  docs/dev/installer.md
  docs/install.md
  docs/tutorial.md
  scripts/installer
  scripts/prepare-kind-cluster
  tekton/prerelease-checks.yaml
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
  test/e2e-tests.sh
Labels: lgtm, size/L, approved, kind/misc

#2667 Update tests to latest Pipelines release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2673 Update dependencies
  package-lock.json
  package.json
  packages/e2e/package.json
Labels: lgtm, size/S, approved, kind/misc

#2674 Fix typos
  packages/e2e/cypress/e2e/run/create-pipelinerun.cy.js
  tekton/release-cheat-sheet.md
Labels: size/XS, lgtm, approved, kind/misc

#2633 Add new action for PipelineRun - Edit and Run
  packages/e2e/cypress/e2e/run/actions-pipelinerun.cy.js
  src/api/pipelineRuns.js
  src/api/pipelineRuns.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreatePipelineRun/YAMLEditor.js
  src/containers/CreatePipelineRun/YAMLEditor.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
Labels: kind/feature, lgtm, size/XL, approved, ok-to-test

#2675 Update error handling for application loading state
  src/containers/App/App.js
Labels: size/XS, lgtm, approved

#2676 Fix invalid dom nesting
  packages/components/src/components/ResourceDetails/ResourceDetails.js
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.js
  src/containers/EventListener/EventListener.js
  src/containers/Run/Run.js
  src/scss/Triggers.scss
Labels: size/M, lgtm, approved, kind/misc

#2678 Remove unused dependencies
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#2680 Cleanup
  packages/e2e/cypress/e2e/run/actions-pipelinerun.cy.js
  src/api/pipelineRuns.test.js
  src/containers/CreatePipelineRun/CreatePipelineRun.test.js
  src/containers/CreatePipelineRun/YAMLEditor.js
  src/containers/CreatePipelineRun/YAMLEditor.test.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/PipelineRuns/PipelineRuns.js
Labels: lgtm, size/L, approved, kind/misc

#2688 Update eslint plugins
  .eslintrc.js
  package-lock.json
  package.json
Labels: lgtm, size/S, approved, kind/misc

#2689 Update e2e to latest Pipeline release (v0.44.0 LTS)
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#2690 Add v0.32.0 to the release docs
  releases.md
Labels: size/M, lgtm, approved, kind/documentation

#2691 Remove unused prop
  packages/components/src/components/PipelineRun/PipelineRun.js
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.js
  src/containers/PipelineRun/PipelineRun.js
  src/containers/TaskRun/TaskRun.js
Labels: lgtm, size/S, approved, kind/misc

#2693 Update to Node.js 18
  .eslintrc.js
  config_frontend/setupTests.js
  docs/dev/README.md
  package-lock.json
  package.json
  packages/components/package.json
  packages/e2e/Dockerfile
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
  src/api/comms.test.js
  src/api/index.test.js
  src/api/pipelineRuns.test.js
  src/api/runs.test.js
  src/api/taskRuns.test.js
  tekton/build.yaml
  test/presubmit-tests.sh
Labels: lgtm, size/XL, approved, kind/misc

#2700 Update dependencies
  package-lock.json
  package.json
  packages/graph/package.json
Labels: size/XS, lgtm, approved, kind/misc
