Repository tektoncd/dashboard, pull requests merged in 2023-08, with the labels that each got.

#3022 Update Storybook and document the @tektoncd/dashboard-* packages
  .storybook/Container.scss
  .storybook/Welcome.mdx
  .storybook/main.js
  .storybook/preview.js
  .storybook/tekton-horizontal-color.png
  .storybook/theme.js
  .storybook/welcome.scss
  package-lock.json
  package.json
  packages/components/README.md
  packages/graph/README.md
  packages/utils/README.md
  src/scss/Triggers.scss
Labels: lgtm, size/L, approved, kind/documentation

#3032 Update Node.js version used in CI and use nvm
  .nvmrc
  docs/dev/README.md
  package-lock.json
  package.json
  packages/components/package.json
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
  tekton/build.yaml
  test/presubmit-tests.sh
Labels: size/M, lgtm, approved, kind/misc

#3040 Increase timeout for flaky tests
  src/containers/CreatePipelineRun/CreatePipelineRun.test.jsx
Labels: size/M, lgtm, approved, kind/misc

#3034 Remove Node.js install from build tests
  test/presubmit-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#3041 Improve performance of SASS build step
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#3044 Remove LoadingShell from @tektoncd/dashboard-components
  packages/components/src/components/index.js
  src/containers/App/App.jsx
  src/containers/LoadingShell/LoadingShell.jsx
  src/containers/LoadingShell/LoadingShell.scss
  src/containers/LoadingShell/LoadingShell.stories.jsx
  src/containers/LoadingShell/index.js
  src/containers/index.js
  src/scss/App.scss
Labels: size/XS, lgtm, approved, kind/misc

#3045 Fix Storybook production deploy
  package.json
  packages/components/src/components/Actions/Actions.jsx
  packages/components/src/components/DeleteModal/DeleteModal.jsx
  packages/components/src/components/DetailsHeader/DetailsHeader.jsx
  packages/components/src/components/Header/Header.stories.jsx
  packages/components/src/components/Log/Log.jsx
  packages/components/src/components/Log/Log.stories.jsx
  packages/components/src/components/PageErrorBoundary/PageErrorBoundary.jsx
  packages/components/src/components/PipelineRun/PipelineRun.jsx
  packages/components/src/components/PipelineRuns/PipelineRuns.jsx
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.jsx
  packages/components/src/components/ResourceDetails/ResourceDetails.jsx
  packages/components/src/components/RunHeader/RunHeader.jsx
  packages/components/src/components/StatusIcon/StatusIcon.jsx
  packages/components/src/components/StepDefinition/StepDefinition.jsx
  packages/components/src/components/StepDetails/StepDetails.jsx
  packages/components/src/components/StepDetails/StepDetails.stories.jsx
  packages/components/src/components/Table/Table.jsx
  packages/components/src/components/Tabs/Tabs.stories.jsx
  packages/components/src/components/Task/Task.jsx
  packages/components/src/components/TaskRunDetails/TaskRunDetails.jsx
  packages/components/src/components/TaskRuns/TaskRuns.jsx
  packages/components/src/components/Trigger/Trigger.jsx
  src/containers/ClusterInterceptors/ClusterInterceptors.jsx
  src/containers/ClusterTasks/ClusterTasks.jsx
  src/containers/ClusterTriggerBindings/ClusterTriggerBindings.jsx
  src/containers/CreatePipelineRun/CreatePipelineRun.jsx
  src/containers/CreateTaskRun/CreateTaskRun.jsx
  src/containers/CustomRun/CustomRun.jsx
  src/containers/CustomRuns/CustomRuns.jsx
  src/containers/EventListeners/EventListeners.jsx
  src/containers/HeaderBarContent/HeaderBarContent.jsx
  src/containers/ImportResources/ImportResources.jsx
  src/containers/Interceptors/Interceptors.jsx
  src/containers/PipelineRun/PipelineRun.jsx
  src/containers/PipelineRuns/PipelineRuns.jsx
  src/containers/Pipelines/Pipelines.jsx
  src/containers/ReadWriteRoute/ReadWriteRoute.jsx
  src/containers/ResourceList/ResourceList.jsx
  src/containers/TaskRun/TaskRun.jsx
  src/containers/TaskRuns/TaskRuns.jsx
  src/containers/Tasks/Tasks.jsx
  src/containers/TriggerBindings/TriggerBindings.jsx
  src/containers/TriggerTemplates/TriggerTemplates.jsx
  src/containers/Triggers/Triggers.jsx
Labels: lgtm, size/L, approved, kind/misc

#3043 Replace reference to jest in docs with Vitest
  docs/dev/README.md
Labels: size/XS, lgtm, approved, kind/documentation

#3047 Fix nightly release
  tekton/build.yaml
Labels: size/XS, lgtm, approved, kind/misc

#3048 Update to Storybook v7.3
  package-lock.json
  package.json
Labels: lgtm, size/S, approved, kind/misc

#3050 Update Cypress to v12.17.4
  package-lock.json
  packages/e2e/package.json
Labels: size/XS, lgtm, approved, kind/misc

#3052 Update dev docs with note on colima + kind compatibility issue
  docs/dev/README.md
Labels: size/XS, lgtm, approved, kind/documentation

#3053 Don't include containers in the published storybook
  .storybook/Welcome.mdx
  .storybook/main.js
  .storybook/welcome.scss
Labels: size/M, lgtm, approved, kind/documentation, kind/misc

#3051 Modify Korean translation file
  src/nls/messages_ko.json
Labels: lgtm, size/L, approved, ok-to-test

#3063 Update tests to latest Pipelines release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#3064 Update to latest Carbon 10 releases
  package-lock.json
  package.json
  packages/components/package.json
  packages/graph/package.json
Labels: lgtm, size/S, approved, kind/misc

#3066 Add updated korean translation
  src/nls/messages_ko.json
Labels: lgtm, size/S, approved, ok-to-test, kind/misc

#3065 Handle missing steps gracefully
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: lgtm, size/S, approved, kind/misc

#3067 Update sass to latest release
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#3071 Downgrade carbon-components
  package-lock.json
  package.json
  packages/components/package.json
Labels: kind/bug, size/XS, lgtm, approved

#3072 Update Storybook to latest release
  package-lock.json
  package.json
Labels: lgtm, size/S, approved, kind/misc

#3073 Update to latest Carbon 10 releases
  package-lock.json
  package.json
  packages/components/package.json
  packages/graph/package.json
Labels: lgtm, size/S, approved, kind/misc

#3074 Fix missing translations for status filter dropdown control
  packages/components/src/components/StatusFilterDropdown/StatusFilterDropdown.jsx
Labels: kind/bug, size/XS, lgtm, approved

#3075 Update tests to latest Pipelines release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#3076 Publish v0.39.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#3077 Update npmignore files to reflect recent file extension changes
  packages/components/.npmignore
  packages/utils/.npmignore
Labels: size/XS, lgtm, approved, kind/misc

#3078 Add note to dev doc re. JSX file extension
  docs/dev/README.md
Labels: size/XS, lgtm, approved, kind/documentation

#3082 Update isRunning util to correctly handle 'running finally' states
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
Labels: size/XS, lgtm, approved, kind/misc

#3083 Publish v0.39.0-alpha.2 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#3091 Update vitest to latest release
  package-lock.json
  package.json
  vite.config.js
Labels: size/XS, lgtm, approved, kind/misc

#3081 Display matrix TaskRuns on the PipelineRun details page
  packages/components/src/components/PipelineRun/PipelineRun.jsx
  packages/components/src/components/PipelineRun/PipelineRun.stories.jsx
  packages/components/src/components/PipelineRun/PipelineRun.test.jsx
  packages/components/src/components/Task/Task.jsx
  packages/components/src/components/Task/Task.stories.jsx
  packages/components/src/components/Task/Task.test.jsx
  packages/components/src/components/TaskTree/TaskTree.jsx
  packages/components/src/components/TaskTree/TaskTree.stories.jsx
  packages/utils/src/utils/constants.js
  packages/utils/src/utils/index.js
  src/containers/PipelineRun/PipelineRun.jsx
  src/containers/TaskRun/TaskRun.jsx
Labels: kind/feature, lgtm, size/L, approved

#3093 Update tests to use latest Triggers release
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#3092 Check for the wrong start date
  packages/components/src/components/DetailsHeader/DetailsHeader.jsx
Labels: kind/bug, size/XS, lgtm, approved, ok-to-test

#3094 Add v0.39.0 to the releases doc
  releases.md
Labels: lgtm, size/S, approved, kind/documentation

#3095 Update to Cypress v13
  package-lock.json
  packages/e2e/cypress.config.js
  packages/e2e/package.json
Labels: size/XS, lgtm, approved, kind/misc

#3096 Reduce noise in log output
  packages/components/src/components/DeleteModal/DeleteModal.jsx
  packages/components/src/components/Modal/Modal.jsx
  src/containers/App/App.jsx
  src/containers/App/App.test.jsx
Labels: lgtm, size/S, approved, kind/misc

#3097 Fail early if nvm fails to install Node.js binary
  test/presubmit-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#3098 Portuguese translation
  src/nls/messages_pt.json
Labels: size/M, lgtm, approved, kind/misc
