Repository tektoncd/dashboard, pull requests merged in 2024-07, with the labels that each got.

#3488 Bump cypress from 13.11.0 to 13.12.0
  package-lock.json
  packages/e2e/package.json
Labels: size/XS, lgtm, approved, kind/misc

#3487 Bump sass-embedded from 1.66.1 to 1.77.5
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#3490 Add support for displaying StepActions
  base/200-clusterrole-tenant.yaml
  overlays/patches/read-write/clusterrole-tenant-patch.yaml
  packages/e2e/cypress/fixtures/kinds.json
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/containers/SideNav/SideNav.jsx
  src/routes/pipelines.jsx
Labels: kind/feature, size/M, lgtm, approved

#3491 Update kind walk-through to Kubernetes 1.30
  docs/walkthrough/walkthrough-kind.md
  scripts/prepare-kind-cluster
Labels: size/XS, lgtm, approved, kind/documentation, kind/misc

#3500 Fix rerun from PipelineRun details page
  src/containers/PipelineRun/PipelineRun.jsx
Labels: kind/bug, size/XS, lgtm, approved

#3507 Update obsolete link in kind walk-through
  docs/walkthrough/walkthrough-kind.md
Labels: size/XS, lgtm, approved, kind/documentation

#3508 Update images in kind walk-through
  docs/walkthrough/walkthrough-kind-import.png
  docs/walkthrough/walkthrough-kind-pipelineruns.png
Labels: size/XS, lgtm, approved, kind/documentation

#3518 Publish v0.49.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  packages/components/package.json
  packages/e2e/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#3519 docs: fix logs persistence walkthrough broken url
  docs/install.md
Labels: size/XS, lgtm, approved, kind/documentation, ok-to-test

#3520 Fix the Storybook production build
  packages/graph/src/components/newGraph.scss
Labels: size/XS, lgtm, approved, kind/misc

#3521 Update E2E tests to latest Pipelines and Triggers releases
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc
