Repository tektoncd/dashboard, pull requests merged in 2025-05, with the labels that each got.

#4150 Add v0.57.0 to the releases doc and remove EOL releases
  releases.md
Labels: size/M, lgtm, approved, kind/documentation

#4160 Publish v0.58.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  package.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#4159 Remove support for ClusterTasks
  config/200-clusterrole-backend-view.yaml
  docs/dev/localization/Japanese/term.tsv
  packages/components/src/components/TaskRuns/TaskRuns.jsx
  packages/components/src/components/TaskRuns/TaskRuns.test.jsx
  packages/e2e/cypress/fixtures/kinds.json
  packages/utils/src/utils/constants.js
  packages/utils/src/utils/index.js
  packages/utils/src/utils/index.test.js
  packages/utils/src/utils/router.js
  packages/utils/src/utils/router.test.js
  src/api/clusterTasks.js
  src/api/clusterTasks.test.js
  src/api/index.js
  src/api/index.test.js
  src/api/taskRuns.js
  src/api/taskRuns.test.js
  src/containers/ClusterTasks/ClusterTasks.jsx
  src/containers/ClusterTasks/index.js
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.jsx
  src/containers/ClusterTasksDropdown/ClusterTasksDropdown.test.jsx
  src/containers/ClusterTasksDropdown/index.js
  src/containers/CreateTaskRun/CreateTaskRun.jsx
  src/containers/CreateTaskRun/CreateTaskRun.test.jsx
  src/containers/PipelineRun/PipelineRun.jsx
  src/containers/PipelineRun/PipelineRun.test.jsx
  src/containers/SideNav/SideNav.jsx
  src/containers/TaskRun/TaskRun.jsx
  src/containers/TaskRuns/TaskRuns.jsx
  src/containers/index.js
  src/nls/messages_de.json
  src/nls/messages_en.json
  src/nls/messages_es.json
  src/nls/messages_fr.json
  src/nls/messages_it.json
  src/nls/messages_ja.json
  src/nls/messages_ko.json
  src/nls/messages_pt.json
  src/nls/messages_zh-Hans.json
  src/nls/messages_zh-Hant.json
  src/routes/pipelines.jsx
Labels: size/XXL, lgtm, approved, kind/cleanup, kind/misc

#4169 Remove Storybook addon storysource
  .storybook/main.js
  .storybook/preview.jsx
  package-lock.json
  package.json
  packages/components/src/components/Log/Log.stories.jsx
  packages/components/src/components/PipelineRun/PipelineRun.stories.jsx
  packages/components/src/components/StepDetails/StepDetails.stories.jsx
  src/containers/Header/Header.stories.jsx
Labels: lgtm, size/S, approved, kind/misc

#4182 Fix subpath capitalisation
  tekton/release-pipeline.yaml
Labels: lgtm, size/S, approved, kind/misc

#4195 Upgrade to Storybook v9
  .eslintrc.cjs
  .storybook/Welcome.mdx
  .storybook/main.js
  .storybook/manager.js
  .storybook/theme.js
  package-lock.json
  package.json
  packages/components/src/components/DeleteModal/DeleteModal.stories.js
  packages/components/src/components/KeyValueList/KeyValueList.stories.js
  packages/components/src/components/LabelFilter/LabelFilter.stories.js
  packages/components/src/components/Log/Log.stories.jsx
  packages/components/src/components/LogsToolbar/LogsToolbar.stories.jsx
  packages/components/src/components/PipelineRun/PipelineRun.stories.jsx
  packages/components/src/components/PipelineRuns/PipelineRuns.stories.jsx
  packages/components/src/components/ResourceDetails/ResourceDetails.stories.jsx
  packages/components/src/components/Step/Step.stories.js
  packages/components/src/components/StepDetails/StepDetails.stories.jsx
  packages/components/src/components/Table/Table.stories.jsx
  packages/components/src/components/Task/Task.stories.jsx
  packages/components/src/components/TaskRunDetails/TaskRunDetails.stories.jsx
  packages/components/src/components/TaskTree/TaskTree.stories.jsx
  packages/components/src/components/TextInput/TextInput.stories.js
  packages/graph/src/components/legacy/PipelineGraph.stories.jsx
  packages/graph/src/components/legacy/ZoomablePipelineGraph.stories.jsx
Labels: lgtm, size/L, approved, kind/misc
