Repository tektoncd/dashboard, pull requests merged in 2025-07, with the labels that each got.

#4264 Update Node.js to 20.19 and Chrome to 138
  .nvmrc
  packages/e2e/base-image/Dockerfile
  packages/e2e/base-image/tekton/cronjob.yaml
  tekton/build.yaml
  test/presubmit-tests.sh
Labels: lgtm, size/S, approved, kind/misc

#4271 Update E2E to use new base image with Node.js 20.19 and Chrome 138
  packages/e2e/Dockerfile
Labels: size/XS, lgtm, approved, kind/misc

#4285 Add anti-affinity rules to dashboard's replicas
  config/300-deployment.yaml
Labels: lgtm, size/S, approved

#4294 Update labels modal to automatically focus filter input
  packages/components/src/components/LabelsWithOverflow/LabelsWithOverflow.jsx
  packages/components/src/components/PipelineRun/PipelineRun.stories.jsx
  packages/components/src/components/RunHeader/RunHeader.stories.jsx
Labels: size/M, lgtm, approved, kind/misc

#4318 Publish v0.60.0-alpha.1 of the @tektoncd/dashboard-* packages
  package-lock.json
  package.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#4323 Fix bleed-through for sticky header
  packages/components/src/components/DetailsHeader/DetailsHeader.jsx
Labels: size/M, lgtm, approved, kind/cleanup

#4325 Always display duration on task run and step header
  packages/components/src/components/DetailsHeader/DetailsHeader.jsx
Labels: kind/feature, size/XS, lgtm, approved

#4329 Publish v0.60.0-alpha.2 of the @tektoncd/dashboard-* packages
  package-lock.json
  package.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc
