Repository tektoncd/dashboard, pull requests merged in 2025-03, with the labels that each got.

#4025 Add v0.55.0 to the releases doc
  releases.md
Labels: lgtm, size/S, approved, kind/documentation

#4030 Update E2E tests to Pipelines v0.69
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#4031 Fix dashboard-utils import issue
  packages/utils/src/utils/index.js
  packages/utils/src/utils/router.js
Labels: kind/bug, lgtm, size/S, approved

#4037 Reduce manual steps required to publish npm packages
  package-lock.json
  package.json
  tekton/README.md
Labels: size/M, lgtm, approved, kind/misc

#4040 Publish v0.56.0-alpha.0 of the @tektoncd/dashboard-* packages
  package-lock.json
  package.json
  packages/components/package.json
  packages/graph/package.json
  packages/utils/package.json
Labels: size/XS, lgtm, approved, kind/misc

#4049 npm audit fix
  package-lock.json
Labels: size/XS, lgtm, approved, kind/misc

#4051 Update GitHub Actions to use go.mod to identify correct go version
  .github/workflows/ci.yml
  docs/dev/README.md
Labels: lgtm, size/S, approved, kind/documentation, kind/misc

#4052 Update E2E tests to Pipelines v0.69.1
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#4050 Bump @carbon/react from 1.77.0 to 1.78.2
  package-lock.json
  package.json
Labels: size/XS, lgtm, approved, kind/misc

#4053 Update to golang 1.24
  .github/workflows/ci.yml
  .golangci.yml
  go.mod
  tekton/publish.yaml
Labels: lgtm, size/S, approved, kind/misc

#4059 Bump golang.org/x/oauth2 from v0.23.0 to v0.28.0
  go.mod
  go.sum
Labels: lgtm, size/S, approved, kind/misc

#4077 Bump typescript from 5.2.2 to 5.7.3
  package-lock.json
Labels: size/XS, lgtm, approved, kind/misc

#4078 Fix image SHA used in release pipeline check-github-release step
  tekton/prerelease-checks.yaml
Labels: size/XS, lgtm, approved, kind/misc

#4079 Update release pipeline to use remote resolution
  tekton/kustomization.yaml
  tekton/prerelease-checks.yaml
  tekton/release-pipeline.yaml
Labels: size/M, lgtm, approved, kind/misc

#4080 Consume gcs-upload bundle from GHCR instead of GCR
  tekton/release-pipeline.yaml
Labels: size/XS, lgtm, approved, kind/misc

#4084 Update E2E tests to Pipelines v0.70.0
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#4085 Add v0.56.0 to the releases doc
  releases.md
Labels: lgtm, size/S, approved, kind/documentation
