Repository tektoncd/dashboard, pull requests merged in 2025-06, with the labels that each got.

#4215 Update E2E tests to Pipelines v1.1.0 and Triggers v0.32.0
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved, kind/misc

#4216 Add v0.58.0 to the release docs
  releases.md
Labels: lgtm, size/S, approved, kind/documentation

#4243 Enable Storybook code panel
  .storybook/preview.jsx
Labels: size/XS, lgtm, approved, kind/misc

#4249 bump golangci-lint to v2 config
  .github/workflows/ci.yml
  .golangci.yml
Labels: lgtm, size/L, approved, kind/cleanup

#4259 Add v0.59.0 to the releases doc
  releases.md
Labels: lgtm, size/S, approved, kind/documentation
